force-app/main/default/objects/FIN_InvoiceItem__c/FIN_InvoiceItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>II-{0000000000}</displayFormat>
        <label>Invoice Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_InvoiceItem__c/fields/FIN_ParentInvoiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_ParentInvoiceSchedule__c</fullName>
    <label>Parent Invoice Schedule</label>
    <referenceTo>FIN_InvoiceSchedule__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceItem__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceItem__c/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceSchedule__c/FIN_InvoiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Invoice Schedule</label>
    <nameField>
        <displayFormat>IS-{0000000000}</displayFormat>
        <label>Invoice Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Order__c.field-meta.xml
<CustomField>
    <fullName>FIN_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/Invoices_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoices_Status__c</fullName>
    <label>Invoices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Invoices_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Invoices_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoices_Status__c</fullName>
    <label>Invoices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Invoices_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FIN_Invoices_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>ToBeInvoiced</fullName>
        <label>To Be Invoiced</label>
    </customValue>
    <customValue>
        <fullName>InvoiceScheduled</fullName>
        <label>Invoice in Progress</label>
    </customValue>
    <customValue>
        <fullName>Invoiced</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/testClasses/FIN_InvoiceItemHelperTest.cls
@IsTest
private class FIN_InvoiceItemHelperTest {
    @IsTest
    static void updateStatusesAfterInsert() {
        try {

            Account acc = TestDataFactory.createAccount();
            Contract cntr = TestDataFactory.createParentContract(acc.Id);
            Product2 pro = TestDataFactory.createProduct2();
            PricebookEntry standardPriceEntry = TestDataFactory.createPricebookEntry(pro.Id);
            Order ord = TestDataFactory.createTestOrder(acc.Id);
            FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id, cntr.Id);
            FIN_PaymentDistribution__c paymentdist = TestDataFactory.createPaymentDistribution(payment.Id, null, cntr.Id);
            FIN_InvoiceSchedule__c invoiceSchedule = new FIN_InvoiceSchedule__c();
            insert invoiceSchedule;
            FIN_InvoiceItem__c invoiceItem = new FIN_InvoiceItem__c(
                FIN_PaymentDistribution__c = paymentdist.Id,
                FIN_ParentInvoiceSchedule__c = invoiceSchedule.id);

//            Test.startTest();
            insert invoiceItem;
//            Test.stopTest();
            List<FIN_PaymentDistribution__c> PDList = [
                SELECT Id, RecordTypeId, Invoices_Status__c, FIN_Payment__r.FIN_Order__r.Invoices_Status__c
                FROM FIN_PaymentDistribution__c
            ];


             System.assertEquals(PDList[0].Invoices_Status__c, 'InvoiceScheduled');
             System.assertEquals(PDList[0].FIN_Payment__r.FIN_Order__r.Invoices_Status__c, 'InvoiceScheduled');

        } catch(Exception e) {
            System.debug(e.getMessage());
        }
    }
    @IsTest
    static void updateStatusesBeforeDelete() {
        try {
            Account acc = TestDataFactory.createAccount();
            Contract cntr = TestDataFactory.createParentContract(acc.Id);
            Product2 pro = TestDataFactory.createProduct2();
            PricebookEntry standardPriceEntry = TestDataFactory.createPricebookEntry(pro.Id);
            Order ord = TestDataFactory.createTestOrder(acc.Id);
            FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id, cntr.Id);
            FIN_PaymentDistribution__c paymentdist = TestDataFactory.createPaymentDistribution(payment.Id, null, cntr.Id);
            FIN_InvoiceSchedule__c invoiceSchedule = new FIN_InvoiceSchedule__c();
            insert invoiceSchedule;
            FIN_InvoiceItem__c invoiceItem = new FIN_InvoiceItem__c(
                FIN_PaymentDistribution__c = paymentdist.Id,
                FIN_ParentInvoiceSchedule__c = invoiceSchedule.id);

            insert invoiceItem;
            Test.startTest();

            delete invoiceItem;
            Test.stopTest();

            List<FIN_PaymentDistribution__c> paymeent = [
                SELECT FIN_Payment__r.FIN_Order__r.Invoices_Status__c
                FROM FIN_PaymentDistribution__c
                WHERE FIN_Payment__r.FIN_Order__c = :ord.id
            ] ;

            System.assertEquals(paymeent[0].FIN_Payment__r.FIN_Order__r.Invoices_Status__c, 'ToBeInvoiced');


        } catch(Exception e) {
            System.debug(e.getMessage());
        }
    }
}