force-app/main/default/objects/FIN_InvoiceItem__c/FIN_InvoiceItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>II-{0000000000}</displayFormat>
        <label>Invoice Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_InvoiceItem__c/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceSchedule__c/FIN_InvoiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Invoice Schedule</label>
    <nameField>
        <displayFormat>IS-{0000000000}</displayFormat>
        <label>Invoice Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_InvoiceSchedule__c/fields/FIN_SettlementSchedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_SettlementSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Settlement Schedule</label>
    <referenceTo>FIN_SettlementSchedule__c</referenceTo>
    <relationshipLabel>Invoice Schedules</relationshipLabel>
    <relationshipName>Invoice_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SettlementItem__c/FIN_SettlementItem__c.object-meta.xml
<CustomObject>
    <label>Settlement Item</label>
    <nameField>
        <displayFormat>SI-{0000000000}</displayFormat>
        <label>Settlement Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_InvoiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_InvoiceSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Schedule</label>
    <referenceTo>FIN_InvoiceSchedule__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementSchedule__c/FIN_SettlementSchedule__c.object-meta.xml
<CustomObject>
    <label>Settlement Schedule</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Settlement Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_ToastNotification__e/FIN_ToastNotification__e.object-meta.xml
<CustomObject>
    <label>FIN_ToastNotification</label>
    <pluralLabel>FIN_ToastNotifications</pluralLabel>
</CustomObject>

force-app/main/default/classes/batches/FIN_SettlementDataBatch.cls
public with sharing class FIN_SettlementDataBatch implements Database.Batchable<SObject> {
    private final String query;
    private final String settlementSh;
    private final SObjectType batchType;
    private Map<String, Object> bindVariables = new Map<String, Object>();
    private final Map<Id, FIN_InvoiceSchedule__c> invoiceSh;
    private final Id currentInvoiceSh;
    private final String statusValue;
    public static Integer insertedRecordsCount = 0;

    public FIN_SettlementDataBatch() {
    }
    public FIN_SettlementDataBatch(String query, Map<String, Object> bindVariables, FIN_SettlementSchedule__c settlementSh) {
        this.batchType = Schema.FIN_SettlementItem__c.getSObjectType();
        this.query = query;
        this.settlementSh = settlementSh.Id;
        this.bindVariables = bindVariables;
    }

    public FIN_SettlementDataBatch(String query, Map<String, Object> bindVariables, Map<Id, FIN_InvoiceSchedule__c> invoiceSh, Id currentInvoiceSh) {
        this.batchType = Schema.FIN_InvoiceItem__c.getSObjectType();
        this.invoiceSh = invoiceSh;
        this.bindVariables = bindVariables;
        this.query = query;
        this.currentInvoiceSh = currentInvoiceSh;
    }


    public void execute(Database.BatchableContext param1, List<SObject> scope) {
        List<SObject> records = new List<SObject>();
        switch on batchType.newSObject() {
            when FIN_SettlementItem__c si {
                records.addAll(FIN_SettlementItemsService.createSettlementItems((List<FIN_PaymentDistribution__c>) scope, this.settlementSh));
            } when FIN_InvoiceItem__c ii {
                records.addAll(InvoiceDataController.createInvoiceItemsByType(scope.getSObjectType().getDescribe().getName(),
                        this.invoiceSh, this.currentInvoiceSh, scope));
            }
        }
        Database.update(scope);
        insertedRecordsCount = Database.insert(records).size();
    }

    public void finish(Database.BatchableContext param1) {
//        EventBus.publish(new FIN_ToastNotification__e(Status__c = 'Success',
//                Message__c = insertedRecordsCount + ' records was created successfully'));
    }

    public Database.QueryLocator start(Database.BatchableContext param1) {
        return Database.getQueryLocatorWithBinds(query, bindVariables, AccessLevel.USER_MODE);
    }
}