force-app/main/default/objects/FIN_InvoiceItem__c/FIN_InvoiceItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>II-{0000000000}</displayFormat>
        <label>Invoice Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_InvoiceItem__c/fields/FIN_AccountforInvoice__c.field-meta.xml
<CustomField>
    <fullName>FIN_AccountforInvoice__c</fullName>
    <formula>FIN_LibraryAssociation__r.FIN_Financial_Code__r.FIN_Business_Unit__r.Name
+ &apos;.&apos; +
FIN_LibraryAssociation__r.FIN_Financial_Code__r.FIN_Financial_Chart_of_Accounts__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account # for Invoice</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceItem__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceItem__c/fields/FIN_ParentInvoiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_ParentInvoiceSchedule__c</fullName>
    <label>Parent Invoice Schedule</label>
    <referenceTo>FIN_InvoiceSchedule__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceItem__c/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceItem__c/fields/FIN_SubContract__c.field-meta.xml
<CustomField>
    <fullName>FIN_SubContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SubContract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceItem__c/fields/FIN_TotalGrossAmountforInvoice__c.field-meta.xml
<CustomField>
    <fullName>FIN_TotalGrossAmountforInvoice__c</fullName>
    <formula>IF ( FIN_SalesTransactions__c != null, FIN_SalesTransactions__r.FIN_TotalGrossAmount__c ,
IF ( FIN_PaymentDistribution__c != null, FIN_PaymentDistribution__r.FIN_DistributionAmount__c,
IF ( FIN_Payment__c != null, FIN_Payment__r.FIN_PaymentAmount__c, 0
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Gross Amount for Invoice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceLine__c/FIN_InvoiceLine__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <label>Invoice Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_InvoiceLine__c/fields/FIN_Amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceLine__c/fields/FIN_ParentInvoiceSchedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_ParentInvoiceSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Invoice Schedule</label>
    <referenceTo>FIN_InvoiceSchedule__c</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceLine__c/fields/FIN_Subledger__c.field-meta.xml
<CustomField>
    <fullName>FIN_Subledger__c</fullName>
    <label>Subledger</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Settlement_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_DistributionAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmount__c</fullName>
    <label>Distribution Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distribution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/FIN_SettlementItem__c.object-meta.xml
<CustomObject>
    <label>Settlement Item</label>
    <nameField>
        <displayFormat>SI-{0000000000}</displayFormat>
        <label>Settlement Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_Amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_ParentSettlementSchedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_ParentSettlementSchedule__c</fullName>
    <label>Parent Settlement Schedule</label>
    <referenceTo>FIN_SettlementSchedule__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_SubContract__c.field-meta.xml
<CustomField>
    <fullName>FIN_SubContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SubContract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contract.FIN_ParentContract__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_Amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_Amount__c</fullName>
    <label>Ticket Component Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_InvoiceLine__c.field-meta.xml
<CustomField>
    <fullName>FIN_InvoiceLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line</label>
    <referenceTo>FIN_InvoiceLine__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Sales Transactions</relationshipLabel>
    <relationshipName>Sales_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/SBQQ__ContractedPrice__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__ContractedPriceHelp</customHelpPage>
    <description>Contracted (negotiated) price for a product for a given customer account.</description>
    <label>Contracted Price</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Contracted Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracted Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Financial_Code__c.field-meta.xml
<CustomField>
    <fullName>FIN_Financial_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Code</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>FIN_Financial_Code__c.Region__c</field>
            <operation>equals</operation>
            <valueField>$Source.FIN_Region__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>FIN_Financial_Code__c</referenceTo>
    <relationshipLabel>Contracted Prices</relationshipLabel>
    <relationshipName>Contracted_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Subledger__c.field-meta.xml
<CustomField>
    <fullName>FIN_Subledger__c</fullName>
    <formula>MID(FIN_Financial_Code__r.FIN_SubledgerCodeName__c, 3, LEN(FIN_Financial_Code__r.FIN_SubledgerCodeName__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subledger</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_SubledgerType__c.field-meta.xml
<CustomField>
    <fullName>FIN_SubledgerType__c</fullName>
    <formula>MID(FIN_Financial_Code__r.FIN_SubledgerCodeName__c, 0, 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subledger Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/FIN_Settlement_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>ToBeSettled</fullName>
        <label>To Be Settled</label>
    </customValue>
    <customValue>
        <fullName>Settled</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>ScheduledSettlement</fullName>
        <label>Scheduled for Settlement</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <masterLabel>Settlement Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/services/FIN_SettlementItemsService.cls
public with sharing class FIN_SettlementItemsService {
    public with sharing class FIN_InvoiceItemHelper {

        // Private instance variables
        private Id invoiceScheduleId;
        private Map<Id, FIN_Financial_Code__c> financialCodes;
        private Map<Id, FIN_SubledgerCode__c> subledgerCodes;
        private Map<Id, Account> accounts;
        private Map<String, Order> salesByLookupCode;
        private Map<String, Campaign> eventsByLookupCode;
        private Set<String> channels;
        private Set<Double> uniqueAppliedRates;

        // Constructor
        public FIN_InvoiceItemHelper(Id invoiceScheduleId) {
            this.invoiceScheduleId = invoiceScheduleId;
            this.financialCodes = new Map<Id, FIN_Financial_Code__c>();
            this.subledgerCodes = new Map<Id, FIN_SubledgerCode__c>();
            this.accounts = new Map<Id, Account>();
            this.salesByLookupCode = new Map<String, Order>();
            this.eventsByLookupCode = new Map<String, Campaign>();
            this.channels = new Set<String>();
            this.uniqueAppliedRates = new Set<Double>();
        }


        // Public methods
        public void processInvoiceItems(Id invoiceScheduleId) {
            Map<Id, List<FIN_InvoiceItem__c>> allInvoiceItemsByScheduleId = getAllInvoiceItemsByScheduleId(invoiceScheduleId);
            Set<String> allChannels = getAllChannels(allInvoiceItemsByScheduleId.values());
            Map<Id, Order> allSales = getAllSales(allInvoiceItemsByScheduleId.values());
            Map<Id, Campaign> allEvents = getAllEvents(allInvoiceItemsByScheduleId.values());
            Set<Double> uniqueAppliedRates = getUniqueAppliedRates(allInvoiceItemsByScheduleId.values());

            List<FIN_InvoiceLine__c> invoiceLinesToInsert = new List<FIN_InvoiceLine__c>();

            createAccountSubledgerInvoiceLines(invoiceScheduleId, invoiceLinesToInsert, allInvoiceItemsByScheduleId);
            createAddendumInvoiceLines(invoiceScheduleId, invoiceLinesToInsert, allInvoiceItemsByScheduleId, allChannels, allSales, allEvents, uniqueAppliedRates);
            insertInvoiceLines(invoiceLinesToInsert);
        }

        private Map<Id, List<FIN_InvoiceItem__c>> getAllInvoiceItemsByScheduleId(Id invoiceScheduleId) {
            // TODO: Implement this method
            return null;
        }

        private Set<String> getAllChannels(List<List<FIN_InvoiceItem__c>> allInvoiceItemsByScheduleId) {
            // TODO: Implement this method
            return null;
        }

        private Map<Id, Order> getAllSales(List<List<FIN_InvoiceItem__c>> allInvoiceItemsByScheduleId) {
            // TODO: Implement this method
            return null;
        }

        private Map<Id, Campaign> getAllEvents(List<List<FIN_InvoiceItem__c>> allInvoiceItemsByScheduleId) {
            // TODO: Implement this method
            return null;
        }

        private Set<Double> getUniqueAppliedRates(List<List<FIN_InvoiceItem__c>> allInvoiceItemsByScheduleId) {
            // TODO: Implement this method
            return null;
        }

        private void createAccountSubledgerInvoiceLines(Id invoiceScheduleId, List<FIN_InvoiceLine__c> invoiceLinesToInsert, Map<Id, List<FIN_InvoiceItem__c>> allInvoiceItemsByScheduleId) {
            // TODO: Implement this method
        }

        private void createAddendumInvoiceLines(Id invoiceScheduleId, List<FIN_InvoiceLine__c> invoiceLinesToInsert, Map<Id, List<FIN_InvoiceItem__c>> allInvoiceItemsByScheduleId, Set<String> allChannels, Map<Id, Order> allSales, Map<Id, Campaign> allEvents, Set<Double> uniqueAppliedRates) {
            // TODO: Implement this method
        }

        private void insertInvoiceLines(List<FIN_InvoiceLine__c> invoiceLinesToInsert) {
            // TODO: Implement this method
        }
    }

    public static List<FIN_SettlementItem__c> createSettlementItems(List<FIN_PaymentDistribution__c> listPD, Id settlementSh) {
        List<FIN_SettlementItem__c> settlementItems = new List<FIN_SettlementItem__c>();
        for (FIN_PaymentDistribution__c payment : listPD) {
            payment.FIN_Settlement_Status__c = 'ScheduledSettlement';
            settlementItems.add(new FIN_SettlementItem__c(
                    FIN_PaymentDistribution__c = payment.Id,
                    FIN_ParentSettlementSchedule__c = settlementSh,
                    FIN_SubContract__c = payment.Contract__c,
                    FIN_Amount__c = payment.FIN_DistributionAmount__c,
                    FIN_LibraryAssociation__c = payment.FIN_LibraryAssociation__c
            ));
        }
        return settlementItems;
    }

    // Create a method to get all the invoice items for the given invoice schedule ID
    public static List<FIN_InvoiceItem__c> getAllInvoiceItems(Id isId) {
        // Query all the related invoice items for the given invoice schedule ID
        return [SELECT Id, FIN_LibraryAssociation__r.FIN_SubledgerType__c, FIN_AccountforInvoice__c,
                FIN_LibraryAssociation__r.FIN_Subledger__c, FIN_TotalGrossAmountforInvoice__c,
                FIN_ParentInvoiceSchedule__r.FIN_Mode__c, FIN_TotalAmountbyQty__c, FIN_AmountbyQty__c,
                FIN_AdjustmentforInvoice__c, FIN_EntryType__c, FIN_ManualAmount__c
        FROM FIN_InvoiceItem__c
        WHERE FIN_ParentInvoiceSchedule__c = :isId];
    }

    // Create a method to get all the unique channels from the invoice items
    public static Set<String> getAllChannels(List<FIN_InvoiceItem__c> allIIs) {
        // Create a set to store all the unique channels
        Set<String> channelsSet = new Set<String>();
        // Loop through all the invoice items and add their channel to the set
        for (FIN_InvoiceItem__c ii : allIIs) {
            if (ii.FIN_SalesTransactions__c != null) {
                channelsSet.add(ii.FIN_SalesTransactions__r.FIN_Channel__c);
            } else if (ii.FIN_PaymentDistribution__c != null) {
                channelsSet.add(ii.FIN_PaymentDistribution__r.FIN_Channel__c);
            } else if (ii.FIN_Payment__c != null) {
                channelsSet.add(ii.FIN_Payment__r.FIN_Channel__c);
            }
        }
        return channelsSet;
    }

    // Create a method to get all the unique sales orders from the invoice items
    public static Map<Id, Order> getAllSales(List<FIN_InvoiceItem__c> allIIs) {
        // Create a map to store all the unique sales orders
        Map<Id, Order> salesMap = new Map<Id, Order>();
        // Loop through all the invoice items and add their sales order to the map
        for (FIN_InvoiceItem__c ii : allIIs) {
            if (ii.FIN_SalesTransactions__r != null && ii.FIN_SalesTransactions__r.OrderId != null) {
                salesMap.put(ii.FIN_SalesTransactions__r.OrderId, ii.FIN_SalesTransactions__r.Order);
            } else if (ii.FIN_PaymentDistribution__r != null && ii.FIN_PaymentDistribution__r.FIN_Payment__r != null && ii.FIN_PaymentDistribution__r.FIN_Payment__r.FIN_Order__c != null) {
                salesMap.put(ii.FIN_PaymentDistribution__r.FIN_Payment__r.FIN_Order__c, ii.FIN_PaymentDistribution__r.FIN_Payment__r.FIN_Order__r);
            } else if (ii.FIN_Payment__r != null && ii.FIN_Payment__r.FIN_Order__c != null) {
                salesMap.put(ii.FIN_Payment__r.FIN_Order__c, ii.FIN_Payment__r.FIN_Order__r);
            }
        }
        return salesMap;
    }
}