force-app/main/default/objects/FIN_ResponsePublisher__e/FIN_ResponsePublisher__e.object-meta.xml
<CustomObject>
    <label>Response publisher</label>
    <pluralLabel>FIN_ResponsePublishers</pluralLabel>
</CustomObject>

force-app/main/default/objects/FIN_ResponsePublisher__e/fields/ResponseDTO__c.field-meta.xml
<CustomField>
    <fullName>ResponseDTO__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIN_ResponsePublisher__e/fields/ResponseType__c.field-meta.xml
<CustomField>
    <fullName>ResponseType__c</fullName>
    <label>Response type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/FIN_SystemDataLoadLog__c.object-meta.xml
<CustomObject>
    <label>Finance Raw Data Logs</label>
    <nameField>
        <displayFormat>SDLL-{0000000000}</displayFormat>
        <label>System Data Load Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Raw Data Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/triggerHandlers/FIN_ResponsePublisherTriggerHandler.cls
public with sharing class FIN_ResponsePublisherTriggerHandler extends TriggerHandler {
    public override void afterInsert() {
        for (FIN_ResponsePublisher__e responsePublisher : (List<FIN_ResponsePublisher__e>) this.triggerNew) {
                if (responsePublisher.ResponseType__c == FIN_SystemDataLoadLog__c.getSObjectType().getDescribe().getName()) {
                    FIN_ResponsePublisherService.processSystemDataLoadLogResponse(responsePublisher.ResponseDTO__c);
                }
        }
    }
}