force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testClasses/FIN_UnclassifiedRecordsControllerTest.cls
@IsTest
public with sharing class FIN_UnclassifiedRecordsControllerTest {
    @IsTest
    static void testOnSalesClassify() {
        try {
            Test.startTest();
            PageReference pageRef = Page.ClassifySalesRecords;

            Account acc = TestDataFactory.createAccount();
            Order ord = TestDataFactory.createTestOrder(acc.Id);

            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('id', ord.Id);

            ApexPages.StandardSetController sc = new ApexPages.StandardSetController(new List<Order>{
                ord
            });
            FIN_UnclassifiedRecordsController controller = new FIN_UnclassifiedRecordsController(sc);

            System.assertNotEquals(null, controller.onSalesClassify());
            Test.stopTest();
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }

    @IsTest
    static void testOnPaymentsClassify() {
        try {
            Test.startTest();
            PageReference pageRef = Page.ClassifySalesRecords;

            Account acc = TestDataFactory.createAccount();
            Order ord = TestDataFactory.createTestOrder(acc.Id);
            FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id,null);

            Test.setCurrentPage(pageRef);

            ApexPages.StandardSetController sc = new ApexPages.StandardSetController(new List<FIN_Payment__c>{
                payment
            });
            FIN_UnclassifiedRecordsController controller = new FIN_UnclassifiedRecordsController(sc);

            System.assertNotEquals(null, controller.onPaymentsClassify());
            Test.stopTest();
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }

    @IsTest
    static void testPaymentsDistributionClassify() {
        try {
            Test.startTest();
            PageReference pageRef = Page.ClassifySalesRecords;

            Account acc = TestDataFactory.createAccount();
            Contract contract = TestDataFactory.createParentContract(acc.Id);
            Order ord = TestDataFactory.createTestOrderWithContract(acc.Id, contract.Id);
            FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id,contract.Id);
            FIN_PaymentDistribution__c paymentdist = TestDataFactory.createPaymentDistribution(payment.Id, null, contract.Id);

            Test.setCurrentPage(pageRef);

            ApexPages.StandardSetController sc = new ApexPages.StandardSetController(new List<FIN_PaymentDistribution__c>{
                paymentdist
            });
            FIN_UnclassifiedRecordsController controller = new FIN_UnclassifiedRecordsController(sc);

            System.assertNotEquals(null, controller.onPaymentsDistributionClassify());
            Test.stopTest();
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }
}