force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Settlement_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journalizing_Schedule__c/Journalizing_Schedule__c.object-meta.xml
<CustomObject>
    <label>Journalizing Schedule</label>
    <nameField>
        <displayFormat>JS-{0000000000}</displayFormat>
        <label>Journalizing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journalizing Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journalizing_Schedule__c/fields/FIN_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Journalizing_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Journalizing_Schedule__c/fields/FIN_Type__c.field-meta.xml
<CustomField>
    <fullName>FIN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDs</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/FIN_Journalizing_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ToBePosted</fullName>
        <label>To be Posted</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>Exported</fullName>
    </customValue>
    <customValue>
        <fullName>Posted</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <customValue>
        <fullName>PartiallyPosted</fullName>
        <isActive>false</isActive>
        <label>Partially Posted</label>
    </customValue>
    <masterLabel>Journalizing Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FIN_Settlement_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>ToBeSettled</fullName>
        <label>To Be Settled</label>
    </customValue>
    <customValue>
        <fullName>Settled</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>ScheduledSettlement</fullName>
        <label>Scheduled for Settlement</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <masterLabel>Settlement Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/testClasses/JournalizingDataControllerTest.cls
@IsTest
public with sharing class JournalizingDataControllerTest {
    @IsTest
    static void testCreateJI() {
        Account acc = TestDataFactory.createAccount();

        Contract parentContract = TestDataFactory.createParentContract(acc.Id);
        Contract contract = TestDataFactory.createContract(acc.Id, parentContract.Id);

        Order ord = TestDataFactory.createTestOrderWithContract(acc.Id, contract.Id);
        FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id, contract.Id);
        FIN_Payment__c payment2 = TestDataFactory.createPayment(ord.Id, contract.Id);
        FIN_PaymentDistribution__c paymentdist = TestDataFactory.createPaymentDistribution(payment.Id, null, contract.Id);
        paymentdist.FIN_Settlement_Status__c = 'ToBeSettled';
        update paymentdist;

        Journalizing_Schedule__c js = TestDataFactory.createJournalizingSchedule(contract.Id);
        js.FIN_Type__c = 'PDs';
        js.FIN_Status__c = 'InProgress';
        update js;

        Integer numOfNewJI = JournalizingDataController.createJI(new List<Id>{
            paymentdist.Id
        }, 'PDs', js.Id);
        Assert.areEqual(1, numOfNewJI);

        Journalizing_Schedule__c js2 = TestDataFactory.createJournalizingSchedule(contract.Id);
        js2.FIN_Type__c = 'Payments';
        js2.FIN_Status__c = 'InProgress';
        update js2;

        Integer numOfNewJI2 = JournalizingDataController.createJI(new List<Id>{
            payment2.Id
        }, 'Payments', js2.Id);
        Assert.areEqual(1, numOfNewJI2);
    }

    @IsTest
    static void testGetRelatedRecords() {
        Account acc = TestDataFactory.createAccount();

        Contract parentContract = TestDataFactory.createParentContract(acc.Id);
        Contract contract = TestDataFactory.createContract(acc.Id, parentContract.Id);

        Order ord = TestDataFactory.createTestOrderWithContract(acc.Id, contract.Id);
        FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id, contract.Id);
        FIN_Payment__c payment2 = TestDataFactory.createPayment(ord.Id, contract.Id);
        FIN_PaymentDistribution__c paymentdist = TestDataFactory.createPaymentDistribution(payment.Id, null, contract.Id);
        paymentdist.FIN_Settlement_Status__c = 'ToBeSettled';
        update paymentdist;

        Journalizing_Schedule__c js = TestDataFactory.createJournalizingSchedule(contract.Id);
        js.FIN_Type__c = 'PDs';
        js.FIN_Status__c = 'InProgress';
        update js;

        Integer numOfNewJI = JournalizingDataController.createJI(new List<Id>{
            paymentdist.Id
        }, 'PDs', js.Id);

        List<Contract> listRelatedRecords = JournalizingDataController.getRelatedRecords(js.Id);
        Assert.areEqual(1, listRelatedRecords.size());

        Journalizing_Schedule__c js2 = TestDataFactory.createJournalizingSchedule(contract.Id);

        js2.FIN_Type__c = 'Payments';
        js2.FIN_Status__c = 'InProgress';
        update js2;

        Integer numOfNewJI2 = JournalizingDataController.createJI(new List<Id>{
            payment2.Id
        }, 'Payments', js2.Id);

        List<Contract> listRelatedRecords2 = JournalizingDataController.getRelatedRecords(js2.Id);
        Assert.areEqual(1, listRelatedRecords2.size());
    }

    @IsTest
    static void testDeleteJI() {
        Account acc = TestDataFactory.createAccount();

        Contract parentContract = TestDataFactory.createParentContract(acc.Id);
        Contract contract = TestDataFactory.createContract(acc.Id, parentContract.Id);

        Order ord = TestDataFactory.createTestOrderWithContract(acc.Id, contract.Id);
        FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id, contract.Id);
        FIN_PaymentDistribution__c paymentdist = TestDataFactory.createPaymentDistribution(payment.Id, null, contract.Id);
        paymentdist.FIN_Settlement_Status__c = 'ToBeSettled';
        update paymentdist;

        Journalizing_Schedule__c js = TestDataFactory.createJournalizingSchedule(contract.Id);
        js.FIN_Type__c = 'PDs';
        js.FIN_Status__c = 'InProgress';
        update js;

        Integer numOfNewJI = JournalizingDataController.createJI(new List<Id>{
            paymentdist.Id
        }, 'PDs', js.Id);

        Integer numOfDeletedJI = JournalizingDataController.removeRelatedJIs(new List<Id>{
            contract.Id
        }, js.Id);
        Assert.areEqual(1, numOfDeletedJI);

        List<Contract> listRelatedRecords = JournalizingDataController.getRelatedRecords(js.Id);
        Assert.areEqual(0, listRelatedRecords.size());
    }
}