force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Order__c.field-meta.xml
<CustomField>
    <fullName>FIN_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Settlement_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_DistributionAmountNetofTaxAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmountNetofTaxAmount__c</fullName>
    <label>Distribution Amount - Net of Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distribution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/FIN_SettlementItem__c.object-meta.xml
<CustomObject>
    <label>Settlement Item</label>
    <nameField>
        <displayFormat>SI-{0000000000}</displayFormat>
        <label>Settlement Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_ParentSettlementSchedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_ParentSettlementSchedule__c</fullName>
    <label>Parent Settlement Schedule</label>
    <referenceTo>FIN_SettlementSchedule__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementSchedule__c/FIN_SettlementSchedule__c.object-meta.xml
<CustomObject>
    <label>Settlement Schedule</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Settlement Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SettlementSchedule__c/fields/FIN_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SettlementInProgress</fullName>
                <default>true</default>
                <label>Settlement In Progress</label>
            </value>
            <value>
                <fullName>Remittance</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Settlement_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Remittance_Payout__c/Remittance_Payout__c.object-meta.xml
<CustomObject>
    <label>Remittance Payout</label>
    <nameField>
        <displayFormat>RP-{0000000000}</displayFormat>
        <label>Remittance Payout Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remittance Payouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance_Payout__c/fields/FIN_RemittancePayoutAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_RemittancePayoutAmount__c</fullName>
    <label>Remittance Payout Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Remittance_Payout__c/fields/FIN_SettlementSchedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_SettlementSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Settlement Process</label>
    <referenceTo>FIN_SettlementSchedule__c</referenceTo>
    <relationshipLabel>Remittance Payouts</relationshipLabel>
    <relationshipName>Remittance_Payouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/SBQQ__ContractedPrice__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__ContractedPriceHelp</customHelpPage>
    <description>Contracted (negotiated) price for a product for a given customer account.</description>
    <label>Contracted Price</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Contracted Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracted Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Component_Number__c.field-meta.xml
<CustomField>
    <fullName>FIN_Component_Number__c</fullName>
    <inlineHelpText>Indicates what Number the Product Component is within a Context</inlineHelpText>
    <label>Component Key</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Fee_and_Component__c.field-meta.xml
<CustomField>
    <fullName>FIN_Fee_and_Component__c</fullName>
    <label>Fee and Component</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AXS Fee</fullName>
            </value>
            <value>
                <fullName>AXS Payment Fee</fullName>
            </value>
            <value>
                <fullName>Venue Facility Fee</fullName>
            </value>
            <value>
                <fullName>Venue Fee</fullName>
            </value>
            <value>
                <fullName>Venue Lift</fullName>
            </value>
            <value>
                <fullName>Venue Uplift</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Status__c</fullName>
    <formula>IF (
    ISBLANK(SBQQ__EffectiveDate__c) &amp;&amp; ISBLANK(SBQQ__ExpirationDate__c),
    IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;,
    IF (
        NOT(ISBLANK(SBQQ__EffectiveDate__c)) &amp;&amp; NOT(ISBLANK(SBQQ__ExpirationDate__c)) &amp;&amp;
        TODAY()&lt;= SBQQ__ExpirationDate__c &amp;&amp; TODAY()&gt;= SBQQ__EffectiveDate__c,
        IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;,
        IF (
            NOT(ISBLANK(SBQQ__EffectiveDate__c)) &amp;&amp; ISBLANK(SBQQ__ExpirationDate__c) &amp;&amp; TODAY()&gt;= SBQQ__EffectiveDate__c,
            IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;,
            IF (
                NOT(ISBLANK(SBQQ__ExpirationDate__c)) &amp;&amp; ISBLANK(SBQQ__EffectiveDate__c) &amp;&amp; TODAY()&lt;= SBQQ__ExpirationDate__c,
                IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;, IMAGE(&apos;/img/samples/flag_red.gif&apos;, &apos;red&apos;) + &apos; Inactive&apos;)
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Ticket_price_Component__c.field-meta.xml
<CustomField>
    <fullName>FIN_Ticket_price_Component__c</fullName>
    <label>Ticket Price and Component</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AXS Payment Fee</fullName>
            </value>
            <value>
                <fullName>AXS Premium Fee</fullName>
            </value>
            <value>
                <fullName>AXS Ticket Fee</fullName>
            </value>
            <value>
                <fullName>Venue Delivery Fee</fullName>
            </value>
            <value>
                <fullName>Venue Premium Fee</fullName>
            </value>
            <value>
                <fullName>Venue Ticket Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <description>Account for which this price was negotiated.</description>
    <inlineHelpText>Account for which this price was negotiated.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracted Prices</relationshipLabel>
    <relationshipName>R00N70000001olI5EAI</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/FIN_Settlement_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>ToBeSettled</fullName>
        <label>To Be Settled</label>
    </customValue>
    <customValue>
        <fullName>Settled</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>ScheduledSettlement</fullName>
        <label>Scheduled for Settlement</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <masterLabel>Settlement Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/testClasses/FIN_SettlementScheduleHelperTest.cls
@IsTest
private class FIN_SettlementScheduleHelperTest {
    @IsTest
    static void updateStatusesAfterUpdate() {
        try {
            Account acc = TestDataFactory.createAccount();
            Contract parentContract = TestDataFactory.createParentContract(acc.Id);
            Contract contract = TestDataFactory.createContract(acc.Id, parentContract.Id);

            Order ord = TestDataFactory.createTestOrderWithContract(acc.Id, contract.Id);
            FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id, contract.Id);
            FIN_PaymentDistribution__c paymentdist = TestDataFactory.createPaymentDistribution(payment.Id, null, contract.Id);
            FIN_SettlementSchedule__c settlementSchedule = TestDataFactory.createSettlementSchedule(contract.Id);

            FIN_SettlementItem__c settItem = TestDataFactory.createSettlementItem(contract.Id, settlementSchedule.Id, paymentdist.Id);

            Test.startTest();
            settlementSchedule.FIN_Status__c = 'Complete';
            update settlementSchedule;

            List<FIN_PaymentDistribution__c> PDList = [
                SELECT Id, RecordTypeId, FIN_Settlement_Status__c, FIN_Payment__r.FIN_Order__r.Settlement_Status__c
                FROM FIN_PaymentDistribution__c
            ];
            //System.assertEquals(PDList[0].FIN_Settlement_Status__c, 'Invoiced');

            settlementSchedule.FIN_Status__c = 'Void';
            update settlementSchedule;


            List<FIN_PaymentDistribution__c> PDList1 = [
                SELECT Id, RecordTypeId, FIN_Settlement_Status__c, FIN_Payment__r.FIN_Order__r.Settlement_Status__c
                FROM FIN_PaymentDistribution__c
            ];
            System.assertEquals(PDList1[0].FIN_Settlement_Status__c, 'Voided');

            Test.stopTest();
        } catch(Exception e) {
            System.debug(e.getMessage());
        }
    }
    @IsTest
    static void testCreateRemittancePayoutsAfterUpdateTicketPriceComponent() {
        try {

            Account acc = TestDataFactory.createAccount();
            Contract parentContract = TestDataFactory.createParentContract(acc.Id);
            Contract contract = TestDataFactory.createContract(acc.Id, parentContract.Id);
            Product2 pro = TestDataFactory.createProduct2();
            PricebookEntry standardPriceEntry = TestDataFactory.createPricebookEntry(pro.Id);
            Order ord = TestDataFactory.createTestOrderWithContract(acc.Id, contract.Id);
            FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id, contract.Id);
            FIN_PaymentDistribution__c paymentdist = TestDataFactory.createPaymentDistribution(payment.Id, null, contract.Id);
            paymentdist.FIN_DistributionAmountNetofTaxAmount__c = 10;
            update paymentdist;
            FIN_SettlementSchedule__c settlementSchedule = TestDataFactory.createSettlementSchedule(contract.Id);

            SBQQ__ContractedPrice__c library = new SBQQ__ContractedPrice__c(
                SBQQ__Account__c = acc.id,
                FIN_Component_Number__c = 1,
                FIN_Ticket_price_Component__c = 'Venue Delivery Fee',
                //FIN_Fee_and_Component__c = 'Venue Fee',
                SBQQ__Price__c = 100,
                SBQQ__FilterField__c = 'Product',
                SBQQ__Operator__c = 'equals');
            insert library;

            FIN_SettlementItem__c settItem = TestDataFactory.createSettlementItem(contract.Id, settlementSchedule.Id, paymentdist.Id);
            settItem.FIN_LibraryAssociation__c = library.Id;
            update settItem;

            Test.startTest();
            settlementSchedule.FIN_Status__c = 'Remittance';
            update settlementSchedule;

            List<FIN_PaymentDistribution__c> PDList = [
                SELECT Id, FIN_DistributionAmountNetofTaxAmount__c
                FROM FIN_PaymentDistribution__c
            ];
            System.assertEquals(PDList[0].FIN_DistributionAmountNetofTaxAmount__c, 10);

        } catch(Exception e) {
            System.debug(e.getMessage());
        }
    }
    
    @IsTest
    static void testCreateRemittancePayoutsAfterUpdateFeeAndComponent() {
        try {

            Account acc = TestDataFactory.createAccount();
            Contact cont = TestDataFactory.createContactForAccount(acc.Id, 'test@g.com');
            Product2 pro = TestDataFactory.createProduct2();
            PricebookEntry standardPriceEntry = TestDataFactory.createPricebookEntry(pro.Id);
            Order ord = TestDataFactory.createTestOrder(acc.Id);
            FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id, cont.Id);
            FIN_PaymentDistribution__c paymentdist = TestDataFactory.createPaymentDistribution(payment.Id, null,cont.Id);
            paymentdist.FIN_DistributionAmountNetofTaxAmount__c = 10;
            update paymentdist;

            FIN_SettlementSchedule__c settlementSchedule = new FIN_SettlementSchedule__c();
            insert settlementSchedule;

            SBQQ__ContractedPrice__c library = new SBQQ__ContractedPrice__c(
                SBQQ__Account__c = acc.id,
                FIN_Component_Number__c = 1,
                //FIN_Ticket_price_Component__c = 'Venue Delivery Fee',
                FIN_Fee_and_Component__c = 'Venue Fee',
                SBQQ__Price__c = 100,
                SBQQ__FilterField__c = 'Product',
                SBQQ__Operator__c = 'equals');
            insert library;

            FIN_SettlementItem__c settlementItem = new FIN_SettlementItem__c(
                FIN_PaymentDistribution__c = paymentdist.Id,
                FIN_ParentSettlementSchedule__c = settlementSchedule.id,
                FIN_LibraryAssociation__c = library.id);
            insert settlementItem;
            Test.startTest();
            settlementSchedule.FIN_Status__c = 'Remittance';
            update settlementSchedule;

            List<Remittance_Payout__c> PDList = [
                SELECT Id, FIN_RemittancePayoutAmount__c
                FROM Remittance_Payout__c
            ];
            System.assertEquals(PDList[0].FIN_RemittancePayoutAmount__c, 10);

        } catch(Exception e) {
            System.debug(e.getMessage());
        }
    }
}