force-app/main/default/objects/ConsumptionSchedule/fields/Accumulation_to_Target__c.field-meta.xml
<CustomField>
    <fullName>Accumulation_to_Target__c</fullName>
    <label>Accumulation to Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/fields/FIN_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FIN_Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/fields/Recoupment_Balance__c.field-meta.xml
<CustomField>
    <fullName>Recoupment_Balance__c</fullName>
    <description>Recoupment balance for Advance Recoupment accumulation rule</description>
    <inlineHelpText>Recoupment balance for Advance Recoupment accumulation rule</inlineHelpText>
    <label>Recoupment Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/recordTypes/Accumulation_to_Target.recordType-meta.xml
<RecordType>
    <fullName>Accumulation_to_Target</fullName>
    <active>true</active>
    <description>Accumulation to Target</description>
    <label>Accumulation to Target</label>
</RecordType>

force-app/main/default/objects/ConsumptionSchedule/recordTypes/Advance_Recoupment.recordType-meta.xml
<RecordType>
    <fullName>Advance_Recoupment</fullName>
    <active>true</active>
    <description>Advance Recoupment</description>
    <label>Advance Recoupment</label>
</RecordType>

force-app/main/default/classes/testClasses/FIN_ConsumptionScheduleHelperTest.cls
@IsTest
private class FIN_ConsumptionScheduleHelperTest {
    @IsTest
    static void createConsumptionRates() {
        try {

            RecordType rtActoTarget = [
                SELECT Id, DeveloperName
                FROM RecordType
                WHERE SobjectType = 'ConsumptionSchedule'
                AND DeveloperName = 'Accumulation_to_Target'
            ];
            RecordType rtAdvRec = [
                SELECT Id, DeveloperName
                FROM RecordType
                WHERE SobjectType = 'ConsumptionSchedule'
                AND DeveloperName = 'Advance_Recoupment'
            ];

            ConsumptionSchedule newCS1 = new ConsumptionSchedule(
                RecordTypeId = rtActoTarget.Id,
                Name = 'test',
                FIN_Start_Date__c = Date.TODAY()-1,
                Accumulation_to_Target__c = 100
            );
            ConsumptionSchedule newCS2 = new ConsumptionSchedule(
                RecordTypeId = rtActoTarget.Id,
                Name = 'test',
                FIN_Start_Date__c = Date.TODAY()-1
            );
            ConsumptionSchedule newCS3 = new ConsumptionSchedule(
                RecordTypeId = rtAdvRec.Id,
                Name = 'test',
                FIN_Start_Date__c = Date.TODAY()-1,
                Recoupment_Balance__c = 100
            );
            insert newCS1;
            insert newCS2;
            insert newCS3;


            List<ConsumptionRate> crList = [
                SELECT ID
                FROM ConsumptionRate];

            System.assertEquals(3, crList.size());

        } catch(Exception e) {
            System.debug(e.getMessage());
        }
    }
}