force-app/main/default/objects/FIN_RetroactiveAdjustment__c/FIN_RetroactiveAdjustment__c.object-meta.xml
<CustomObject>
    <label>Retroactive Adjustment</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Retroactive Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retroactive Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_Amount__c</fullName>
    <label>Ticket Component Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_Amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_Amount__c</fullName>
    <label>Ticket Component Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/testClasses/FIN_OrderItemHelperTest.cls
@IsTest
private class FIN_OrderItemHelperTest {
    @IsTest
    static void testOrderItemUpdate() {
        try {
            List<FIN_RetroactiveAdjustment__c> oldRetroList = [
                SELECT Id
                FROM FIN_RetroactiveAdjustment__c
            ];
            Id orderRecordTypeId = Schema.SObjectType.FIN_RetroactiveAdjustment__c.getRecordTypeInfosByName().get('Order Product').getRecordTypeId();
            Account acc = TestDataFactory.createAccount();
            Contact cont = TestDataFactory.createContactForAccount(acc.Id, 'test@g.com');
            Product2 pro = TestDataFactory.createProduct2();
            Order ord = TestDataFactory.createTestOrder(acc.Id);
            PricebookEntry standardPriceEntry = TestDataFactory.createPricebookEntry(pro.Id);
            OrderItem orderItem = TestDataFactory.createTestOrderLine(ord.Id, pro.Id, standardPriceEntry.Id);
            
            orderItem.FIN_Amount__c = 120;
            
            update orderItem;

            List<FIN_RetroactiveAdjustment__c> newRetroList = [
                SELECT Id, RecordTypeId
                FROM FIN_RetroactiveAdjustment__c
            ];

           System.assertEquals(oldRetroList.size()+1, newRetroList.size());
           System.assertEquals(newRetroList[0].RecordTypeId, orderRecordTypeId);
        } catch(Exception e) {
            System.debug(e.getMessage());
        }
    }
}