force-app/main/default/objects/Accumulator_Condition__c/Accumulator_Condition__c.object-meta.xml
<CustomObject>
    <label>Consumption Schedule Condition</label>
    <nameField>
        <displayFormat>CSC-{00000}</displayFormat>
        <label>Consumption Schedule Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumption Schedule Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accumulator_Condition__c/fields/FIN_Consumption_Schedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_Consumption_Schedule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Consumption Schedule</label>
    <referenceTo>ConsumptionSchedule</referenceTo>
    <relationshipName>Accumulator_Conditions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accumulator_Condition__c/fields/FIN_Number__c.field-meta.xml
<CustomField>
    <fullName>FIN_Number__c</fullName>
    <label>Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Accumulator_Condition__c/fields/FIN_Object_Attribute__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object_Attribute__c</fullName>
    <label>Object Attribute</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Number</fullName>
            </value>
            <value>
                <fullName>Adjustment_Amount__c</fullName>
                <label>Adjustment Amount</label>
            </value>
            <value>
                <fullName>ApprovalStatus__c</fullName>
                <label>Approval Status</label>
            </value>
            <value>
                <fullName>FIN_BaseComp_Total_NoTax__c</fullName>
                <label>BaseComp Total No Tax</label>
            </value>
            <value>
                <fullName>FIN_BaseCompGrandTotal__c</fullName>
                <label>Base Comp Grand Total</label>
            </value>
            <value>
                <fullName>FIN_Channel__c</fullName>
                <label>Channel</label>
            </value>
            <value>
                <fullName>ContractName</fullName>
                <label>Contract Name</label>
            </value>
            <value>
                <fullName>SBQQ__ContractingMethod__c</fullName>
                <label>Contracting Method</label>
            </value>
            <value>
                <fullName>FIN_CurrentPaidAmount__c</fullName>
                <label>Current Paid Amount</label>
            </value>
            <value>
                <fullName>FIN_CustomerID__c</fullName>
                <label>Customer ID</label>
            </value>
            <value>
                <fullName>FIN_Entity_ID__c</fullName>
                <label>Entity ID</label>
            </value>
            <value>
                <fullName>FIN_Entity_Name__c</fullName>
                <label>Entity Name</label>
            </value>
            <value>
                <fullName>FIN_EventZoneGlCode__c</fullName>
                <label>Event Zone GL Code</label>
            </value>
            <value>
                <fullName>FIN_FinancialAdjCount__c</fullName>
                <label>Financial Adj Count</label>
            </value>
            <value>
                <fullName>FIN_GLCode__c</fullName>
                <label>GL Code</label>
            </value>
            <value>
                <fullName>Invoices_Status__c</fullName>
                <label>Invoices Status</label>
            </value>
            <value>
                <fullName>FIN_Journalizing_Status__c</fullName>
                <label>Journalizing Status</label>
            </value>
            <value>
                <fullName>FIN_MOD__c</fullName>
                <label>MOD</label>
            </value>
            <value>
                <fullName>FIN_MODType__c</fullName>
                <label>MOD Type</label>
            </value>
            <value>
                <fullName>FIN_OfferLookup__c</fullName>
                <label>Offer Lookup</label>
            </value>
            <value>
                <fullName>FIN_OfferName__c</fullName>
                <label>Offer Name</label>
            </value>
            <value>
                <fullName>FIN_Offer_Type__c</fullName>
                <label>Offer Type</label>
            </value>
            <value>
                <fullName>FIN_Operator__c</fullName>
                <label>Operator</label>
            </value>
            <value>
                <fullName>FIN_OrderID__c</fullName>
                <label>Order ID</label>
            </value>
            <value>
                <fullName>FIN_Outlet__c</fullName>
                <label>Outlet</label>
            </value>
            <value>
                <fullName>SBQQ__PaymentTerm__c</fullName>
                <label>Payment Term</label>
            </value>
            <value>
                <fullName>PoNumber</fullName>
                <label>PO Number</label>
            </value>
            <value>
                <fullName>SBQQ__PriceCalcStatus__c</fullName>
                <label>Price Calc Status</label>
            </value>
            <value>
                <fullName>SBQQ__PriceCalcStatusMessage__c</fullName>
                <label>Price Calc Status Message</label>
            </value>
            <value>
                <fullName>FIN_PriceCode__c</fullName>
                <label>Price Code</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accumulator_Condition__c/fields/FIN_Value__c.field-meta.xml
<CustomField>
    <fullName>FIN_Value__c</fullName>
    <label>Value</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accumulator_Condition__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Either Apply the Conditions or select a Library Association</inlineHelpText>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FIN_Payment__c</fullName>
                <label>Payment</label>
            </value>
            <value>
                <fullName>FIN_PaymentDistribution__c</fullName>
                <label>Payment Distribution</label>
            </value>
            <value>
                <fullName>FIN_SalesTransactions__c</fullName>
                <label>Sales Transaction</label>
            </value>
            <value>
                <fullName>Contract</fullName>
                <isActive>false</isActive>
                <label>Contract</label>
            </value>
            <value>
                <fullName>Financial Code</fullName>
                <isActive>false</isActive>
                <label>Financial Code</label>
            </value>
            <value>
                <fullName>Library Association</fullName>
                <isActive>false</isActive>
                <label>Library Association</label>
            </value>
            <value>
                <fullName>Order</fullName>
                <isActive>false</isActive>
                <label>Sales</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accumulator_Condition__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&lt;&gt;</fullName>
            </value>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Consumption Schedules</relationshipLabel>
    <relationshipName>Consumption_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/fields/FIN_Actual_Count__c.field-meta.xml
<CustomField>
    <fullName>FIN_Actual_Count__c</fullName>
    <label>Actual Ticket Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/fields/FIN_Conditional_Logic__c.field-meta.xml
<CustomField>
    <fullName>FIN_Conditional_Logic__c</fullName>
    <label>Conditional Logic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AND</fullName>
                <default>true</default>
                <label>AND</label>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>Custom Logic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/fields/FIN_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FIN_Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/recordTypes/Ticket_Quantity.recordType-meta.xml
<RecordType>
    <fullName>Ticket_Quantity</fullName>
    <active>true</active>
    <description>Ticket Quantity</description>
    <label>Ticket Quantity</label>
</RecordType>

force-app/main/default/objects/FIN_Applied_Accumulators__c/FIN_Applied_Accumulators__c.object-meta.xml
<CustomObject>
    <label>Applied Accumulators</label>
    <nameField>
        <displayFormat>AppAcc - {0000}</displayFormat>
        <label>Applied Accumulators Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applied Accumulators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Applied_Accumulators__c/fields/FIN_Consumption_Schedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_Consumption_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consumption Schedule</label>
    <referenceTo>ConsumptionSchedule</referenceTo>
    <relationshipLabel>Applied Accumulators</relationshipLabel>
    <relationshipName>Applied_Accumulators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceSchedule__c/FIN_InvoiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Invoice Schedule</label>
    <nameField>
        <displayFormat>IS-{0000000000}</displayFormat>
        <label>Invoice Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/Invoices_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoices_Status__c</fullName>
    <label>Invoices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Invoices_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Channel__c.field-meta.xml
<CustomField>
    <fullName>FIN_Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Back Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Invoices_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoices_Status__c</fullName>
    <label>Invoices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Invoices_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FIN_Invoices_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>ToBeInvoiced</fullName>
        <label>To Be Invoiced</label>
    </customValue>
    <customValue>
        <fullName>InvoiceScheduled</fullName>
        <label>Invoice in Progress</label>
    </customValue>
    <customValue>
        <fullName>Invoiced</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/testClasses/FIN_RecalculateAccumulatorsTest.cls
@IsTest
private class FIN_RecalculateAccumulatorsTest {
    @IsTest
    static void testGetInvoiceSchedule() {
        try {
            Account acc = TestDataFactory.createAccount();

            Contract parentContract = TestDataFactory.createParentContract(acc.Id);
            Contract contract = TestDataFactory.createContract(acc.Id, parentContract.Id);

            Order ord = TestDataFactory.createTestOrderWithContract(acc.Id, contract.Id);
            FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id, contract.Id);
            FIN_PaymentDistribution__c paymentdist = TestDataFactory.createPaymentDistribution(payment.Id, null,contract.Id);
            paymentdist.Invoices_Status__c = 'ToBeInvoiced';
            paymentdist.FIN_Channel__c = 'Web';
            update paymentdist;

            ConsumptionSchedule cs = new ConsumptionSchedule(
                RecordTypeId = Schema.SObjectType.ConsumptionSchedule.getRecordTypeInfosByDeveloperName()
                    .get('Ticket_Quantity').getRecordTypeId(),
                Name = 'Test',
                FIN_Start_Date__c = Date.today(),
                BillingTerm = 12,
                BillingTermUnit = 'Month',
                Type = 'Range',
                RatingMethod = 'Tier',
                Contract__c = contract.Id,
                FIN_Conditional_Logic__c = 'AND',
                FIN_Actual_Count__c = 5
            );
            insert cs;

            ConsumptionRate cr = new ConsumptionRate(
                ConsumptionScheduleId = cs.Id,
                ProcessingOrder = 1,
                LowerBound = 0,
                UpperBound = 10,
                PricingMethod = 'FlatFee',
                Price =0
            );
            insert cr;

            Accumulator_Condition__c ac = new Accumulator_Condition__c(
                FIN_Consumption_Schedule__c = cs.Id,
                FIN_Number__c = 1,
                Object__c = 'FIN_PaymentDistribution__c',
                FIN_Object_Attribute__c = 'FIN_Channel__c',
                Operator__c = '=',
                FIN_Value__c = 'Web'
            );
            insert ac;

            FIN_InvoiceSchedule__c is = TestDataFactory.createInvoiceSchedule(contract.Id);
            Map<Id, List<Id>> idIdMap2 = new Map<Id, List<Id>>();
            idIdMap2.put(contract.Id, new List<Id>{payment.Id});
            String json = JSON.serialize(idIdMap2);
            Integer result2 = InvoiceDataController.createInvoiceItems(json, 'Payments', new FIN_InvoiceSchedule__c(), is.Id);

            FIN_RecalculateAccumulators.FlowInputs flowInputs = new FIN_RecalculateAccumulators.FlowInputs();
            flowInputs.invoiceScheduleId = is.Id;
            flowInputs.contractId = contract.Id;
            List<FIN_RecalculateAccumulators.FlowInputs> listFlowInputs = new List<FIN_RecalculateAccumulators.FlowInputs>();
            listFlowInputs.add(flowInputs);

            Test.startTest();
            FIN_RecalculateAccumulators.getInvoiceSchedule(listFlowInputs);
            Test.stopTest();

            List<FIN_Applied_Accumulators__c> aaList = [
                SELECT Id
                FROM FIN_Applied_Accumulators__c
            ];

//            Assert.areEqual(1, aaList.size());

        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }
}