force-app/main/default/objects/Accumulator_Condition__c/Accumulator_Condition__c.object-meta.xml
<CustomObject>
    <label>Consumption Schedule Condition</label>
    <nameField>
        <displayFormat>CSC-{00000}</displayFormat>
        <label>Consumption Schedule Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumption Schedule Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accumulator_Condition__c/fields/FIN_Consumption_Schedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_Consumption_Schedule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Consumption Schedule</label>
    <referenceTo>ConsumptionSchedule</referenceTo>
    <relationshipName>Accumulator_Conditions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accumulator_Condition__c/fields/FIN_Library_Association__c.field-meta.xml
<CustomField>
    <fullName>FIN_Library_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Either Apply the Conditions or select a Library Association</description>
    <inlineHelpText>Either Apply the Conditions or select a Library Association</inlineHelpText>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Consumption Schedule Conditions</relationshipLabel>
    <relationshipName>Library_Association_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accumulator_Condition__c/fields/FIN_Object_Attribute__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object_Attribute__c</fullName>
    <label>Object Attribute</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Number</fullName>
            </value>
            <value>
                <fullName>Adjustment_Amount__c</fullName>
                <label>Adjustment Amount</label>
            </value>
            <value>
                <fullName>ApprovalStatus__c</fullName>
                <label>Approval Status</label>
            </value>
            <value>
                <fullName>FIN_BaseComp_Total_NoTax__c</fullName>
                <label>BaseComp Total No Tax</label>
            </value>
            <value>
                <fullName>FIN_BaseCompGrandTotal__c</fullName>
                <label>Base Comp Grand Total</label>
            </value>
            <value>
                <fullName>FIN_Channel__c</fullName>
                <label>Channel</label>
            </value>
            <value>
                <fullName>ContractName</fullName>
                <label>Contract Name</label>
            </value>
            <value>
                <fullName>SBQQ__ContractingMethod__c</fullName>
                <label>Contracting Method</label>
            </value>
            <value>
                <fullName>FIN_CurrentPaidAmount__c</fullName>
                <label>Current Paid Amount</label>
            </value>
            <value>
                <fullName>FIN_CustomerID__c</fullName>
                <label>Customer ID</label>
            </value>
            <value>
                <fullName>FIN_Entity_ID__c</fullName>
                <label>Entity ID</label>
            </value>
            <value>
                <fullName>FIN_Entity_Name__c</fullName>
                <label>Entity Name</label>
            </value>
            <value>
                <fullName>FIN_EventZoneGlCode__c</fullName>
                <label>Event Zone GL Code</label>
            </value>
            <value>
                <fullName>FIN_FinancialAdjCount__c</fullName>
                <label>Financial Adj Count</label>
            </value>
            <value>
                <fullName>FIN_GLCode__c</fullName>
                <label>GL Code</label>
            </value>
            <value>
                <fullName>Invoices_Status__c</fullName>
                <label>Invoices Status</label>
            </value>
            <value>
                <fullName>FIN_Journalizing_Status__c</fullName>
                <label>Journalizing Status</label>
            </value>
            <value>
                <fullName>FIN_MOD__c</fullName>
                <label>MOD</label>
            </value>
            <value>
                <fullName>FIN_MODType__c</fullName>
                <label>MOD Type</label>
            </value>
            <value>
                <fullName>FIN_OfferLookup__c</fullName>
                <label>Offer Lookup</label>
            </value>
            <value>
                <fullName>FIN_OfferName__c</fullName>
                <label>Offer Name</label>
            </value>
            <value>
                <fullName>FIN_Offer_Type__c</fullName>
                <label>Offer Type</label>
            </value>
            <value>
                <fullName>FIN_Operator__c</fullName>
                <label>Operator</label>
            </value>
            <value>
                <fullName>FIN_OrderID__c</fullName>
                <label>Order ID</label>
            </value>
            <value>
                <fullName>FIN_Outlet__c</fullName>
                <label>Outlet</label>
            </value>
            <value>
                <fullName>SBQQ__PaymentTerm__c</fullName>
                <label>Payment Term</label>
            </value>
            <value>
                <fullName>PoNumber</fullName>
                <label>PO Number</label>
            </value>
            <value>
                <fullName>SBQQ__PriceCalcStatus__c</fullName>
                <label>Price Calc Status</label>
            </value>
            <value>
                <fullName>SBQQ__PriceCalcStatusMessage__c</fullName>
                <label>Price Calc Status Message</label>
            </value>
            <value>
                <fullName>FIN_PriceCode__c</fullName>
                <label>Price Code</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accumulator_Condition__c/fields/FIN_Value__c.field-meta.xml
<CustomField>
    <fullName>FIN_Value__c</fullName>
    <label>Value</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accumulator_Condition__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Either Apply the Conditions or select a Library Association</inlineHelpText>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FIN_Payment__c</fullName>
                <label>Payment</label>
            </value>
            <value>
                <fullName>FIN_PaymentDistribution__c</fullName>
                <label>Payment Distribution</label>
            </value>
            <value>
                <fullName>FIN_SalesTransactions__c</fullName>
                <label>Sales Transaction</label>
            </value>
            <value>
                <fullName>Contract</fullName>
                <isActive>false</isActive>
                <label>Contract</label>
            </value>
            <value>
                <fullName>Financial Code</fullName>
                <isActive>false</isActive>
                <label>Financial Code</label>
            </value>
            <value>
                <fullName>Library Association</fullName>
                <isActive>false</isActive>
                <label>Library Association</label>
            </value>
            <value>
                <fullName>Order</fullName>
                <isActive>false</isActive>
                <label>Sales</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accumulator_Condition__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&lt;&gt;</fullName>
            </value>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/fields/FIN_ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_ApprovalStatus__c</fullName>
    <description>Captures approvals status of the record</description>
    <inlineHelpText>Captures approvals status of the record</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>In Review</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted for Review</fullName>
    </customValue>
    <customValue>
        <fullName>Reviewed</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted for Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <description>Picklist for setting Approval Status</description>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/helpers/FIN_ConsConditionTriggerHandlerHelper.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
*  Consumption Condition trigger handler helper, used by the FIN_ConsConditionTriggerHandler
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Ivan Liolia
* @modifiedBy     Ivan Liolia
* @version        1.0
* @created        2022-03-31
* @modified       2022-01-31
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* vX.X            Name
* YYYY-MM-DD      Explanation of the change.  Multiple lines can be used to explain the change, but
*                 each line should be indented till left aligned with the previous description text.
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/

public with sharing class FIN_ConsConditionTriggerHandlerHelper {

    /**
     * @method      updateConsumptionScheduleApprovalStatus
     * @description SFCA-449 - If Consumption Condition created, deleted or updated specified fields,
     *              then update Approval Status field to 'New' on parent ConsumptionSchedule record
     * @author      Ivan Liolia - 2023-03-31
     */
    public static void updateConsumptionScheduleApprovalStatus(Map<Id, Accumulator_Condition__c> conditionsToIterate, Map<Id, Accumulator_Condition__c> oldConditions) {
        Set<String> consumptionScheduleIds = new Set<String>();

        // check if oldConditions isn't null, then it comes from update trigger to compare specified values for update
        if (oldConditions != null) {
            for (String Id : conditionsToIterate.keySet()) {
                if (conditionsToIterate.get(Id).Object__c != oldConditions.get(Id).Object__c ||
                        conditionsToIterate.get(Id).FIN_Object_Attribute__c != oldConditions.get(Id).FIN_Object_Attribute__c ||
                        conditionsToIterate.get(Id).Operator__c != oldConditions.get(Id).Operator__c ||
                        conditionsToIterate.get(Id).FIN_Value__c != oldConditions.get(Id).FIN_Value__c ||
                        conditionsToIterate.get(Id).FIN_Library_Association__c != oldConditions.get(Id).FIN_Library_Association__c ||
                        conditionsToIterate.get(Id).FIN_Consumption_Schedule__c != oldConditions.get(Id).FIN_Consumption_Schedule__c) {
                    consumptionScheduleIds.add(conditionsToIterate.get(Id).FIN_Consumption_Schedule__c);
                    consumptionScheduleIds.add(oldConditions.get(Id).FIN_Consumption_Schedule__c);
                }
            }
        }
        // if records come from insert or delete context, then just add ConsumptionScheduleId for subsequent query and update
        else {
            for (String Id : conditionsToIterate.keySet()) {
                consumptionScheduleIds.add(conditionsToIterate.get(Id).FIN_Consumption_Schedule__c);
            }
        }

        // query parent ConsumptionSchedule records with not 'New' status
        List<ConsumptionSchedule> consSchedules =  [SELECT Id
                                                    ,      FIN_ApprovalStatus__c
                                                    FROM   ConsumptionSchedule
                                                    WHERE  Id IN :consumptionScheduleIds
                                                    AND    FIN_ApprovalStatus__c != 'New'];

        // update status for queried parent ConsumptionSchedule records to 'New'
        if (!consSchedules.isEmpty()) {
            for (ConsumptionSchedule consSchedule : consSchedules) {
                consSchedule.FIN_ApprovalStatus__c = 'New';
                consSchedule.IsActive = FALSE;
            }

            update consSchedules;
        }
    }
}