force-app/main/default/objects/Accumulator_Condition__c/Accumulator_Condition__c.object-meta.xml
<CustomObject>
    <label>Consumption Schedule Condition</label>
    <nameField>
        <displayFormat>CSC-{00000}</displayFormat>
        <label>Consumption Schedule Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumption Schedule Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accumulator_Condition__c/fields/FIN_Consumption_Schedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_Consumption_Schedule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Consumption Schedule</label>
    <referenceTo>ConsumptionSchedule</referenceTo>
    <relationshipName>Accumulator_Conditions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accumulator_Condition__c/fields/FIN_Object_Attribute__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object_Attribute__c</fullName>
    <label>Object Attribute</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Number</fullName>
            </value>
            <value>
                <fullName>Adjustment_Amount__c</fullName>
                <label>Adjustment Amount</label>
            </value>
            <value>
                <fullName>ApprovalStatus__c</fullName>
                <label>Approval Status</label>
            </value>
            <value>
                <fullName>FIN_BaseComp_Total_NoTax__c</fullName>
                <label>BaseComp Total No Tax</label>
            </value>
            <value>
                <fullName>FIN_BaseCompGrandTotal__c</fullName>
                <label>Base Comp Grand Total</label>
            </value>
            <value>
                <fullName>FIN_Channel__c</fullName>
                <label>Channel</label>
            </value>
            <value>
                <fullName>ContractName</fullName>
                <label>Contract Name</label>
            </value>
            <value>
                <fullName>SBQQ__ContractingMethod__c</fullName>
                <label>Contracting Method</label>
            </value>
            <value>
                <fullName>FIN_CurrentPaidAmount__c</fullName>
                <label>Current Paid Amount</label>
            </value>
            <value>
                <fullName>FIN_CustomerID__c</fullName>
                <label>Customer ID</label>
            </value>
            <value>
                <fullName>FIN_Entity_ID__c</fullName>
                <label>Entity ID</label>
            </value>
            <value>
                <fullName>FIN_Entity_Name__c</fullName>
                <label>Entity Name</label>
            </value>
            <value>
                <fullName>FIN_EventZoneGlCode__c</fullName>
                <label>Event Zone GL Code</label>
            </value>
            <value>
                <fullName>FIN_FinancialAdjCount__c</fullName>
                <label>Financial Adj Count</label>
            </value>
            <value>
                <fullName>FIN_GLCode__c</fullName>
                <label>GL Code</label>
            </value>
            <value>
                <fullName>Invoices_Status__c</fullName>
                <label>Invoices Status</label>
            </value>
            <value>
                <fullName>FIN_Journalizing_Status__c</fullName>
                <label>Journalizing Status</label>
            </value>
            <value>
                <fullName>FIN_MOD__c</fullName>
                <label>MOD</label>
            </value>
            <value>
                <fullName>FIN_MODType__c</fullName>
                <label>MOD Type</label>
            </value>
            <value>
                <fullName>FIN_OfferLookup__c</fullName>
                <label>Offer Lookup</label>
            </value>
            <value>
                <fullName>FIN_OfferName__c</fullName>
                <label>Offer Name</label>
            </value>
            <value>
                <fullName>FIN_Offer_Type__c</fullName>
                <label>Offer Type</label>
            </value>
            <value>
                <fullName>FIN_Operator__c</fullName>
                <label>Operator</label>
            </value>
            <value>
                <fullName>FIN_OrderID__c</fullName>
                <label>Order ID</label>
            </value>
            <value>
                <fullName>FIN_Outlet__c</fullName>
                <label>Outlet</label>
            </value>
            <value>
                <fullName>SBQQ__PaymentTerm__c</fullName>
                <label>Payment Term</label>
            </value>
            <value>
                <fullName>PoNumber</fullName>
                <label>PO Number</label>
            </value>
            <value>
                <fullName>SBQQ__PriceCalcStatus__c</fullName>
                <label>Price Calc Status</label>
            </value>
            <value>
                <fullName>SBQQ__PriceCalcStatusMessage__c</fullName>
                <label>Price Calc Status Message</label>
            </value>
            <value>
                <fullName>FIN_PriceCode__c</fullName>
                <label>Price Code</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accumulator_Condition__c/fields/FIN_Value__c.field-meta.xml
<CustomField>
    <fullName>FIN_Value__c</fullName>
    <label>Value</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Accumulator_Condition__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <inlineHelpText>Either Apply the Conditions or select a Library Association</inlineHelpText>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FIN_Payment__c</fullName>
                <label>Payment</label>
            </value>
            <value>
                <fullName>FIN_PaymentDistribution__c</fullName>
                <label>Payment Distribution</label>
            </value>
            <value>
                <fullName>FIN_SalesTransactions__c</fullName>
                <label>Sales Transaction</label>
            </value>
            <value>
                <fullName>Contract</fullName>
                <isActive>false</isActive>
                <label>Contract</label>
            </value>
            <value>
                <fullName>Financial Code</fullName>
                <isActive>false</isActive>
                <label>Financial Code</label>
            </value>
            <value>
                <fullName>Library Association</fullName>
                <isActive>false</isActive>
                <label>Library Association</label>
            </value>
            <value>
                <fullName>Order</fullName>
                <isActive>false</isActive>
                <label>Sales</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accumulator_Condition__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&lt;&gt;</fullName>
            </value>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsumptionRate/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/fields/Accumulation_to_Target__c.field-meta.xml
<CustomField>
    <fullName>Accumulation_to_Target__c</fullName>
    <label>Accumulation to Target</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Consumption Schedules</relationshipLabel>
    <relationshipName>Consumption_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/fields/FIN_ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_ApprovalStatus__c</fullName>
    <description>Captures approvals status of the record</description>
    <inlineHelpText>Captures approvals status of the record</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/fields/FIN_DuplicateMessage__c.field-meta.xml
<CustomField>
    <fullName>FIN_DuplicateMessage__c</fullName>
    <label>Duplicate Message</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/fields/FIN_End_Date__c.field-meta.xml
<CustomField>
    <fullName>FIN_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/fields/FIN_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FIN_Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/fields/Recoupment_Balance__c.field-meta.xml
<CustomField>
    <fullName>Recoupment_Balance__c</fullName>
    <description>Recoupment balance for Advance Recoupment accumulation rule</description>
    <inlineHelpText>Recoupment balance for Advance Recoupment accumulation rule</inlineHelpText>
    <label>Recoupment Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ConsumptionSchedule/recordTypes/Accumulation_to_Target.recordType-meta.xml
<RecordType>
    <fullName>Accumulation_to_Target</fullName>
    <active>true</active>
    <description>Accumulation to Target</description>
    <label>Accumulation to Target</label>
</RecordType>

force-app/main/default/objects/ConsumptionSchedule/recordTypes/Advance_Recoupment.recordType-meta.xml
<RecordType>
    <fullName>Advance_Recoupment</fullName>
    <active>true</active>
    <description>Advance Recoupment</description>
    <label>Advance Recoupment</label>
</RecordType>

force-app/main/default/objects/ConsumptionSchedule/recordTypes/Revenue_Amount.recordType-meta.xml
<RecordType>
    <fullName>Revenue_Amount</fullName>
    <active>true</active>
    <description>Revenue Amount</description>
    <label>Revenue Amount</label>
</RecordType>

force-app/main/default/objects/ConsumptionSchedule/recordTypes/Ticket_Quantity.recordType-meta.xml
<RecordType>
    <fullName>Ticket_Quantity</fullName>
    <active>true</active>
    <description>Ticket Quantity</description>
    <label>Ticket Quantity</label>
</RecordType>

force-app/main/default/globalValueSets/ApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>In Review</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted for Review</fullName>
    </customValue>
    <customValue>
        <fullName>Reviewed</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted for Approval</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <description>Picklist for setting Approval Status</description>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/helpers/FIN_ConsumptionScheduleHelper.cls
public with sharing class FIN_ConsumptionScheduleHelper {
    public static void createConsumptionRate(List<ConsumptionSchedule> items, Map<Id, ConsumptionSchedule> oldMap) {
        List<ConsumptionRate> consRatesToAdd = new List<ConsumptionRate>();
        
        System.debug('createConsumptionRate');

        if (items != null) {
            System.debug('items != null');

            List<ConsumptionSchedule> csRT = [
                SELECT Id, Recoupment_Balance__c, Accumulation_to_Target__c, RecordType.DeveloperName
                FROM ConsumptionSchedule
                WHERE Id IN :items
            ];

            for (ConsumptionSchedule cs : csRT) {
                System.debug('csRecordType.DeveloperName ' + cs.RecordType.DeveloperName);
                if (cs.RecordType.DeveloperName == 'Accumulation_to_Target' || cs.RecordType.DeveloperName == 'Advance_Recoupment') {
                    
                    System.debug('create cr');
                    
                    ConsumptionRate cr = new ConsumptionRate();
                    cr.ProcessingOrder = 1;
                    cr.Description = 'autocreated';
                    cr.LowerBound = 0;

                    if (cs.RecordType.DeveloperName == 'Advance_Recoupment' && cs.Recoupment_Balance__c != null) {
                        cr.UpperBound = Math.round(cs.Recoupment_Balance__c);
                    } else if (cs.RecordType.DeveloperName == 'Accumulation_to_Target' && cs.Accumulation_to_Target__c != null) {
                        cr.UpperBound = Math.round(cs.Accumulation_to_Target__c);
                    } else {
                        cr.UpperBound = 10;
                    }
                   
                    cr.Active__c = true;
                    cr.ConsumptionScheduleId = cs.Id;
                    cr.PricingMethod = 'PerUnit';
                    cr.Price = 0;
                    

                    System.debug('cr ---> ' + cr);

                    consRatesToAdd.add(cr);
                }
            }
        } else {
            // List<ConsumptionSchedule> csRT = [
            //     SELECT Id, Recoupment_Balance__c, Accumulation_to_Target__c, RecordType.DeveloperName
            //     FROM ConsumptionSchedule
            //     WHERE Id IN :oldMap.values()
            // ];
            // for (ConsumptionSchedule cs : oldMap.values()) {

            // }
        }

        System.debug('consRatesToAdd ---> ' + consRatesToAdd);

        if (!consRatesToAdd.isEmpty()){
            insert consRatesToAdd;
        }
    }




    // #2 Issue: User should not be able to Approve and Activate following accumulators for the same contract with the same effective dates
        // Ticket Quantity and Revenue Amount/ only one of these two can Approved and Activated
        // Advanced Recoupment and Accumulation To Target/ only one of these two can be Approved and Activated

    // #3: Add validation rule to check for duplicates within accumulation rules for the contract
    // WHEN:
        // User Activate or Approve the accumulation rule
        // User save changes to Active or Approved accumulation rule
    // IF satisfy the below criteria, consider as duplicates:
        // Only Accumulation rules within one contract
        // Only Active and Approved accumulation rules have to be checked
    // If the accumulation rules match by following conditions, consider them as duplicates (AND):
        // Same Accumulation rule type
        // Same Effective Dates
        // Same Conditions, where Object, Object Attribute, Operator and Value are the same -------> ?

    public static void checkForDuplicates(List<ConsumptionSchedule> items, Map<Id, ConsumptionSchedule> oldMap) {
        System.debug('checkForDuplicates');
        
        List<ConsumptionSchedule> triggeredCS = [
            SELECT Id, RecordType.DeveloperName, Contract__c, IsActive, FIN_ApprovalStatus__c, FIN_Start_Date__c, FIN_End_Date__c
                    ,(SELECT Id, FIN_Consumption_Schedule__c, Object__c, FIN_Object_Attribute__c, Operator__c, FIN_Value__c
                    FROM Accumulator_Conditions__r)
            FROM ConsumptionSchedule
            WHERE Id IN :items
        ];
        System.debug('triggeredCS.size() -> ' + triggeredCS.size());

        // if ConsumptionSchedule becomes approved we need to check it
        Map<Id, ConsumptionSchedule> csToCheckMap = new Map<Id, ConsumptionSchedule>();

        for (ConsumptionSchedule trCS : triggeredCS) {
            for (ConsumptionSchedule item : items) {
                if (oldMap?.get(item.Id)?.FIN_ApprovalStatus__c == 'Approved' && item.FIN_ApprovalStatus__c != oldMap?.get(item.Id)?.FIN_ApprovalStatus__c) {
                    item.FIN_DuplicateMessage__c = null;
                } else if (trCS.Id == item.Id && item.FIN_ApprovalStatus__c != oldMap?.get(item.Id)?.FIN_ApprovalStatus__c && item.FIN_ApprovalStatus__c == 'Approved') {
                    csToCheckMap.put(trCS.Id, trCS);
                } 
            }
        }
        System.debug('csToCheckMap.size() -> ' + csToCheckMap.size());

        // get all contract IDs
        Set<Id> contractsIds = new Set<Id>();
        for (ConsumptionSchedule cs : items) {
            contractsIds.add(cs.Contract__c);
        }
        System.debug('contractsIds.size() -> ' + contractsIds.size());

        // get all CSs that were approved & active before this one
        List<ConsumptionSchedule> allActiveCS = [
            SELECT Id, RecordType.DeveloperName, Contract__c, IsActive, FIN_ApprovalStatus__c, FIN_Start_Date__c, FIN_End_Date__c
                    ,(SELECT Id, FIN_Consumption_Schedule__c, Object__c, FIN_Object_Attribute__c, Operator__c, FIN_Value__c
                    FROM Accumulator_Conditions__r)
            FROM ConsumptionSchedule
            WHERE Contract__c IN :contractsIds
            AND IsActive = true
            AND FIN_ApprovalStatus__c = 'Approved'
        ];
        System.debug('allActiveCS.size() -> ' + allActiveCS.size());

        // get all related CS-conditions
        List<Accumulator_Condition__c> allActiveConditions = [
            SELECT Id, FIN_Consumption_Schedule__c, Object__c, FIN_Object_Attribute__c, Operator__c, FIN_Value__c
            FROM Accumulator_Condition__c
            WHERE FIN_Consumption_Schedule__c IN :allActiveCS
            //OR FIN_Consumption_Schedule__c IN :items
        ];
        System.debug('allActiveConditions.size() -> ' + allActiveConditions.size());
        
        //Map<Id, String> csIdMessageMap = new Map<Id, String>();
        Map<Accumulator_Condition__c, Id> conditionCSIdMap = new Map<Accumulator_Condition__c, Id>();
        for (Accumulator_Condition__c ac : allActiveConditions) {
            conditionCSIdMap.put(ac, ac.FIN_Consumption_Schedule__c);
        }

        for (Id cId : contractsIds) {
            
            //check
            for (ConsumptionSchedule item : items) {
                if (csToCheckMap.get(item.Id) != null) {
                    for (ConsumptionSchedule csA : allActiveCS) {
                        System.debug('csToCheckMap.get(item.Id) ' + csToCheckMap.get(item.Id));
                        System.debug('item.Contract__c ' + item.Contract__c);
                        System.debug('csA.Contract__c ' + csA.Contract__c);
                        System.debug('csToCheckMap.get(item.Id).RecordType.DeveloperName ' + csToCheckMap.get(item.Id).RecordType.DeveloperName);
                        System.debug('csA.RecordType.DeveloperName ' + csA.RecordType.DeveloperName);

                        if (csToCheckMap.get(item.Id) != null && item.Contract__c == cId && csA.Contract__c == cId && csToCheckMap.get(item.Id).RecordType.DeveloperName == csA.RecordType.DeveloperName) {
                            System.debug('checkkkkkkkkkkk');

                            if (item.FIN_End_Date__c != null && csA.FIN_End_Date__c != null) {
                                if (item.FIN_Start_Date__c >= csA.FIN_End_Date__c || item.FIN_End_Date__c <= csA.FIN_Start_Date__c) {
                                    System.debug('good dates');
                                    item.FIN_DuplicateMessage__c = null;
                                    //csIdMessageMap.put(item.Id, item.FIN_DuplicateMessage__c);
                                } else if ((item.FIN_Start_Date__c <= csA.FIN_End_Date__c && item.FIN_Start_Date__c >= csA.FIN_Start_Date__c)
                                        || (item.FIN_End_Date__c <= csA.FIN_End_Date__c && item.FIN_End_Date__c >= csA.FIN_Start_Date__c)) {
                                    System.debug('bad dates');
                                    item.FIN_DuplicateMessage__c = 'BAD_DATES';
                                    //csIdMessageMap.put(item.Id, item.FIN_DuplicateMessage__c);
                                }
                            } else if (item.FIN_End_Date__c != null && csA.FIN_End_Date__c == null) {
                                if (item.FIN_End_Date__c <= csA.FIN_Start_Date__c) {
                                    System.debug('good dates');
                                    item.FIN_DuplicateMessage__c = null;
                                    //csIdMessageMap.put(item.Id, item.FIN_DuplicateMessage__c);
                                } else if (item.FIN_Start_Date__c >= csA.FIN_Start_Date__c || item.FIN_End_Date__c >= csA.FIN_Start_Date__c) {
                                    System.debug('bad dates');
                                    item.FIN_DuplicateMessage__c = 'BAD_DATES';
                                    //csIdMessageMap.put(item.Id, item.FIN_DuplicateMessage__c);
                                }
                            } else if (item.FIN_End_Date__c == null && csA.FIN_End_Date__c != null) {
                                if (item.FIN_Start_Date__c >= csA.FIN_End_Date__c) {
                                    System.debug('good dates');
                                    item.FIN_DuplicateMessage__c = null;
                                    //csIdMessageMap.put(item.Id, item.FIN_DuplicateMessage__c);
                                } else if (item.FIN_Start_Date__c <= csA.FIN_Start_Date__c || item.FIN_Start_Date__c <= csA.FIN_End_Date__c) {
                                    System.debug('bad dates');
                                    item.FIN_DuplicateMessage__c = 'BAD_DATES';
                                    //csIdMessageMap.put(item.Id, item.FIN_DuplicateMessage__c);
                                }
                            } else if (item.FIN_End_Date__c == null && csA.FIN_End_Date__c == null) {
                                System.debug('bad dates');
                                item.FIN_DuplicateMessage__c = 'BAD_DATES';
                                //csIdMessageMap.put(item.Id, item.FIN_DuplicateMessage__c);
                            }
                        } else if (csToCheckMap.get(item.Id) != null && item.Contract__c == cId && csA.Contract__c == cId
                            && ((csToCheckMap.get(item.Id).RecordType.DeveloperName == 'Revenue_Amount' && csA.RecordType.DeveloperName == 'Ticket_Quantity')
                            || (csToCheckMap.get(item.Id).RecordType.DeveloperName == 'Ticket_Quantity' && csA.RecordType.DeveloperName == 'Revenue_Amount')
                            || (csToCheckMap.get(item.Id).RecordType.DeveloperName == 'Accumulation_to_Target' && csA.RecordType.DeveloperName == 'Advance_Recoupment')
                            || (csToCheckMap.get(item.Id).RecordType.DeveloperName == 'Advance_Recoupment' && csA.RecordType.DeveloperName == 'Accumulation_to_Target')
                        )) {
                            System.debug('checkkkkkkkkkkk');

                            if (item.FIN_End_Date__c != null && csA.FIN_End_Date__c != null) {
                                if (item.FIN_Start_Date__c >= csA.FIN_End_Date__c || item.FIN_End_Date__c <= csA.FIN_Start_Date__c) {
                                    System.debug('good dates');
                                    item.FIN_DuplicateMessage__c = null;
                                } else if ((item.FIN_Start_Date__c <= csA.FIN_End_Date__c && item.FIN_Start_Date__c >= csA.FIN_Start_Date__c)
                                        || (item.FIN_End_Date__c <= csA.FIN_End_Date__c && item.FIN_End_Date__c >= csA.FIN_Start_Date__c)) {
                                    System.debug('bad dates');
                                    item.FIN_DuplicateMessage__c = 'BAD_TYPE';
                                }
                            } else if (item.FIN_End_Date__c != null && csA.FIN_End_Date__c == null) {
                                if (item.FIN_End_Date__c <= csA.FIN_Start_Date__c) {
                                    System.debug('good dates');
                                    item.FIN_DuplicateMessage__c = null;
                                } else if (item.FIN_Start_Date__c >= csA.FIN_Start_Date__c || item.FIN_End_Date__c >= csA.FIN_Start_Date__c) {
                                    System.debug('bad dates');
                                    item.FIN_DuplicateMessage__c = 'BAD_TYPE';
                                }
                            } else if (item.FIN_End_Date__c == null && csA.FIN_End_Date__c != null) {
                                if (item.FIN_Start_Date__c >= csA.FIN_End_Date__c) {
                                    System.debug('good dates');
                                    item.FIN_DuplicateMessage__c = null;
                                } else if (item.FIN_Start_Date__c <= csA.FIN_Start_Date__c || item.FIN_Start_Date__c <= csA.FIN_End_Date__c) {
                                    System.debug('bad dates');
                                    item.FIN_DuplicateMessage__c = 'BAD_TYPE';
                                }
                            } else if (item.FIN_End_Date__c == null && csA.FIN_End_Date__c == null) {
                                System.debug('bad dates');
                                item.FIN_DuplicateMessage__c = 'BAD_TYPE';
                            }
                        } 
                    }

                    // add check by conditions
                    if (item.FIN_DuplicateMessage__c == 'BAD_DATES') {
                        System.debug('--------------------------> item.FIN_DuplicateMessage__c ' + item.FIN_DuplicateMessage__c);
                        for (ConsumptionSchedule thisCS : triggeredCS) {
                            for (Accumulator_Condition__c ac : allActiveConditions) {
                                for (Accumulator_Condition__c thisAC : thisCS.Accumulator_Conditions__r) {

                                    //System.debug('conditionCSIdMap.get(ac) ' + conditionCSIdMap.get(ac));
                                    System.debug('thisCS.Id ' + thisCS.Id);
                                    System.debug('item.Id ' + item.Id);
                                    System.debug('thisAC.Object__c ' + thisAC.Object__c);
                                    System.debug('ac.Object__c ' + ac.Object__c);
                                    System.debug('thisAC.FIN_Object_Attribute__c ' + thisAC.FIN_Object_Attribute__c);
                                    System.debug('ac.FIN_Object_Attribute__c ' + ac.FIN_Object_Attribute__c);
                                    System.debug('thisAC.Operator__c ' + thisAC.Operator__c);
                                    System.debug('ac.Operator__c ' + ac.Operator__c);
                                    System.debug('thisAC.FIN_Value__c ' + thisAC.FIN_Value__c);
                                    System.debug('ac.FIN_Value__c ' + ac.FIN_Value__c);

                                    if (
                                        //conditionCSIdMap.get(ac) == item.Id &&
                                         thisCS.Id == item.Id
                                        && thisAC.Object__c == ac.Object__c
                                        && thisAC.FIN_Object_Attribute__c == ac.FIN_Object_Attribute__c
                                        && thisAC.Operator__c == ac.Operator__c
                                        && thisAC.FIN_Value__c == ac.FIN_Value__c) {
                                        item.FIN_DuplicateMessage__c = 'BAD_CONDITIONS';
                                    } else {
                                        item.FIN_DuplicateMessage__c = null;
                                    }
                                }
                            }
                        }
                    }
                }

                System.debug('item.FIN_DuplicateMessage__c ' + item.FIN_DuplicateMessage__c);
            }
        }
    }
}