force-app/main/default/objects/Contract/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Auto_Approved__c.field-meta.xml
<CustomField>
    <fullName>FIN_Auto_Approved__c</fullName>
    <description>Fill up Contract, Payment Amount, Sales and Library Association to mark the record Approved</description>
    <formula>IF(
OR( ISBLANK( FIN_Order__c) ,ISBLANK(FIN_LibraryAssociation__c), ISBLANK(FIN_PaymentAmount__c), ISBLANK(Contract__c) ) ,
FALSE,
TRUE)</formula>
    <inlineHelpText>Fill up Contract, Payment Amount, Sales and Library Association to mark the record Approved</inlineHelpText>
    <label>Auto Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Order__c.field-meta.xml
<CustomField>
    <fullName>FIN_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/FIN_RetroactiveAdjustment__c.object-meta.xml
<CustomObject>
    <label>Retroactive Adjustment</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Retroactive Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retroactive Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Account__c.field-meta.xml
<CustomField>
    <fullName>FIN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_AdjustmentAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_AdjustmentAmount__c</fullName>
    <label>Adjustment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Contract__c.field-meta.xml
<CustomField>
    <fullName>FIN_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Order__c.field-meta.xml
<CustomField>
    <fullName>FIN_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_OrderStartDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_OrderStartDate__c</fullName>
    <label>Order Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_ReferencePrice__c.field-meta.xml
<CustomField>
    <fullName>FIN_ReferencePrice__c</fullName>
    <label>Reference Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Total_Sales_Amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_Total_Sales_Amount__c</fullName>
    <label>Total Sales Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Total_Sales_Gross_Amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_Total_Sales_Gross_Amount__c</fullName>
    <label>Total Sales Gross Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Adjustment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Amount__c</fullName>
    <label>Adjustment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Auto_Approved__c.field-meta.xml
<CustomField>
    <fullName>FIN_Auto_Approved__c</fullName>
    <description>This field determines if the record has minimum data elements to be auto approved</description>
    <formula>IF(
OR( Account.Name =&quot;US Unclassified Client&quot; ,ISBLANK(FIN_OrderContext__c), ISBLANK(ContractId), FIN_Total_Sales_Qty__c = 0),
FALSE,
TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Contract, Context and Account must be populated and at least 1 Sale Transaction must be created to make the Sale auto-approved.</inlineHelpText>
    <label>Auto Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_ReferencePrice__c.field-meta.xml
<CustomField>
    <fullName>FIN_ReferencePrice__c</fullName>
    <label>Reference Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_total_sales_amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_total_sales_amount__c</fullName>
    <label>Total Sales amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Total_Sales_Gross_Amoun__c.field-meta.xml
<CustomField>
    <fullName>FIN_Total_Sales_Gross_Amoun__c</fullName>
    <label>Total Sales Gross Amount</label>
    <summarizedField>OrderItem.FIN_TotalGrossAmount__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Total_Sales_Qty__c.field-meta.xml
<CustomField>
    <fullName>FIN_Total_Sales_Qty__c</fullName>
    <label>Total Sales Qty</label>
    <summarizedField>OrderItem.Quantity</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Unclassified_US__c.field-meta.xml
<CustomField>
    <fullName>FIN_Unclassified_US__c</fullName>
    <formula>IF (TEXT(FIN_Region__c) = &apos;US&apos; &amp;&amp; (
				     FIN_ContractRecordType__c = &apos;Master&apos; 
				    ||  TEXT(ApprovalStatus__c) != &apos;Approved&apos; 
				    ||  Contract.Name = null 
				    || Contract.Name = &apos;UNCLASSIFIED&apos;
) , true, false )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>US Unclassified?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/helpers/FIN_OrderHelper.cls
public class FIN_OrderHelper {
    public static void orderSharing(List<Order> orders, Map<Id, Order> oldMap) {
        List<OrderShare> listShareRecords = new List<OrderShare>();
        //        System.debug(orders);
        //        System.debug(oldMap);


        //Bypass this method when CPQ SBAA Approval Status changed
        if (orders[0].ApprovalStatus__c != oldMap?.get(orders[0].Id)?.ApprovalStatus__c) {
            return;
        }

        Group groupUS = [
            SELECT Id
            FROM Group
            WHERE Name = :'US Region'
            LIMIT 1
        ];
        Group groupUK = [
            SELECT Id
            FROM Group
            WHERE Name = :'UK Region'
            LIMIT 1
        ];
        Group groupSWE = [
            SELECT Id
            FROM Group
            WHERE Name = :'SWE Region'
            LIMIT 1
        ];

        for (Order order : orders) {
            if (order.FIN_Region__c != oldMap?.get(order.Id)?.FIN_Region__c) {
                OrderShare newShareRecord = new OrderShare();
                newShareRecord.put('OrderAccessLevel', 'Read');
                newShareRecord.put('OrderId', order.Id);
                newShareRecord.put('RowCause', 'Manual');

                if (order.FIN_Region__c == 'US') {
                    newShareRecord.put('UserOrGroupId', groupUS.Id);
                } else if (order.FIN_Region__c == 'UK') {
                    newShareRecord.put('UserOrGroupId', groupUK.Id);
                } else if (order.FIN_Region__c == 'SWE') {
                    newShareRecord.put('UserOrGroupId', groupSWE.Id);
                }

                if (newShareRecord.UserOrGroupId != null) {
                    listShareRecords.add(newShareRecord);
                }
            }
        }
        if (Trigger.isUpdate && Trigger.isAfter) {
            //            System.debug('ords: ' + orders);
        }
        insert listShareRecords;
    }

    public static void createRetroactiveAdjustment(List<Order> orders, Map<Id, Order> oldMap) {
        List<FIN_RetroactiveAdjustment__c> retroactiveAdjustments = new List<FIN_RetroactiveAdjustment__c>();
        Id orderRecordTypeId = Schema.SObjectType.FIN_RetroactiveAdjustment__c.getRecordTypeInfosByName().get('Order').getRecordTypeId();
        Map<String, String> orderRAMap = new Map<String, String>{
            'AccountId' => 'FIN_Account__c',
            'FIN_Region__c' => 'FIN_Region__c',
            'TotalAmount' => 'FIN_AdjustmentAmount__c',
            'EffectiveDate' => 'FIN_OrderStartDate__c',
            'ContractId' => 'FIN_Contract__c',
            'FIN_Payment__c' => 'FIN_Payment__c',
            'FIN_total_sales_amount__c' => 'FIN_Total_Sales_Amount__c',
            'FIN_Total_Sales_Gross_Amoun__c' => 'FIN_Total_Sales_Gross_Amount__c',
            'Adjustment_Amount__c' => 'FIN_AdjustmentAmount__c',
            'FIN_ReferencePrice__c' => 'FIN_ReferencePrice__c'
        };

        //Bypass this method when CPQ SBAA Approval Status changed
        if (orders[0].ApprovalStatus__c != oldMap?.get(orders[0].Id)?.ApprovalStatus__c) {
            return;
        }

        for (Order order : orders) {
            Order oldO = oldMap.get(order.Id);
            Integer i = 0;

            FIN_RetroactiveAdjustment__c newRetroactiveAdjustment = new FIN_RetroactiveAdjustment__c();
            newRetroactiveAdjustment.FIN_Order__c = order.Id;
            newRetroactiveAdjustment.FIN_Account__c = order.AccountId;
            newRetroactiveAdjustment.FIN_Contract__c = order.ContractId;
            newRetroactiveAdjustment.FIN_Payment__c = order.FIN_Payment__c;
            newRetroactiveAdjustment.RecordTypeId = orderRecordTypeId;

            for (String str : orderRAMap.keyset()) {
                if (order.get(str) != oldO.get(str)) {
                    newRetroactiveAdjustment.put(orderRAMap.get(str), order.get(str));
                    i++;
                }
            }

            if (i != 0) {
                retroactiveAdjustments.add(newRetroactiveAdjustment);
            }
        }
        System.debug('orders in trigger: ' + orders.size());
        insert retroactiveAdjustments;
    }

//    public static void updateOwnerOnClassifiedRecord(List<Order> sales) {
//        for (Order sale : sales) {
//            if (!String.isBlank(sale.Owner.Name)) {
//                if (sale.Owner.Name.contains('Unclassified') && !sale.FIN_Unclassified_US__c) {
//                    sale.OwnerId = UserInfo.getUserId();
//                }
//            }
//        }
//    }

    public static void updateApprovalStatus(List<Order> sales, Map<Id, Order> oldMap) {
        for (Order order : sales) {
            System.debug('order.FIN_Auto_Approved__c'+order.FIN_Auto_Approved__c);
            System.debug('order.ApprovalStatus__c'+order.ApprovalStatus__c);
            if (!order.FIN_Auto_Approved__c && order.ApprovalStatus__c == 'Approved' && order.FIN_Total_Sales_Qty__c > 0) {
                if (order.ApprovalStatus__c != oldMap.get(order.Id).ApprovalStatus__c) {
                    order.addError('Please populate the fields required for Approval: Contract, Context, and add Sales Transactions');
                } else {
                    order.ApprovalStatus__c = 'New';
                    order.Status = 'New';
                }
            } else if (order.FIN_Auto_Approved__c && order.ApprovalStatus__c == oldMap.get(order.Id).ApprovalStatus__c && order.ApprovalStatus__c == 'New' && order.FIN_Total_Sales_Qty__c > 0) {
                order.Status = 'Approved';
                order.ApprovalStatus__c = 'Approved';
            }
        }
    }
}