force-app/main/default/objects/Contract/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_ParentContract__c.field-meta.xml
<CustomField>
    <fullName>FIN_ParentContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contract.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Master</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>SubContracts</relationshipLabel>
    <relationshipName>SubContracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/ContractAssociation__c.object-meta.xml
<CustomObject>
    <label>Contract Association</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Contract Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractAssociation__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/helpers/FIN_ContractHelper.cls
public with sharing class FIN_ContractHelper {
    public static void processDeactivatedContracts(List<Contract> contracts) {
        Set<Id> contractIds = new Set<Id>();
        List<Contract> subContractsToUpdate = new List<Contract>();
        List<ContractAssociation__c> contractAssociationsToUpdate = new List<ContractAssociation__c>();
        for (Contract contract : contracts) {
            if (contract.Status == 'Deactivated') {
                contractIds.add(contract.Id);
            }
        }
        if (!contractIds.isEmpty()) {
            List<Contract> contractsDataWithLookups = FIN_ContractSelector.getContractByIds(contractIds);
            contractIds.clear();
            for (Contract contract : contractsDataWithLookups) {
                if (!contract.SubContracts__r.isEmpty()) {
                    for (Contract subContract : contract.SubContracts__r) {
                        contractIds.add(subContract.Id);
                        subContract.Status = 'Deactivated';
                        subContractsToUpdate.add(subContract);
                    }
                }
                contractIds.add(contract.Id);
            }
            List<ContractAssociation__c> contractAssociations = FIN_ContractAssociationSelector.getNotDeactivatedContractAssociationsByContractIds(contractIds);
            for (ContractAssociation__c contractAssociation : contractAssociations) {
                contractAssociation.ApprovalStatus__c = 'Deactivated';
                contractAssociationsToUpdate.add(contractAssociation);
            }
            update contractAssociationsToUpdate;
            update subContractsToUpdate;
        }
    }

    public static void processActivatedContractsCAs(Map<Id, Contract> oldMap, List<Contract> newContractsList) {
        Set<Id> contractIds = new Set<Id>();
        for (Contract ctrct : newContractsList) {
            if (oldMap.get(ctrct.Id).Status == 'Deactivated' && ctrct.Status != 'Deactivated') {
                contractIds.add(ctrct.Id);
            }
        }
        List<ContractAssociation__c> contractAssociations = FIN_ContractAssociationSelector.getDeactivatedContractAssociationsByContractIds(contractIds);
        for (ContractAssociation__c ca : contractAssociations) {
            ca.ApprovalStatus__c = 'New';
        }
        update contractAssociations;
    }
}