force-app/main/default/objects/Contract/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_ParentContract__c.field-meta.xml
<CustomField>
    <fullName>FIN_ParentContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contract.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Master</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>SubContracts</relationshipLabel>
    <relationshipName>SubContracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceItem__c/FIN_InvoiceItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>II-{0000000000}</displayFormat>
        <label>Invoice Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_InvoiceItem__c/fields/FIN_Contract__c.field-meta.xml
<CustomField>
    <fullName>FIN_Contract__c</fullName>
    <formula>FIN_ParentInvoiceSchedule__r.FIN_Contract__r.ContractNumber</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceItem__c/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceSchedule__c/FIN_InvoiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Invoice Schedule</label>
    <nameField>
        <displayFormat>IS-{0000000000}</displayFormat>
        <label>Invoice Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_InvoiceSchedule__c/fields/FIN_Contract__c.field-meta.xml
<CustomField>
    <fullName>FIN_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Invoice Schedules</relationshipLabel>
    <relationshipName>Invoice_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_InvoiceSchedule__c/fields/FIN_Mode__c.field-meta.xml
<CustomField>
    <fullName>FIN_Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ByAmount</fullName>
                <default>true</default>
                <label>By Amount</label>
            </value>
            <value>
                <fullName>ByTicketQuantity</fullName>
                <label>By Ticket Quantity</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_InvoiceSchedule__c/fields/FIN_Type__c.field-meta.xml
<CustomField>
    <fullName>FIN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDs</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>SalesTransactions</fullName>
                <label>Sales Transactions</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Invoices_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Invoices_Status__c</fullName>
    <label>Invoices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Invoices_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <formula>FIN_PaymentAmount__c * FIN_JournalEntrySign__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Journalizing_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Journalizing_Status__c</fullName>
    <label>Journalizing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Journalizing_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Order__c.field-meta.xml
<CustomField>
    <fullName>FIN_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_PaymentAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentAmount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Event__c.field-meta.xml
<CustomField>
    <fullName>FIN_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <formula>FIN_DistributionAmount__c  * FIN_JournalEntrySign__c</formula>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/Invoices_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoices_Status__c</fullName>
    <label>Invoices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Invoices_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Event__c.field-meta.xml
<CustomField>
    <fullName>FIN_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Journalizing_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Journalizing_Status__c</fullName>
    <label>Journalizing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Journalizing_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_OrderContext__c.field-meta.xml
<CustomField>
    <fullName>FIN_OrderContext__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_ZoneDesc__c.field-meta.xml
<CustomField>
    <fullName>FIN_ZoneDesc__c</fullName>
    <label>Zone Desc</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admissions</fullName>
            </value>
            <value>
                <fullName>Table / Booth Upsell</fullName>
            </value>
            <value>
                <fullName>Comps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Invoices_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoices_Status__c</fullName>
    <label>Invoices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Invoices_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_Event__c.field-meta.xml
<CustomField>
    <fullName>FIN_Event__c</fullName>
    <formula>FIN_EventLookup__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_Invoices_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Invoices_Status__c</fullName>
    <label>Invoices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Invoices_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_Journalizing_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Journalizing_Status__c</fullName>
    <label>Journalizing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Journalizing_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_TotalNetAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_TotalNetAmount__c</fullName>
    <formula>IF(FIN_Amount__c &lt;&gt; 0, FIN_Amount__c,
IF(FIN_FeeNetAmount__c &lt;&gt; 0, FIN_FeeNetAmount__c,
IF(FIN_MerchNetAmount__c &lt;&gt; 0, FIN_MerchNetAmount__c, 0)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/FIN_Invoices_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>ToBeInvoiced</fullName>
        <label>To Be Invoiced</label>
    </customValue>
    <customValue>
        <fullName>InvoiceScheduled</fullName>
        <label>Invoice in Progress</label>
    </customValue>
    <customValue>
        <fullName>Invoiced</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FIN_Journalizing_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ToBePosted</fullName>
        <label>To be Posted</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>Exported</fullName>
    </customValue>
    <customValue>
        <fullName>Posted</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <customValue>
        <fullName>PartiallyPosted</fullName>
        <isActive>false</isActive>
        <label>Partially Posted</label>
    </customValue>
    <masterLabel>Journalizing Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/controllers/InvoiceDataController.cls
public with sharing class InvoiceDataController {
    static final String PDS_CONST = 'PDs';
    static final String PAYMENTS_CONST = 'Payments';

    @AuraEnabled(cacheable=true)
    public static List<Contract> getFilteredSubContractsWithPayments(String objectName, String contractId, String sale, String event, String zone, String context, String region) {
        String query = 'SELECT Id, Name, ContractNumber, (SELECT Id, FIN_PaymentAmount__c, FIN_JournalEntryAmount__c ' +
            'FROM Payments__r ';

        if (objectName == 'invoice') {
            query += ' WHERE ((FIN_Invoices_Status__c = \'ToBeInvoiced\' OR FIN_Invoices_Status__c = \'Voided\') AND FIN_Order__r.ApprovalStatus__c = \'Approved\') ';
        } else if (objectName == 'journalizing') {
            query += ' WHERE FIN_Journalizing_Status__c = \'ToBePosted\' AND FIN_Order__r.ApprovalStatus__c = \'Approved\' ';

            if (contractId != null && contractId != '') {
                query += ' AND Contract__c = :contractId ';
            }
        }

        if (sale != '') {
            query += ' AND FIN_Order__c = :sale';
        }
        if (event != '') {
            query += ' AND FIN_Order__r.FIN_Event__c = :event';
        }
        if (zone != '') {
            query += ' AND FIN_Order__r.FIN_ZoneDesc__c = :zone';
        }
        if (context != '') {
            query += ' AND FIN_Order__r.FIN_OrderContext__c = :context';
        }
        if (region != '') {
            query += ' AND FIN_Region__c = :region';
        }

        if (objectName == 'journalizing') {
            query += ') FROM Contract WHERE FIN_ParentContract__c != NULL';
        } else {
            query += ') FROM Contract WHERE FIN_ParentContract__c = :contractId OR (FIN_ParentContract__c != NULL AND Id = :contractId)';
        }

        List<Contract> filteredSubContracts = new List<Contract>();
        filteredSubContracts = Database.query(query);

        List<Contract> processedSubContracts = new List<Contract>();

        for (Contract contract : filteredSubContracts) {
            if (contract.Payments__r.size() > 0) {
                processedSubContracts.add(contract);
            }
        }
        System.debug('processedSubContracts' + processedSubContracts);

        return processedSubContracts;
    }

    @AuraEnabled(cacheable=true)
    public static List<Contract> getFilteredSubContractsWithSalesTransactions(String contractId, String sale, String event, String zone) {
        String query = 'SELECT Id, Name, ContractNumber, (SELECT Id, FIN_TotalNetAmount__c, Quantity ' +
            'FROM SBQQ__OrderProducts__r ' +
            'WHERE FIN_Invoices_Status__c = \'ToBeInvoiced\' ' +
            'AND Order.ApprovalStatus__c = \'Approved\' ';

        if (sale != '') {
            query += ' AND OrderId = :sale';
        }
        if (event != '') {
            query += ' AND Order.FIN_Event__c = :event';
        }
        if (zone != '') {
            query += ' AND Order.FIN_ZoneDesc__c = :zone';
        }
        query += ') FROM Contract WHERE FIN_ParentContract__c = :contractId OR (FIN_ParentContract__c != NULL AND Id = :contractId)';

        List<Contract> filteredSubContracts = new List<Contract>();
        filteredSubContracts = Database.query(query);

        List<Contract> processedSubContracts = new List<Contract>();

        for (Contract contract : filteredSubContracts) {
            if (contract.SBQQ__OrderProducts__r.size() > 0) {
                processedSubContracts.add(contract);
            }
        }

        return processedSubContracts;
    }

    @AuraEnabled(cacheable=false)
    public static Integer createInvoiceItems(String jsonString, String type, FIN_InvoiceSchedule__c invoiceSh, Id currentInvoiceSh) {
        try {
            Map<Id, List<Id>> selectedRecords = (Map<Id, List<Id>>) JSON.deserialize(jsonString, Map<Id, List<Id>>.class);
            Map<Id, FIN_InvoiceSchedule__c> invoiceSchedules = new Map<Id, FIN_InvoiceSchedule__c>();
            List<FIN_InvoiceItem__c> invoiceItems = new List<FIN_InvoiceItem__c>();

            List<Id> selectedChild = new List<Id>();

            if (currentInvoiceSh == null) {
                for (Id selectedRecord : selectedRecords.keySet()) {
                    FIN_InvoiceSchedule__c invoiceSchedule = invoiceSh.clone(false);
                    invoiceSchedule.FIN_Contract__c = selectedRecord;
                    invoiceSchedule.FIN_Type__c = type;
                    invoiceSchedule.FIN_Mode__c = 'ByAmount';

                    invoiceSchedules.put(selectedRecord, invoiceSchedule);
                    selectedChild.addAll(selectedRecords.get(selectedRecord));
                }

                insert invoiceSchedules.values();
            } else {
                for (Id selectedRecord : selectedRecords.keySet()) {
                    selectedChild.addAll(selectedRecords.get(selectedRecord));
                }
            }

            Id invoiceId = null;
            if (type == PDS_CONST) {
                List<FIN_PaymentDistribution__c> listPD = [
                    SELECT Id, Contract__c, FIN_LibraryAssociation__c, Invoices_Status__c, FIN_DistributionAmount__c
                    FROM FIN_PaymentDistribution__c
                    WHERE Id IN :selectedChild
                ];

                for (FIN_PaymentDistribution__c pd : listPD) {
                    if (currentInvoiceSh != null) {
                        invoiceId = currentInvoiceSh;
                    } else {
                        invoiceId = invoiceSchedules.get(pd.Contract__c).Id;
                    }

                    invoiceItems.add(new FIN_InvoiceItem__c(
                        FIN_SubContract__c = pd.Contract__c,
                        FIN_PaymentDistribution__c = pd.Id,
                        FIN_ParentInvoiceSchedule__c = invoiceId,
                        FIN_LibraryAssociation__c = pd.FIN_LibraryAssociation__c,
                        RecordTypeId = getRecordTypeIdByObjName(type),
                        FIN_EntryType__c = 'StandardEntry',
                        FIN_TotalNetAmountforInvoice__c = pd.FIN_DistributionAmount__c
                    ));
                }
            } else if (type == PAYMENTS_CONST) {
                List<FIN_Payment__c> listPayments = [
                    SELECT Id, Contract__c, FIN_Invoices_Status__c, FIN_PaymentAmount__c, FIN_LibraryAssociation__c
                    FROM FIN_Payment__c
                    WHERE Id IN :selectedChild
                ];

                for (FIN_Payment__c payment : listPayments) {
                    if (currentInvoiceSh != null) {
                        invoiceId = currentInvoiceSh;
                    } else {
                        invoiceId = invoiceSchedules.get(payment.Contract__c).Id;
                    }

                    invoiceItems.add(new FIN_InvoiceItem__c(
                        FIN_SubContract__c = payment.Contract__c,
                        FIN_Payment__c = payment.Id,
                        FIN_ParentInvoiceSchedule__c = invoiceId,
                        RecordTypeId = getRecordTypeIdByObjName(type),
                        FIN_LibraryAssociation__c = payment.FIN_LibraryAssociation__c,
                        FIN_EntryType__c = 'StandardEntry',
                        FIN_TotalNetAmountforInvoice__c = payment.FIN_PaymentAmount__c
                    ));
                }
            } else if (type == 'SalesTransactions') {
                List<OrderItem> listSalesTr = [
                    SELECT Id, SBQQ__Contract__c, FIN_LibraryAssociation__c, FIN_TotalNetAmount__c, Quantity
                    FROM OrderItem
                    WHERE Id IN :selectedChild
                ];

                for (OrderItem salesTr : listSalesTr) {
                    if (currentInvoiceSh != null) {
                        invoiceId = currentInvoiceSh;
                    } else {
                        invoiceId = invoiceSchedules.get(salesTr.SBQQ__Contract__c).Id;
                    }

                    invoiceItems.add(new FIN_InvoiceItem__c(
                        FIN_SubContract__c = salesTr.SBQQ__Contract__c,
                        FIN_SalesTransactions__c = salesTr.Id,
                        FIN_ParentInvoiceSchedule__c = invoiceId,
                        RecordTypeId = getRecordTypeIdByObjName(type),
                        FIN_LibraryAssociation__c = salesTr.FIN_LibraryAssociation__c,
                        FIN_EntryType__c = 'StandardEntry',
                        FIN_QuantityforInvoiceQty__c = salesTr.Quantity,
                        FIN_TotalNetAmountforInvoice__c = salesTr.FIN_TotalNetAmount__c
                    ));
                }
            }
            System.debug('invoiceItems'+invoiceItems);

            insert invoiceItems;
            return invoiceItems.size();
        } catch (Exception e) {
            return 0;
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Contract> getRelatedRecords(String invoiceSh) {
        List<FIN_InvoiceItem__c> listII = [
            SELECT Id, FIN_PaymentDistribution__r.Contract__c, FIN_Payment__r.Contract__c, FIN_SalesTransactions__r.SBQQ__Contract__c, FIN_ParentInvoiceSchedule__r.FIN_Type__c
            FROM FIN_InvoiceItem__c
            WHERE FIN_ParentInvoiceSchedule__c = :invoiceSh
        ];
        Set<String> setContractId = new Set<String>();
        Set<String> setPDsId = new Set<String>();
        Set<String> setPaymentsId = new Set<String>();
        Set<String> setSTsId = new Set<String>();

        String type;

        if (listII.size() > 0) {
            type = listII[0]?.FIN_ParentInvoiceSchedule__r?.FIN_Type__c;
        }

        if (type == PDS_CONST) {
            for (FIN_InvoiceItem__c item : listII) {
                setContractId.add(item.FIN_PaymentDistribution__r.Contract__c);
                setPDsId.add(item.FIN_PaymentDistribution__c);
            }
        } else if (type == PAYMENTS_CONST) {
            for (FIN_InvoiceItem__c item : listII) {
                setContractId.add(item.FIN_Payment__r.Contract__c);
                setPaymentsId.add(item.FIN_Payment__c);
            }
        } else if (type == 'SalesTransactions') {
            for (FIN_InvoiceItem__c item : listII) {
                setContractId.add(item.FIN_SalesTransactions__r.SBQQ__Contract__c);
                setSTsId.add(item.FIN_SalesTransactions__c);
            }
        }

        if (!setContractId.isEmpty()) {
            if (type == PDS_CONST) {
                return [
                    SELECT Id, Name, ContractNumber, (
                        SELECT Id, FIN_DistributionAmount__c, FIN_JournalEntryAmount__c
                        FROM Payment_Distributions__r
                        WHERE Id IN:setPDsId
                    )
                    FROM Contract
                    WHERE Id IN :setContractId
                ];
            } else if (type == PAYMENTS_CONST) {
                return [
                    SELECT Id, Name, ContractNumber, (
                        SELECT Id, FIN_PaymentAmount__c, FIN_JournalEntryAmount__c
                        FROM Payments__r
                        WHERE Id IN:setPaymentsId
                    )
                    FROM Contract
                    WHERE Id IN :setContractId
                ];
            } else if (type == 'SalesTransactions') {
                return [
                    SELECT Id, Name, ContractNumber, (
                        SELECT Id, FIN_TotalNetAmount__c, Quantity
                        FROM SBQQ__OrderProducts__r
                        WHERE Id IN:setSTsId
                    )
                    FROM Contract
                    WHERE Id IN :setContractId
                ];
            } else {
                return new List<Contract>();
            }
        } else {
            return new List<Contract>();
        }
    }

    @AuraEnabled(cacheable=false)
    public static Integer removeRelatedIIs(List<Id> listSubContracts, String invoiceSh) {
        List<FIN_InvoiceItem__c> listII = [
            SELECT Id
            FROM FIN_InvoiceItem__c
            WHERE (FIN_PaymentDistribution__r.Contract__c IN :listSubContracts
            OR FIN_Payment__r.Contract__c IN :listSubContracts
            OR FIN_SalesTransactions__r.SBQQ__Contract__c IN :listSubContracts)
            AND FIN_ParentInvoiceSchedule__c = :invoiceSh
        ];

        delete listII;
        return listII.size();
    }

    public static Id getRecordTypeIdByObjName(String type) {
        Map<String, Schema.RecordTypeInfo> rts = Schema.SObjectType.FIN_InvoiceItem__c.getRecordTypeInfosByDeveloperName();

        for (String rt : rts.keySet()) {
            if (rt.contains(type)) {
                return rts.get(rt).RecordTypeId;
            }
        }

        return null;
    }
}