force-app/main/default/objects/Contract/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_ParentContract__c.field-meta.xml
<CustomField>
    <fullName>FIN_ParentContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contract.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Master</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>SubContracts</relationshipLabel>
    <relationshipName>SubContracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Context__c/FIN_Context__c.object-meta.xml
<CustomObject>
    <label>Context</label>
    <nameField>
        <label>Context Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contexts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Context__c/fields/FIN_Active__c.field-meta.xml
<CustomField>
    <fullName>FIN_Active__c</fullName>
    <formula>TODAY() &gt; FIN_StartDate__c
&amp;&amp;
TODAY() &lt; FIN_EndDate__c ||
ISNULL(FIN_EndDate__c)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_ContextID__c.field-meta.xml
<CustomField>
    <fullName>FIN_ContextID__c</fullName>
    <description>Formula (Context ID field)</description>
    <formula>FIN_ContextName__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Context ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_ContextName__c.field-meta.xml
<CustomField>
    <fullName>FIN_ContextName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context Name</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <formula>FIN_PaymentAmount__c * FIN_JournalEntrySign__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Journalizing_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Journalizing_Status__c</fullName>
    <label>Journalizing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Journalizing_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Order__c.field-meta.xml
<CustomField>
    <fullName>FIN_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Settlement_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_ContextID__c.field-meta.xml
<CustomField>
    <fullName>FIN_ContextID__c</fullName>
    <description>Formula(Context ID field)</description>
    <formula>FIN_ContextName__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Context ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_ContextName__c.field-meta.xml
<CustomField>
    <fullName>FIN_ContextName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context Name</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_DistributionAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmount__c</fullName>
    <label>Distribution Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_DistributionDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionDate__c</fullName>
    <label>Distribution Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Event__c.field-meta.xml
<CustomField>
    <fullName>FIN_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <formula>FIN_DistributionAmount__c  * FIN_JournalEntrySign__c</formula>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Order_ID__c.field-meta.xml
<CustomField>
    <fullName>FIN_Order_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order ID</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/Invoices_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoices_Status__c</fullName>
    <label>Invoices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Invoices_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/FIN_SettlementItem__c.object-meta.xml
<CustomObject>
    <label>Settlement Item</label>
    <nameField>
        <displayFormat>SI-{0000000000}</displayFormat>
        <label>Settlement Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_ContextID__c.field-meta.xml
<CustomField>
    <fullName>FIN_ContextID__c</fullName>
    <description>Formula (Context ID field lookup)</description>
    <formula>FIN_OrderContext__r.Context_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Context ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Event__c.field-meta.xml
<CustomField>
    <fullName>FIN_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Journalizing_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Journalizing_Status__c</fullName>
    <label>Journalizing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Journalizing_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_OrderContext__c.field-meta.xml
<CustomField>
    <fullName>FIN_OrderContext__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_ZoneDesc__c.field-meta.xml
<CustomField>
    <fullName>FIN_ZoneDesc__c</fullName>
    <label>Zone Desc</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admissions</fullName>
            </value>
            <value>
                <fullName>Table / Booth Upsell</fullName>
            </value>
            <value>
                <fullName>Comps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Invoices_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoices_Status__c</fullName>
    <label>Invoices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Invoices_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FIN_Invoices_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>ToBeInvoiced</fullName>
        <label>To Be Invoiced</label>
    </customValue>
    <customValue>
        <fullName>InvoiceScheduled</fullName>
        <label>Invoice in Progress</label>
    </customValue>
    <customValue>
        <fullName>Invoiced</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FIN_Journalizing_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ToBePosted</fullName>
        <label>To be Posted</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>Exported</fullName>
    </customValue>
    <customValue>
        <fullName>Posted</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <customValue>
        <fullName>PartiallyPosted</fullName>
        <isActive>false</isActive>
        <label>Partially Posted</label>
    </customValue>
    <masterLabel>Journalizing Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FIN_Settlement_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>ToBeSettled</fullName>
        <label>To Be Settled</label>
    </customValue>
    <customValue>
        <fullName>Settled</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>ScheduledSettlement</fullName>
        <label>Scheduled for Settlement</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <masterLabel>Settlement Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/controllers/SettleDataController.cls
public with sharing class SettleDataController {
    static final String PDS_CONST = 'PDs';
    static final String PAYMENTS_CONST = 'Payments';

    @AuraEnabled(cacheable=true)
    public static List<Contract> getFilteredSubContractsWithPDs(String objectName, String contractId,
        Date eventDateFrom, Date eventDateTo, String sale, String event,
        Date transactionDateFrom, Date transactionDateTo, String zone, String context, String region) {

        String query = 'SELECT Id, Name, ContractNumber, (SELECT Id, FIN_DistributionAmount__c, FIN_JournalEntryAmount__c ' +
            'FROM Payment_Distributions__r ';

        if (objectName == 'settlement') {
            query += ' WHERE ((FIN_Settlement_Status__c = \'ToBeSettled\' OR FIN_Settlement_Status__c = \'Voided\') AND FIN_Payment__r.FIN_Order__r.ApprovalStatus__c = \'Approved\') ';
        } else if (objectName == 'invoice') {
            query += ' WHERE ((Invoices_Status__c = \'ToBeInvoiced\' OR Invoices_Status__c = \'Voided\') AND FIN_Payment__r.FIN_Order__r.ApprovalStatus__c = \'Approved\') ';
        } else if (objectName == 'journalizing') {
            query += ' WHERE FIN_Journalizing_Status__c = \'ToBePosted\' AND FIN_Payment__r.FIN_Order__r.ApprovalStatus__c = \'Approved\' ';

            if (contractId != null && contractId != '') {
                query += ' AND Contract__c = :contractId';
            }
        }

        if (context != '') {
            query += ' AND FIN_ContextID__c = :context';
        }
        if (region != '') {
            query += ' AND FIN_Region__c = :region';
        }

        if (eventDateFrom != null) {
            query += ' AND FIN_Event__r.StartDate >= :eventDateFrom';
        }
        if (eventDateTo != null) {
            query += ' AND FIN_Event__r.EndDate <= :eventDateTo';
        }
        if (transactionDateFrom != null) {
            query += ' AND FIN_DistributionDate__c >= :transactionDateFrom';
        }
        if (transactionDateTo != null) {
            query += ' AND FIN_DistributionDate__c <= :transactionDateTo';
        }
        if (sale != '') {
            query += ' AND FIN_Payment__r.FIN_Order__c = :sale';
        }
        if (event != '') {
            query += ' AND FIN_Event__c = :event';
        }
        if (zone != '') {
            query += ' AND FIN_Payment__r.FIN_Order__r.FIN_ZoneDesc__c = :zone';
        }

        if (objectName == 'journalizing') {
            query += ') FROM Contract WHERE FIN_ParentContract__c != NULL';
        } else {
            query += ') FROM Contract WHERE FIN_ParentContract__c = :contractId';
        }

        List<Contract> filteredSubContracts = new List<Contract>();
        filteredSubContracts = Database.query(query);

        List<Contract> processedSubContracts = new List<Contract>();

        for (Contract contract : filteredSubContracts) {
            if (contract.Payment_Distributions__r.size() > 0) {
                processedSubContracts.add(contract);
            }
        }
        System.debug('processedSubContracts'+processedSubContracts);

        return processedSubContracts;
    }

    @AuraEnabled(cacheable=true)
    public static List<Order> getSales(String contractId) {
        if(contractId != null) {
            return [
                SELECT Id, OrderNumber, Status
                FROM Order
                WHERE (Contract.FIN_ParentContract__c = :contractId
                OR ContractId = :contractId)
                AND ApprovalStatus__c = :'Approved'
                ORDER BY OrderNumber
                //WITH SECURITY_ENFORCED
            ];
        } else {
            return [
                SELECT Id, OrderNumber, Status
                FROM Order
                WHERE ApprovalStatus__c = :'Approved'
                ORDER BY OrderNumber
                //WITH SECURITY_ENFORCED
            ];
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Order> getZones(String contractId) {
        if(contractId != null) {
            return [
                SELECT Id, FIN_ZoneDesc__c, Status
                FROM Order
                WHERE (Contract.FIN_ParentContract__c = :contractId
                OR ContractId = :contractId)
                AND ApprovalStatus__c = :'Approved'
                ORDER BY FIN_ZoneDesc__c
                //WITH SECURITY_ENFORCED
            ];
        } else {
            return [
                SELECT Id, FIN_ZoneDesc__c, Status
                FROM Order
                WHERE ApprovalStatus__c = :'Approved'
                ORDER BY FIN_ZoneDesc__c
                //WITH SECURITY_ENFORCED
            ];
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Campaign> getEvents(String objectName, String contractId) {
        String query = 'SELECT FIN_Event__c ' +
            'FROM FIN_PaymentDistribution__c ';

        if(contractId != null && contractId != '') {
            query += ' WHERE Contract__c = :contractId';
        }

        if (objectName == 'settlement') {
            query += ' AND ((FIN_Settlement_Status__c = \'ToBeSettled\' OR FIN_Settlement_Status__c = \'Voided\') AND FIN_Payment__r.FIN_Order__r.ApprovalStatus__c = \'Approved\') ';
        } else if (objectName == 'invoice') {
            query += ' AND ((Invoices_Status__c = \'ToBeInvoiced\' OR Invoices_Status__c = \'Voided\') AND FIN_Payment__r.FIN_Order__r.ApprovalStatus__c = \'Approved\') ';
        } else if (objectName == 'journalizing') {
            query += ' WHERE FIN_Journalizing_Status__c = \'ToBePosted\' AND FIN_Payment__r.FIN_Order__r.ApprovalStatus__c = \'Approved\' ';
        }

        List<FIN_PaymentDistribution__c> eventsFromPdList = new List<FIN_PaymentDistribution__c>();
        eventsFromPdList = Database.query(query);

        List<Campaign> allCampaigns = [
            SELECT Id, Name
            FROM Campaign
            ORDER BY Name
        ];

        List<Campaign> relatedEvents = new List<Campaign>();

        for (Campaign event : allCampaigns) {
            for (FIN_PaymentDistribution__c eventPD : eventsFromPdList) {
                if (event.Id == eventPD.FIN_Event__c && !relatedEvents.contains(event)) {
                    relatedEvents.add(event);
                }
            }
        }

        return relatedEvents;
    }

    @AuraEnabled(cacheable=true)
    public static List<FIN_Context__c> getContexts(String type, String region) {
        Set<Id> contextIds = new Set<Id>();

        if (type == PDS_CONST) {
            List<FIN_PaymentDistribution__c> listPDs = [
                SELECT Id, FIN_ContextName__c, FIN_ContextName__r.FIN_Active__c
                FROM FIN_PaymentDistribution__c
                WHERE FIN_ContextName__r.FIN_Active__c = TRUE
                AND FIN_Region__c =: region
            ];

            for(FIN_PaymentDistribution__c pd : listPDs) {
                if(!contextIds.contains(pd.FIN_ContextName__c)) {
                    contextIds.add(pd.FIN_ContextName__c);
                }
            }

        } else if (type == PAYMENTS_CONST) {
            List<FIN_Payment__c> listPayments = [
                SELECT Id, FIN_Order__r.FIN_OrderContext__c, FIN_Order__r.FIN_OrderContext__r.FIN_Active__c
                FROM FIN_Payment__c
                WHERE FIN_Order__r.FIN_OrderContext__r.FIN_Active__c = TRUE
                AND FIN_Region__c =: region
            ];

            for(FIN_Payment__c payment : listPayments) {
                if(!contextIds.contains(payment.FIN_Order__r.FIN_OrderContext__c)) {
                    contextIds.add(payment.FIN_Order__r.FIN_OrderContext__c);
                }
            }
        }

        List<FIN_Context__c> listContexts = [
            SELECT Id, Name
            FROM FIN_Context__c
            WHERE Id IN : contextIds
        ];

        return listContexts;
    }

    @AuraEnabled(cacheable=true)
    public static List<Contract> getContracts(String region) {
        return [
            SELECT Id, Name, ContractNumber
            FROM Contract
            WHERE FIN_Region__c =: region
            AND FIN_ActiveStatus__c = TRUE
            AND ActivatedDate <= TODAY
        ];
    }

    @AuraEnabled(cacheable=false)
    public static Integer createSI(List<Id> paymentDis, String settlementSh) {
        List<FIN_SettlementItem__c> newItems = new List<FIN_SettlementItem__c>();

        List<FIN_PaymentDistribution__c> listPD = [
            SELECT Id, Contract__c, FIN_LibraryAssociation__c, FIN_DistributionAmount__c
            FROM FIN_PaymentDistribution__c
            WHERE Id IN :paymentDis
        ];

        for (FIN_PaymentDistribution__c payment : listPD) {
            payment.FIN_Settlement_Status__c = 'ScheduledSettlement';
            newItems.add(new FIN_SettlementItem__c(
                FIN_PaymentDistribution__c = payment.Id,
                FIN_ParentSettlementSchedule__c = settlementSh,
                FIN_SubContract__c = payment.Contract__c,
                FIN_Amount__c = payment.FIN_DistributionAmount__c,
                FIN_LibraryAssociation__c = payment.FIN_LibraryAssociation__c
            ));
        }

        insert newItems;
        update listPD;

        return newItems.size();
    }

    @AuraEnabled(cacheable=true)
    public static List<Contract> getRelatedSubContractsWithPDs(String settlementSh) {
        List<FIN_SettlementItem__c> listSI = [
            SELECT Id, FIN_PaymentDistribution__r.Contract__c
            FROM FIN_SettlementItem__c
            WHERE FIN_ParentSettlementSchedule__c = :settlementSh
        ];
        Set<String> setContractId = new Set<String>();
        Set<String> setPDIds = new Set<String>();

        for (FIN_SettlementItem__c item : listSI) {
            setContractId.add(item.FIN_PaymentDistribution__r.Contract__c);
            setPDIds.add(item.FIN_PaymentDistribution__c);
        }

        List<Contract> contractList = [
            SELECT Id, Name, ContractNumber, (
                SELECT Id, FIN_DistributionAmount__c, FIN_JournalEntryAmount__c
                FROM Payment_Distributions__r
                WHERE Id IN :setPDIds
            )
            FROM Contract
            WHERE Id IN :setContractId
        ];

        return contractList;
    }

    @AuraEnabled(cacheable=false)
    public static Integer removeRelatedSIs(List<Id> listSubContracts, String settlementSh) {
        List<FIN_SettlementItem__c> listSI = [
            SELECT Id, FIN_PaymentDistribution__r.FIN_Settlement_Status__c
            FROM FIN_SettlementItem__c
            WHERE FIN_PaymentDistribution__r.Contract__c IN :listSubContracts
            AND FIN_ParentSettlementSchedule__c = :settlementSh
        ];

        delete listSI;
        return listSI.size();
    }
}