force-app/main/default/objects/Contract/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_ParentContract__c.field-meta.xml
<CustomField>
    <fullName>FIN_ParentContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contract.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Master</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>SubContracts</relationshipLabel>
    <relationshipName>SubContracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/controllers/CustomLookupController.cls
public class CustomLookupController {
    @AuraEnabled(cacheable=true)
    public static List<SObject> fetchLookupData(String searchKey, String sObjectApiName, String searchField, String contractId) {
        List<SObject> returnList = new List<SObject>();

        String additionalLogic = '';
        if(contractId != null) {
            additionalLogic = ' AND (Contract.FIN_ParentContract__c = :contractId OR ContractId = :contractId) AND ApprovalStatus__c = \'Approved\'';
        } else {
            additionalLogic = ' AND ApprovalStatus__c = \'Approved\'';
        }

        String sQuery = 'SELECT Id, :searchField FROM :sObjectApiName WHERE :searchField LIKE \'%:searchKey%\' :additionalLogic ORDER BY createdDate DESC LIMIT 5';
        System.debug('sQuery'+sQuery);
        for (SObject obj : Database.query(sQuery.replace(':searchField', searchField).replace(':sObjectApiName', sObjectApiName).replace(':searchKey', searchKey).replace(':additionalLogic',additionalLogic))) {
            returnList.add(obj);
        }

        return returnList;
    }

    @AuraEnabled
    public static SObject fetchDefaultRecord(String recordId, String sObjectApiName, String searchField) {
        String sRecId = recordId;
        String sQuery = 'Select Id, '+ searchField + ' From ' + sObjectApiName + ' Where Id = : sRecId LIMIT 1';
        for (SObject obj : Database.query(sQuery)) {
            System.debug('obj'+obj);
            return obj;
        }
        return null;
    }
}