force-app/main/default/objects/Contract/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Client)</relationshipLabel>
    <relationshipName>Contracts_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_Venue__c.field-meta.xml
<CustomField>
    <fullName>FIN_Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/ContractAssociation__c.object-meta.xml
<CustomObject>
    <label>Contract Association</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Contract Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractAssociation__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <filterItems>
            <field>$Source.Context__c</field>
            <operation>equals</operation>
            <valueField>$Source.Context__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Contract_Library_Components1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Library_Associations1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Contract_Library_Components1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/FIN_AXS_Event__c.field-meta.xml
<CustomField>
    <fullName>FIN_AXS_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AXS Event</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Context__c</field>
            <operation>equals</operation>
            <valueField>$Source.Context__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Contract_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/FIN_ContractAssociationMatchingLevel__c.field-meta.xml
<CustomField>
    <fullName>FIN_ContractAssociationMatchingLevel__c</fullName>
    <description>Formula to detect matching condition level</description>
    <formula>IF(AND (!ISBLANK( Context__c ), !ISBLANK( Client__c),!ISBLANK(FIN_Venue__c), !ISBLANK( FIN_AXS_Event__c ),!ISBLANK(FIN_Event_Zone__c)), 8,
IF(AND (!ISBLANK( Context__c ), !ISBLANK( Client__c),!ISBLANK( FIN_AXS_Event__c ),!ISBLANK(FIN_Event_Zone__c)), 7,
IF(AND (!ISBLANK( Context__c ), !ISBLANK( Client__c),!ISBLANK(FIN_Venue__c), !ISBLANK(FIN_Event_Zone__c)), 6,
IF(AND (!ISBLANK( Context__c ), !ISBLANK( Client__c),!ISBLANK(FIN_Venue__c), !ISBLANK( FIN_AXS_Event__c ),ISBLANK(FIN_Event_Zone__c)), 5,
IF(AND (!ISBLANK( Context__c ), !ISBLANK( Client__c),!ISBLANK(FIN_Event_Zone__c), ISBLANK( FIN_Venue__c ), ISBLANK( FIN_AXS_Event__c )), 4,
IF(AND (!ISBLANK( Context__c ), !ISBLANK( Client__c),ISBLANK(FIN_Venue__c), !ISBLANK( FIN_AXS_Event__c ), ISBLANK(FIN_Event_Zone__c)), 3,
IF(AND (!ISBLANK( Context__c ), !ISBLANK( Client__c),!ISBLANK(FIN_Venue__c), ISBLANK( FIN_AXS_Event__c ),ISBLANK(FIN_Event_Zone__c)), 2,
IF(AND (!ISBLANK( Context__c ), !ISBLANK( Client__c)), 1, 0))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract association matching level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/FIN_Event_Zone__c.field-meta.xml
<CustomField>
    <fullName>FIN_Event_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Zone</label>
    <referenceTo>Zone_Types__c</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Contract_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/FIN_Venue__c.field-meta.xml
<CustomField>
    <fullName>FIN_Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select a Venue.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Venue</value>
        </filterItems>
        <filterItems>
            <field>$Source.Context__c</field>
            <operation>equals</operation>
            <valueField>$Source.Context__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Associations (Venue)</relationshipLabel>
    <relationshipName>Contract_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Venue__c.field-meta.xml
<CustomField>
    <fullName>FIN_Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zone_Types__c/Zone_Types__c.object-meta.xml
<CustomObject>
    <label>Zone Type</label>
    <nameField>
        <label>Zone Types (Standard)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/selectors/FIN_ContractAssociationSelector.cls
public with sharing class FIN_ContractAssociationSelector {

    public static List<ContractAssociation__c> getNotDeactivatedContractAssociationsByContractIds(Set<Id> contractIds) {
        return [SELECT Id, ApprovalStatus__c FROM ContractAssociation__c WHERE Contract__c IN :contractIds AND ApprovalStatus__c != 'Deactivated'];
    }

    public static List<ContractAssociation__c> getDeactivatedContractAssociationsByContractIds(Set<Id> contractIds) {
        return [SELECT Id, ApprovalStatus__c FROM ContractAssociation__c WHERE Contract__c IN :contractIds AND ApprovalStatus__c = 'Deactivated'];
    }

    public static List<ContractAssociation__c> getAllContractAssociationsByContextId(String contextId) {
        return [SELECT Id, Contract__c, Contract__r.AccountId, Contract__r.Pricebook2Id, Context__c, FIN_Venue__c, Client__c, FIN_AXS_Event__c, FIN_Event_Zone__r.Name, FIN_Event_Zone__c, FIN_ContractAssociationMatchingLevel__c,
                Contract__r.EndDate, Contract__r.StartDate
        FROM ContractAssociation__c
        WHERE Context__c = :contextId AND Client__c != NULL AND ApprovalStatus__c = 'Approved'
        ORDER BY FIN_ContractAssociationMatchingLevel__c DESC];
    }

    public static List<ContractAssociation__c> getAllContractAssociationsByContractIdInAndContextId(String contextId, List<String> contractIds) {
        return [SELECT Id, Contract__c, Contract__r.AccountId, Contract__r.Pricebook2Id, Context__c, FIN_Venue__c, Client__c, FIN_AXS_Event__c, FIN_Event_Zone__r.Name, FIN_ContractAssociationMatchingLevel__c,
                Contract__r.EndDate, Contract__r.StartDate
        FROM ContractAssociation__c
        WHERE Contract__c IN :contractIds AND Contract__r.Status != 'Deactivated' AND ApprovalStatus__c = 'Approved'
        ORDER BY FIN_ContractAssociationMatchingLevel__c DESC];
    }
}