force-app/main/default/objects/Contract/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/ContractAssociation__c.object-meta.xml
<CustomObject>
    <label>Contract Association</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Contract Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractAssociation__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Contract_Library_Components1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/helpers/FIN_ContractAssociationHelper.cls
public with sharing class FIN_ContractAssociationHelper {
    public static void checkForDeactivatedContract(List<ContractAssociation__c> contractAssociations) {
        Set<Id> contractIds = new Set<Id>();
        for (ContractAssociation__c contractAssociation : contractAssociations) {
            contractIds.add(contractAssociation.Contract__c);
        }
        Map<Id, Contract> contracts = new Map<Id, Contract>(FIN_ContractSelector.getContractByIds(contractIds));
        for (ContractAssociation__c contractAssociation : contractAssociations) {
            if (contracts.get(contractAssociation.Contract__c).Status == 'Deactivated' && contractAssociation.ApprovalStatus__c != 'Deactivated') {
                throw new FIN_ContractAssociationException(Constants.CONTRACT_ASSOCIATION_EXCEPTION_MESSAGE);
            }
        }
    }

    public class FIN_ContractAssociationException extends Exception {
    }

}