force-app/main/default/objects/Contract/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fee_Components__c/Fee_Components__c.object-meta.xml
<CustomObject>
    <label>Fee Component</label>
    <nameField>
        <label>Fee Components Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee_Components__c/fields/FIN_Fee_Category__c.field-meta.xml
<CustomField>
    <fullName>FIN_Fee_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Category</label>
    <referenceTo>FIN_Fee_Category__c</referenceTo>
    <relationshipLabel>Fee Components</relationshipLabel>
    <relationshipName>Fee_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Context__c/FIN_Context__c.object-meta.xml
<CustomObject>
    <label>Context</label>
    <nameField>
        <label>Context Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contexts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Fee_Category__c/FIN_Fee_Category__c.object-meta.xml
<CustomObject>
    <label>Fee Category</label>
    <nameField>
        <label>Fee Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_ContextName__c.field-meta.xml
<CustomField>
    <fullName>FIN_ContextName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context Name</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_EnrichedLibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_EnrichedLibraryAssociation__c</fullName>
    <label>Enriched Library Association</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_FeeComponent__c.field-meta.xml
<CustomField>
    <fullName>FIN_FeeComponent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Component</label>
    <referenceTo>Fee_Components__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>PaymentDistributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distribution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_ProductName__c.field-meta.xml
<CustomField>
    <fullName>FIN_ProductName__c</fullName>
    <label>Product Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_ContextName__c.field-meta.xml
<CustomField>
    <fullName>FIN_ContextName__c</fullName>
    <formula>SBQQ__Contract__r.FIN_Context__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Context Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_EnrichedLibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_EnrichedLibraryAssociation__c</fullName>
    <label>Enriched Library Association</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_FeeComponent__c.field-meta.xml
<CustomField>
    <fullName>FIN_FeeComponent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Component</label>
    <referenceTo>Fee_Components__c</referenceTo>
    <relationshipLabel>Sales Transactions</relationshipLabel>
    <relationshipName>SalesTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Sales Transactions</relationshipLabel>
    <relationshipName>Sales_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_Missing_Library_Association__c.field-meta.xml
<CustomField>
    <fullName>FIN_Missing_Library_Association__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Missing Library Association</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/SBQQ__ContractedPrice__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__ContractedPriceHelp</customHelpPage>
    <description>Contracted (negotiated) price for a product for a given customer account.</description>
    <label>Contracted Price</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Contracted Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracted Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/Association_Type__c.field-meta.xml
<CustomField>
    <fullName>Association_Type__c</fullName>
    <label>Association Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ticket</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Uplift</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Component_Number__c.field-meta.xml
<CustomField>
    <fullName>FIN_Component_Number__c</fullName>
    <inlineHelpText>Indicates what Number the Product Component is within a Context</inlineHelpText>
    <label>Component Key</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Library Associations</relationshipLabel>
    <relationshipName>Library_Associations_Context</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_ContextName__c.field-meta.xml
<CustomField>
    <fullName>FIN_ContextName__c</fullName>
    <formula>FIN_Context__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Context name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Fee_Category__c.field-meta.xml
<CustomField>
    <fullName>FIN_Fee_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Category</label>
    <referenceTo>FIN_Fee_Category__c</referenceTo>
    <relationshipLabel>Library Associations</relationshipLabel>
    <relationshipName>Library_Associations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_FeeComponent__c.field-meta.xml
<CustomField>
    <fullName>FIN_FeeComponent__c</fullName>
    <label>Fee Component</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_ProductName__c.field-meta.xml
<CustomField>
    <fullName>FIN_ProductName__c</fullName>
    <formula>SBQQ__Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/batches/FIN_ReprocessLibraryAssociationsBatch.cls
public with sharing class FIN_ReprocessLibraryAssociationsBatch implements Database.Batchable<SObject> {

    private String contractId;
    private List<Contract> contracts;
    private String batchType;
    private String contextId;

    public FIN_ReprocessLibraryAssociationsBatch(List<Contract> contracts, String contextId, String batchType) {
        this.batchType = batchType;
        this.contextId = contextId;
        this.contracts = contracts;
        if (!this.contracts.isEmpty()) {
            this.contractId = contracts[0].Id;
            this.contracts.remove(0);
        }
    }
    public FIN_ReprocessLibraryAssociationsBatch() {
    }

    public void execute(Database.BatchableContext param1, List<SObject> param2) {
        List<SObject> updatedRecordsList = new List<SObject>();
        Map<FIN_ClassifyRecordsBatch.LibraryAssociationComparingWrapper, SBQQ__ContractedPrice__c> libraryAssociationsMap = new Map<FIN_ClassifyRecordsBatch.LibraryAssociationComparingWrapper, SBQQ__ContractedPrice__c>();
        for (SBQQ__ContractedPrice__c la : FIN_LibraryAssociationSelector.getLibraryAssociationsForReclassificationByContextId(this.contextId)) {
            libraryAssociationsMap.put(new FIN_ClassifyRecordsBatch.LibraryAssociationComparingWrapper(la.FIN_ContextName__c, la.FIN_Fee_Category__c != null ? String.valueOf(la.FIN_Fee_Category__c) : la.FIN_ProductName__c, la.Association_Type__c, la.FIN_Component_Number__c != null ? la.FIN_Component_Number__c : null, la.Id), la);
        }
        for (SObject record : param2) {
            if (String.isBlank((String) record.get('FIN_LibraryAssociation__c'))) {
                FIN_ClassifyRecordsBatch.LibraryAssociationComparingWrapper lacw;
                if (record.getSObjectType().getDescribe().getName() == Schema.OrderItem.getSObjectType().getDescribe().getName()) {
                    OrderItem oi = (OrderItem) record;
                    if (oi.FIN_FeeComponent__c == null) {
                        lacw = new FIN_ClassifyRecordsBatch.LibraryAssociationComparingWrapper(oi.FIN_ContextName__c.toLowerCase(), oi.Product2.Name.toLowerCase(), Constants.getAssociationType(oi.Product2.Name).toLowerCase(), Constants.getTicketComponentType(oi.Product2.Name), oi.FIN_EnrichedLibraryAssociation__c);
                    } else {
                        lacw = new FIN_ClassifyRecordsBatch.LibraryAssociationComparingWrapper(oi.FIN_ContextName__c.toLowerCase(), oi.FIN_FeeComponent__r.FIN_Fee_Category__c, Constants.getAssociationType('fee').toLowerCase());
                    }
                }
                if (record.getSObjectType().getDescribe().getName() == Schema.FIN_PaymentDistribution__c.getSObjectType().getDescribe().getName()) {
                    FIN_PaymentDistribution__c paymentDistribution = (FIN_PaymentDistribution__c) record;
                    if (paymentDistribution.FIN_FeeComponent__c != null) {
                        lacw = new FIN_ClassifyRecordsBatch.LibraryAssociationComparingWrapper(paymentDistribution.FIN_ContextName__r.Name.toLowerCase(), paymentDistribution.FIN_FeeComponent__r.FIN_Fee_Category__c, Constants.getAssociationType('fee').toLowerCase());
                    }
                }
                String enrichedLibAssoc = (String) record.get('FIN_EnrichedLibraryAssociation__c');
                if (String.isNotBlank(enrichedLibAssoc) && lacw == null) {
                    lacw = new FIN_ClassifyRecordsBatch.LibraryAssociationComparingWrapper(enrichedLibAssoc);
                }
                if (libraryAssociationsMap.containsKey(lacw)) {
                    SBQQ__ContractedPrice__c libraryAssociation = libraryAssociationsMap.get(lacw);
                    if (libraryAssociation.FIN_Context__c == record.get(Constants.contextFieldsMap.get(record.getSObjectType().getDescribe().getName()))) {
                        record.put('FIN_LibraryAssociation__c', libraryAssociationsMap.get(lacw).Id);
                    }
                    if (this.batchType == OrderItem.getSObjectType().getDescribe().getName() && (((Boolean) record.get('FIN_Missing_Library_Association__c')) == true)) {
                        record.put('FIN_Missing_Library_Association__c', false);
                    }
                    updatedRecordsList.add(record);
                }
            }
        }
        update updatedRecordsList;
    }

    public void finish(Database.BatchableContext param1) {
        if (!this.contracts.isEmpty()) {
            Database.executeBatch(new FIN_ReprocessLibraryAssociationsBatch(this.contracts, this.contextId, this.batchType));
        }
    }

    public Database.QueryLocator start(Database.BatchableContext param1) {
        return Database.getQueryLocator(Constants.getQueryForLibraryAssociationReclassification(this.batchType));
    }
}