force-app/main/default/objects/Contract/fields/FIN_RemittanceAccount__c.field-meta.xml
<CustomField>
    <fullName>FIN_RemittanceAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remittance Account</label>
    <referenceTo>FIN_Payee__c</referenceTo>
    <relationshipLabel>Contracts (Remittance Account)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Order__c.field-meta.xml
<CustomField>
    <fullName>FIN_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Settlement_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distribution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/FIN_SettlementItem__c.object-meta.xml
<CustomObject>
    <label>Settlement Item</label>
    <nameField>
        <displayFormat>SI-{0000000000}</displayFormat>
        <label>Settlement Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_EntryType__c.field-meta.xml
<CustomField>
    <fullName>FIN_EntryType__c</fullName>
    <label>Entry Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Entry</fullName>
            </value>
            <value>
                <fullName>Manual Adjustment</fullName>
                <default>true</default>
                <label>Manual Adjustment</label>
            </value>
            <value>
                <fullName>Invoice Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_ManualAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_ManualAmount__c</fullName>
    <label>Manual $ Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_ParentSettlementSchedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_ParentSettlementSchedule__c</fullName>
    <label>Parent Settlement Schedule</label>
    <referenceTo>FIN_SettlementSchedule__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_Payout__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_RemittanceAccount__c.field-meta.xml
<CustomField>
    <fullName>FIN_RemittanceAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remittance Account</label>
    <referenceTo>FIN_Payee__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_SubContract__c.field-meta.xml
<CustomField>
    <fullName>FIN_SubContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SubContract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contract.FIN_ParentContract__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementSchedule__c/FIN_SettlementSchedule__c.object-meta.xml
<CustomObject>
    <label>Settlement Schedule</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Settlement Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SettlementSchedule__c/fields/FIN_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SettlementInProgress</fullName>
                <default>true</default>
                <label>Settlement In Progress</label>
            </value>
            <value>
                <fullName>Remittance</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Settlement_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Remittance_Payout__c/Remittance_Payout__c.object-meta.xml
<CustomObject>
    <label>Remittance Payout</label>
    <nameField>
        <displayFormat>RP-{0000000000}</displayFormat>
        <label>Remittance Payout Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remittance Payouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance_Payout__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Remittance Payouts</relationshipLabel>
    <relationshipName>Remittance_Payouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance_Payout__c/fields/FIN_RemittanceAccount__c.field-meta.xml
<CustomField>
    <fullName>FIN_RemittanceAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DELETE Remittance Account</label>
    <referenceTo>FIN_Remittance_Account__c</referenceTo>
    <relationshipLabel>Remittance Payouts</relationshipLabel>
    <relationshipName>Remittance_Payouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance_Payout__c/fields/FIN_SettlementSchedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_SettlementSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Settlement Process</label>
    <referenceTo>FIN_SettlementSchedule__c</referenceTo>
    <relationshipLabel>Remittance Payouts</relationshipLabel>
    <relationshipName>Remittance_Payouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/SBQQ__ContractedPrice__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__ContractedPriceHelp</customHelpPage>
    <description>Contracted (negotiated) price for a product for a given customer account.</description>
    <label>Contracted Price</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Contracted Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracted Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Status__c</fullName>
    <formula>IF (
    ISBLANK(SBQQ__EffectiveDate__c) &amp;&amp; ISBLANK(SBQQ__ExpirationDate__c),
    IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;,
    IF (
        NOT(ISBLANK(SBQQ__EffectiveDate__c)) &amp;&amp; NOT(ISBLANK(SBQQ__ExpirationDate__c)) &amp;&amp;
        TODAY()&lt;= SBQQ__ExpirationDate__c &amp;&amp; TODAY()&gt;= SBQQ__EffectiveDate__c,
        IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;,
        IF (
            NOT(ISBLANK(SBQQ__EffectiveDate__c)) &amp;&amp; ISBLANK(SBQQ__ExpirationDate__c) &amp;&amp; TODAY()&gt;= SBQQ__EffectiveDate__c,
            IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;,
            IF (
                NOT(ISBLANK(SBQQ__ExpirationDate__c)) &amp;&amp; ISBLANK(SBQQ__EffectiveDate__c) &amp;&amp; TODAY()&lt;= SBQQ__ExpirationDate__c,
                IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;, IMAGE(&apos;/img/samples/flag_red.gif&apos;, &apos;red&apos;) + &apos; Inactive&apos;)
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Ticket_price_Component__c.field-meta.xml
<CustomField>
    <fullName>FIN_Ticket_price_Component__c</fullName>
    <label>Ticket Price and Component</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AXS Payment Fee</fullName>
            </value>
            <value>
                <fullName>AXS Premium Fee</fullName>
            </value>
            <value>
                <fullName>AXS Ticket Fee</fullName>
            </value>
            <value>
                <fullName>Venue Delivery Fee</fullName>
            </value>
            <value>
                <fullName>Venue Premium Fee</fullName>
            </value>
            <value>
                <fullName>Venue Ticket Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FIN_Settlement_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>ToBeSettled</fullName>
        <label>To Be Settled</label>
    </customValue>
    <customValue>
        <fullName>Settled</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>ScheduledSettlement</fullName>
        <label>Scheduled for Settlement</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <masterLabel>Settlement Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/helpers/FIN_SettlementScheduleHelper.cls
public with sharing class FIN_SettlementScheduleHelper {
    public static void updateStatusesAfterUpdate(List<FIN_SettlementSchedule__c> schedules, Map<Id, FIN_SettlementSchedule__c> oldMap) {
        Set<Id> scheduleCompleteIds = new Set<Id>();
        Set<Id> scheduleVoidIds = new Set<Id>();

        for (FIN_SettlementSchedule__c schedule : schedules) {
            if (schedule.FIN_Status__c != oldMap?.get(schedule.Id)?.FIN_Status__c && schedule.FIN_Status__c == 'Complete') {
                scheduleCompleteIds.add(schedule.Id);
            } else if (schedule.FIN_Status__c != oldMap?.get(schedule.Id)?.FIN_Status__c && schedule.FIN_Status__c == 'Void') {
                scheduleVoidIds.add(schedule.Id);
            }
        }

        List<FIN_SettlementItem__c> itemsComplete = [
            SELECT Id, FIN_PaymentDistribution__c, FIN_PaymentDistribution__r.FIN_Payment__r.FIN_Order__c
            FROM FIN_SettlementItem__c
            WHERE FIN_ParentSettlementSchedule__c IN :scheduleCompleteIds
        ];

        List<FIN_SettlementItem__c> itemsVoid = [
            SELECT Id, FIN_PaymentDistribution__c,FIN_PaymentDistribution__r.FIN_Payment__r.FIN_Order__c
            FROM FIN_SettlementItem__c
            WHERE FIN_ParentSettlementSchedule__c IN :scheduleVoidIds
        ];

        Set<Id> pdCompleteIds = new Set<Id>();
        Set<Id> pdVoidIds = new Set<Id>();
        Set<Id> salesCompleteIds = new Set<Id>();
        Set<Id> salesVoidIds = new Set<Id>();

        for (FIN_SettlementItem__c item : itemsComplete) {
            pdCompleteIds.add(item.FIN_PaymentDistribution__c);
            salesCompleteIds.add(item.FIN_PaymentDistribution__r.FIN_Payment__r.FIN_Order__c);
        }

        for (FIN_SettlementItem__c item : itemsVoid) {
            pdVoidIds.add(item.FIN_PaymentDistribution__c);
            salesVoidIds.add(item.FIN_PaymentDistribution__r.FIN_Payment__r.FIN_Order__c);
        }

        List<FIN_PaymentDistribution__c> pdCompeteList = [
            SELECT Id, FIN_Settlement_Status__c
            FROM FIN_PaymentDistribution__c
            WHERE Id IN :pdCompleteIds
        ];

        List<FIN_PaymentDistribution__c> pdVoidList = [
            SELECT Id, FIN_Settlement_Status__c
            FROM FIN_PaymentDistribution__c
            WHERE Id IN :pdVoidIds
        ];

        for (FIN_PaymentDistribution__c pd : pdCompeteList) {
            pd.FIN_Settlement_Status__c = 'Settled';
        }

        for (FIN_PaymentDistribution__c pd : pdVoidList) {
            pd.FIN_Settlement_Status__c = 'Voided';
        }

        List<Order> salesCompleteList = [
            SELECT Id, Settlement_Status__c
            FROM Order
            WHERE Id IN :salesCompleteIds
        ];

        List<Order> salesVoidList = [
            SELECT Id, Settlement_Status__c
            FROM Order
            WHERE Id IN :salesVoidIds
        ];

        for (Order sales : salesCompleteList) {
            sales.Settlement_Status__c = 'Settled';
        }

        for (Order sales : salesVoidList) {
            sales.Settlement_Status__c = 'Voided';
        }

        update pdCompeteList;
        update pdVoidList;
        update salesCompleteList;
        update salesVoidList;
    }

    public static void createRemittancePayoutsAfterUpdate(List<FIN_SettlementSchedule__c> schedules, Map<Id, FIN_SettlementSchedule__c> oldMap) {
        
        Set<Id> schedulesIDs = new Set<Id>();

        for (FIN_SettlementSchedule__c schedule : schedules) {
            if (schedule.FIN_Status__c != oldMap?.get(schedule.Id)?.FIN_Status__c && schedule.FIN_Status__c == 'Remittance') {
                schedulesIDs.add(schedule.Id);
            }
        }

        List<FIN_SettlementItem__c> settlementItemsList = [
            SELECT Id, FIN_PaymentDistribution__c, FIN_Payout__c, FIN_EntryType__c, FIN_ManualAmount__c,
                    FIN_SubContract__r.FIN_RemittanceAccount__c,
                    FIN_ParentSettlementSchedule__c,
                    FIN_LibraryAssociation__r.FIN_Ticket_price_Component__c,
                    FIN_LibraryAssociation__r.FIN_Fee_and_Component__c,
                    FIN_ParentSettlementSchedule__r.FIN_RemittanceDate__c,
                    FIN_ParentSettlementSchedule__r.FIN_PublishingDate__c,
                    FIN_ParentSettlementSchedule__r.FIN_Contract__c,
                    FIN_PaymentDistribution__r.FIN_DistributionAmount__c
            FROM FIN_SettlementItem__c
            WHERE FIN_ParentSettlementSchedule__c IN :schedulesIDs
            AND FIN_PaymentDistribution__c != null      // do we need to take only SIs of regular entry?
        ];

        Map<Id, FIN_SettlementItem__c> payeesSettlementItemMap = new Map<Id, FIN_SettlementItem__c>();
        Map<Id, List<FIN_SettlementItem__c>> payeesAllSettlementItemsMap = new Map<Id, List<FIN_SettlementItem__c>>();

        for (FIN_SettlementItem__c si : settlementItemsList) {
            payeesSettlementItemMap.put(si.FIN_SubContract__r.FIN_RemittanceAccount__c, si);
        }

        for (ID payeeID : payeesSettlementItemMap.keySet()) {
            List<FIN_SettlementItem__c> settleItemsOfThisPayee = new List<FIN_SettlementItem__c>();

            for (FIN_SettlementItem__c siCurrent : settlementItemsList) {
                if (siCurrent.FIN_SubContract__r.FIN_RemittanceAccount__c == payeeID) {
                    settleItemsOfThisPayee.add(siCurrent);    
                }
            }
            payeesAllSettlementItemsMap.put(payeeID, settleItemsOfThisPayee);
        }

        Map<Id, Double> payeeTotalAmount = new Map<Id, Double>();
        Map<Id, Double> payeeDistributionAmount = new Map<Id, Double>();
        
        if (payeesAllSettlementItemsMap.values() != null) {
            
            for (ID payeeID : payeesAllSettlementItemsMap.keySet()) {
                Double totalAmount = 0;
                Double distributionAmount = 0;
    
                for (FIN_SettlementItem__c siForCalculation : payeesAllSettlementItemsMap.get(payeeID)) {
                   
                    String ticketPriceAndComponent = siForCalculation.FIN_LibraryAssociation__r.FIN_Ticket_price_Component__c;
                    String feeAndComponent = siForCalculation.FIN_LibraryAssociation__r.FIN_Fee_and_Component__c;
                    String criteriaString = 'Venue';

                    if (ticketPriceAndComponent != null) {
                        if (ticketPriceAndComponent.contains(criteriaString)) {
                            totalAmount += siForCalculation.FIN_PaymentDistribution__r.FIN_DistributionAmount__c;
                            System.Debug('totalAmount = ' + totalAmount);
                        } else {
                            distributionAmount += siForCalculation.FIN_PaymentDistribution__r.FIN_DistributionAmount__c;
                            System.Debug('distributionAmount = ' + distributionAmount);
                        }
                    } 
                    
                    if (feeAndComponent != null) {
                        if (feeAndComponent.contains(criteriaString)) {
                            totalAmount += siForCalculation.FIN_PaymentDistribution__r.FIN_DistributionAmount__c;
                        } else {
                            distributionAmount += siForCalculation.FIN_PaymentDistribution__r.FIN_DistributionAmount__c;
                        }
                    } 
                }
                payeeTotalAmount.put(payeeID, totalAmount);
                payeeDistributionAmount.put(payeeID, distributionAmount);
            }
        }

        List<Remittance_Payout__c> remittancePayoutsList = new List<Remittance_Payout__c>();

        for (Id payeeId : payeesSettlementItemMap.keySet()) {
            Remittance_Payout__c rp = new Remittance_Payout__c();
            rp.Payee__c = payeeId;
            rp.Due_Date__c = payeesSettlementItemMap.get(payeeId).FIN_ParentSettlementSchedule__r.FIN_RemittanceDate__c;
            rp.FIN_PublishDate__c = payeesSettlementItemMap.get(payeeId).FIN_ParentSettlementSchedule__r.FIN_PublishingDate__c;
            rp.FIN_SettlementSchedule__c = payeesSettlementItemMap.get(payeeId).FIN_ParentSettlementSchedule__c;
            rp.Contract__c = payeesSettlementItemMap.get(payeeId).FIN_ParentSettlementSchedule__r.FIN_Contract__c;
            rp.FIN_RemittancePayoutAmount__c = payeeTotalAmount.get(payeeId);
            rp.Distribution_Amount__c = payeeDistributionAmount.get(payeeId);

            remittancePayoutsList.add(rp);
        }

        insert remittancePayoutsList;
    }
}