force-app/main/default/objects/Contract/fields/FIN_LegalName__c.field-meta.xml
<CustomField>
    <fullName>FIN_LegalName__c</fullName>
    <description>Pulls from an account field of the same name to display read only text of Legal Name</description>
    <formula>Account.FIN_LegalName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Legal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_RemittanceAccount__c.field-meta.xml
<CustomField>
    <fullName>FIN_RemittanceAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remittance Account</label>
    <referenceTo>FIN_Payee__c</referenceTo>
    <relationshipLabel>Contracts (Remittance Account)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payee__c/FIN_Payee__c.object-meta.xml
<CustomObject>
    <label>Remittance Account</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Payee</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remittance Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payee__c/fields/FIN_LegalName__c.field-meta.xml
<CustomField>
    <fullName>FIN_LegalName__c</fullName>
    <label>Beneficiary Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_Remittance_Account__c/FIN_Remittance_Account__c.object-meta.xml
<CustomObject>
    <label>DELETE - Remittance Account</label>
    <nameField>
        <label>Remittance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DELETE - Remittance Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_RemittanceItem__c/FIN_RemittanceItem__c.object-meta.xml
<CustomObject>
    <label>Remittance Item</label>
    <nameField>
        <displayFormat>RI-{0000000000}</displayFormat>
        <label>Remittance Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remittance Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_RemittanceItem__c/fields/FIN_ParentRemittanceSchedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_ParentRemittanceSchedule__c</fullName>
    <label>Parent Remittance Schedule</label>
    <referenceTo>FIN_RemittanceSchedule__c</referenceTo>
    <relationshipLabel>Remittance Items</relationshipLabel>
    <relationshipName>Remittance_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FIN_RemittanceItem__c/fields/FIN_Payee__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remittance Account</label>
    <referenceTo>FIN_Payee__c</referenceTo>
    <relationshipLabel>Remittance Items</relationshipLabel>
    <relationshipName>Remittance_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RemittanceItem__c/fields/FIN_RemittanceAccount__c.field-meta.xml
<CustomField>
    <fullName>FIN_RemittanceAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DELETE Remittance Account</label>
    <referenceTo>FIN_Remittance_Account__c</referenceTo>
    <relationshipLabel>Remittance Items</relationshipLabel>
    <relationshipName>Remittance_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RemittanceItem__c/fields/FIN_RemittanceAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_RemittanceAmount__c</fullName>
    <label>Remittance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_RemittanceItem__c/fields/FIN_RemittancePayout__c.field-meta.xml
<CustomField>
    <fullName>FIN_RemittancePayout__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remittance Payout</label>
    <referenceTo>Remittance_Payout__c</referenceTo>
    <relationshipLabel>Remittance Items</relationshipLabel>
    <relationshipName>Remittance_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementSchedule__c/FIN_SettlementSchedule__c.object-meta.xml
<CustomObject>
    <label>Settlement Schedule</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Settlement Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance_Payout__c/Remittance_Payout__c.object-meta.xml
<CustomObject>
    <label>Remittance Payout</label>
    <nameField>
        <displayFormat>RP-{0000000000}</displayFormat>
        <label>Remittance Payout Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remittance Payouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance_Payout__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Remittance Payouts</relationshipLabel>
    <relationshipName>Remittance_Payouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance_Payout__c/fields/FIN_PublishDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_PublishDate__c</fullName>
    <label>Publishing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Remittance_Payout__c/fields/FIN_RemittanceAccount__c.field-meta.xml
<CustomField>
    <fullName>FIN_RemittanceAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DELETE Remittance Account</label>
    <referenceTo>FIN_Remittance_Account__c</referenceTo>
    <relationshipLabel>Remittance Payouts</relationshipLabel>
    <relationshipName>Remittance_Payouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance_Payout__c/fields/FIN_RemittancePayoutAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_RemittancePayoutAmount__c</fullName>
    <label>Remittance Payout Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Remittance_Payout__c/fields/FIN_SettlementSchedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_SettlementSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Settlement Process</label>
    <referenceTo>FIN_SettlementSchedule__c</referenceTo>
    <relationshipLabel>Remittance Payouts</relationshipLabel>
    <relationshipName>Remittance_Payouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance_Payout__c/fields/FIN_SettlementScheduleStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_SettlementScheduleStatus__c</fullName>
    <formula>TEXT(FIN_SettlementSchedule__r.FIN_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Settlement Process Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remittance_Payout__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remittance Account</label>
    <referenceTo>FIN_Payee__c</referenceTo>
    <relationshipLabel>Remittance Payouts</relationshipLabel>
    <relationshipName>Remittance_Payouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance_Payout__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Exported</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/controllers/RemittanceDataController.cls
public with sharing class RemittanceDataController {
    @AuraEnabled(cacheable=false)
    public static List<Remittance_Payout__c> getFilteredRPs(Date remittanceDate, Date dueDate, String payees, String contracts, String ssNums) {

        String query = 'SELECT Id, Payee__c, Payee__r.FIN_LegalName__c, FIN_RemittanceAccount__r.Name, FIN_RemittancePayoutAmount__c, ' +
            'FIN_SettlementSchedule__r.Name, FIN_SettlementScheduleStatus__c, Due_Date__c, FIN_PublishDate__c, Status__c, Name, ' +
            'Contract__c, Contract__r.ContractNumber, FIN_RemittanceAccount__c ' +
            'FROM Remittance_Payout__c ' +
            'WHERE Status__c = \'Approved\'';

        if (remittanceDate != null) {
            query += ' AND FIN_PublishDate__c = :remittanceDate';
        }
        if (dueDate != null) {
            query += ' AND Due_Date__c = :dueDate';
        }
        if (payees != '') {
            query += ' AND Payee__c = :payees';
        }
        if (contracts != '') {
            query += ' AND Contract__c = :contracts';
        }
        if (ssNums != '') {
            query += ' AND FIN_SettlementSchedule__c = :ssNums';
        }

        List<Remittance_Payout__c> filteredRPs = new List<Remittance_Payout__c>();
        filteredRPs = Database.query(query);

        System.debug('filteredRPs' + filteredRPs);
        return filteredRPs;
    }

    @AuraEnabled(cacheable=true)
    public static List<FIN_Payee__c> getPayees(String contractId) {
        List<FIN_Payee__c> actualPayees = new List<FIN_Payee__c>();
        List<Id> actualPayeesIDs = new List<Id>();

        List<Remittance_Payout__c> rpList = [
            SELECT Id, Payee__c
            FROM Remittance_Payout__c
            WHERE Status__c = 'Approved'
        ];

        for (Remittance_Payout__c rp : rpList) {
            actualPayeesIDs.add(rp.Payee__c);
        }

        for (FIN_Payee__c p : [SELECT Id, FIN_LegalName__c FROM FIN_Payee__c WHERE Id IN :actualPayeesIDs]) {
            actualPayees.add(p);
        }

        return actualPayees;
    }

    @AuraEnabled(cacheable=true)
    public static List<Contract> getContracts(String contractId) {
        List<Contract> actualContracts = new List<Contract>();
        List<Id> actualContractsIDs = new List<Id>();

        List<Remittance_Payout__c> rpList = [
            SELECT Id, Contract__c
            FROM Remittance_Payout__c
            WHERE Status__c = 'Approved'
        ];

        for (Remittance_Payout__c rp : rpList) {
            actualContractsIDs.add(rp.Contract__c);
        }

        for (Contract p : [SELECT Id, ContractNumber FROM Contract WHERE Id IN :actualContractsIDs]) {
            actualContracts.add(p);
        }

        return actualContracts;
    }

    @AuraEnabled(cacheable=true)
    public static List<FIN_SettlementSchedule__c> getSSNums(String contractId) {
        List<FIN_SettlementSchedule__c> actualSSs = new List<FIN_SettlementSchedule__c>();
        List<Id> actualSSIDs = new List<Id>();

        List<Remittance_Payout__c> rpList = [
            SELECT Id, FIN_SettlementSchedule__c
            FROM Remittance_Payout__c
            WHERE Status__c = 'Approved'
        ];

        for (Remittance_Payout__c rp : rpList) {
            actualSSIDs.add(rp.FIN_SettlementSchedule__c);
        }

        for (FIN_SettlementSchedule__c p : [SELECT Id, Name FROM FIN_SettlementSchedule__c WHERE Id IN :actualSSIDs]) {
            actualSSs.add(p);
        }

        return actualSSs;
    }

    @AuraEnabled(cacheable=false)
    public static Integer createRI(List<Id> rps, String remittanceSh) {
        List<FIN_RemittanceItem__c> newItems = new List<FIN_RemittanceItem__c>();

        List<Remittance_Payout__c> listRP = [
            SELECT Id, Payee__c, Payee__r.FIN_LegalName__c, FIN_RemittanceAccount__c, FIN_RemittancePayoutAmount__c
            FROM Remittance_Payout__c
            WHERE Id IN :rps
        ];

        for (Remittance_Payout__c rp : listRP) {
            //rp.Status__c = 'Complete';
            newItems.add(new FIN_RemittanceItem__c(
                FIN_RemittancePayout__c = rp.Id,
                FIN_ParentRemittanceSchedule__c = remittanceSh,
                FIN_Payee__c = rp.Payee__c,
                FIN_RemittanceAccount__c = rp.FIN_RemittanceAccount__c,
                FIN_RemittanceAmount__c = rp.FIN_RemittancePayoutAmount__c
            ));
        }

        insert newItems;
        update listRP;

        return newItems.size();
    }
}