force-app/main/default/objects/FIN_System_Log__c/FIN_System_Log__c.object-meta.xml
<CustomObject>
    <label>System Log</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>System Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_System_Log__c/fields/FIN_Error_Log__c.field-meta.xml
<CustomField>
    <fullName>FIN_Error_Log__c</fullName>
    <label>Error Log</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIN_System_Log__c/fields/FIN_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>FIN_Error_Message__c</fullName>
    <label>Error Message</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIN_System_Log__c/fields/FIN_Error_Time__c.field-meta.xml
<CustomField>
    <fullName>FIN_Error_Time__c</fullName>
    <label>Error Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_System_Log__c/fields/FIN_Process__c.field-meta.xml
<CustomField>
    <fullName>FIN_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>System Logs</relationshipLabel>
    <relationshipName>System_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Logger/Logger.cls
public with sharing class Logger {
    public static void log(Exception e, String finProcess, String finRegion) {
        FIN_System_Log__c systemLog = new FIN_System_Log__c();
        systemLog.FIN_Process__c = finProcess;
        systemLog.FIN_Region__c = finRegion;
        systemLog.FIN_Error_Message__c = e.getMessage();
        systemLog.FIN_Error_Time__c = System.now();
        systemLog.FIN_Error_Log__c = e.getStackTraceString();
        insert systemLog;
    }
}