force-app/main/default/objects/FIN_System_Log__c/FIN_System_Log__c.object-meta.xml
<CustomObject>
    <label>System Log</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>System Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_System_Log__c/fields/FIN_Process__c.field-meta.xml
<CustomField>
    <fullName>FIN_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>System Logs</relationshipLabel>
    <relationshipName>System_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/FIN_SystemDataLoadLog__c.object-meta.xml
<CustomObject>
    <label>Finance Raw Data Logs</label>
    <nameField>
        <displayFormat>SDLL-{0000000000}</displayFormat>
        <label>System Data Load Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Raw Data Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_Process__c.field-meta.xml
<CustomField>
    <fullName>FIN_Process__c</fullName>
    <label>Process</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Payment_Distribution</fullName>
                <label>Payment Distribution</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_ProcessDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_ProcessDate__c</fullName>
    <label>Process Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_ReturnedFromSaleTransactions__c.field-meta.xml
<CustomField>
    <fullName>FIN_ReturnedFromSaleTransactions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This indicates was the success status returned from sales transactions creation</description>
    <label>Returned from sale transactions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/testClasses/LoggerTest.cls
@IsTest
public with sharing class LoggerTest {
    @TestSetup
    static void setUp() {
        insert new FIN_SystemDataLoadLog__c(FIN_Process__c = 'Sales', FIN_ProcessDate__c = System.now(), FIN_ReturnedFromSaleTransactions__c = true);
    }

    @IsTest
    static void testLoggerLog() {
        Test.startTest();
        FIN_SystemDataLoadLog__c systemDataLoadLog = [SELECT Id FROM FIN_SystemDataLoadLog__c WHERE FIN_ReturnedFromSaleTransactions__c = TRUE];
        Logger.log(new AuraHandledException('Test'), systemDataLoadLog.Id, 'US');
        System.assertEquals(1, [SELECT Id, FIN_Process__c FROM FIN_System_Log__c WHERE FIN_Process__c = :systemDataLoadLog.Id].size());
        Test.stopTest();
    }
}