force-app/main/default/objects/FIN_AXSRuleAction__c/FIN_AXSRuleAction__c.object-meta.xml
<CustomObject>
    <label>AXS Rule Action</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AXS Rule Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_AXSRuleAction__c/fields/FIN_DestinationField__c.field-meta.xml
<CustomField>
    <fullName>FIN_DestinationField__c</fullName>
    <label>Destination Field</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FIN_Object__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>context_id</fullName>
            </value>
            <value>
                <fullName>context_name</fullName>
            </value>
            <value>
                <fullName>action_date</fullName>
            </value>
            <value>
                <fullName>customer_id</fullName>
            </value>
            <value>
                <fullName>order_id</fullName>
            </value>
            <value>
                <fullName>channel</fullName>
            </value>
            <value>
                <fullName>outlet</fullName>
            </value>
            <value>
                <fullName>operator</fullName>
            </value>
            <value>
                <fullName>offer_lookup</fullName>
            </value>
            <value>
                <fullName>offer_name</fullName>
            </value>
            <value>
                <fullName>venue_id</fullName>
            </value>
            <value>
                <fullName>venue_name</fullName>
            </value>
            <value>
                <fullName>venue_address</fullName>
            </value>
            <value>
                <fullName>venue_city</fullName>
            </value>
            <value>
                <fullName>venue_state</fullName>
            </value>
            <value>
                <fullName>venue_zip</fullName>
            </value>
            <value>
                <fullName>product_id</fullName>
            </value>
            <value>
                <fullName>primary_product_id</fullName>
            </value>
            <value>
                <fullName>product_description</fullName>
            </value>
            <value>
                <fullName>product_type</fullName>
            </value>
            <value>
                <fullName>inventory_type</fullName>
            </value>
            <value>
                <fullName>entity_id</fullName>
            </value>
            <value>
                <fullName>client_id</fullName>
            </value>
            <value>
                <fullName>client_name</fullName>
            </value>
            <value>
                <fullName>event_id</fullName>
            </value>
            <value>
                <fullName>event_lookup</fullName>
            </value>
            <value>
                <fullName>event_description</fullName>
            </value>
            <value>
                <fullName>event_start_date</fullName>
            </value>
            <value>
                <fullName>event_end_date</fullName>
            </value>
            <value>
                <fullName>event_build_date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleAction__c/fields/FIN_Object__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object__c</fullName>
    <label>Source Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Payment_Distribution</fullName>
                <label>Payment Distribution</label>
            </value>
            <value>
                <fullName>Sales Transactions</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
                <isActive>false</isActive>
                <label>Contract</label>
            </value>
            <value>
                <fullName>FIN_Financial_Code__c</fullName>
                <isActive>false</isActive>
                <label>FIN_Financial_Code__c</label>
            </value>
            <value>
                <fullName>FIN_PaymentDistribution__c</fullName>
                <isActive>false</isActive>
                <label>FIN_PaymentDistribution__c</label>
            </value>
            <value>
                <fullName>FIN_Payment__c</fullName>
                <isActive>false</isActive>
                <label>FIN_Payment__c</label>
            </value>
            <value>
                <fullName>Order</fullName>
                <isActive>false</isActive>
                <label>Order</label>
            </value>
            <value>
                <fullName>OrderItem</fullName>
                <isActive>false</isActive>
                <label>OrderItem</label>
            </value>
            <value>
                <fullName>SBQQ__ContractedPrice__c</fullName>
                <isActive>false</isActive>
                <label>SBQQ__ContractedPrice__c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleAction__c/fields/FIN_SortingRule__c.field-meta.xml
<CustomField>
    <fullName>FIN_SortingRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AXS Rule Engine</label>
    <referenceTo>FIN_AXSRuleEngine__c</referenceTo>
    <relationshipLabel>AXS Rule Actions</relationshipLabel>
    <relationshipName>AXS_Rule_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/FIN_AXSRuleCondition__c.object-meta.xml
<CustomObject>
    <label>AXS Rule Condition</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Rule Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AXS Rule Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_Object__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object__c</fullName>
    <description>AXSRuleEngine.object</description>
    <formula>TEXT(FIN_SortingRule__r.FIN_Object__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Object</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_Object_Attribute_Formula__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object_Attribute_Formula__c</fullName>
    <formula>Case(TEXT(FIN_RelatedObject__c) ,
&quot;Payment -&gt; Sales&quot; , $CustomMetadata.FIN_Object_and_Fields__mdt.Payment_Sales.Field_API_Name__c ,
&quot;Payment Distribution -&gt; Payment&quot; , $CustomMetadata.FIN_Object_and_Fields__mdt.Payment_Distribution_Payment.Field_API_Name__c ,
&quot;Payment Distribution -&gt; Sales&quot; , $CustomMetadata.FIN_Object_and_Fields__mdt.Payment_Distribution_Sales.Field_API_Name__c 
,&quot;&quot;) &amp;  TEXT(FIN_RelatedObjectAttribute__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Object Attribute_Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_Operator__c.field-meta.xml
<CustomField>
    <fullName>FIN_Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&lt;&gt;</fullName>
            </value>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_SortingRule__c.field-meta.xml
<CustomField>
    <fullName>FIN_SortingRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AXS Rule Engine</label>
    <referenceTo>FIN_AXSRuleEngine__c</referenceTo>
    <relationshipLabel>AXS Rule Conditions</relationshipLabel>
    <relationshipName>AXS_Rule_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_Value__c.field-meta.xml
<CustomField>
    <fullName>FIN_Value__c</fullName>
    <label>Value</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleEngine__c/FIN_AXSRuleEngine__c.object-meta.xml
<CustomObject>
    <label>AXS Rule Engine</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AXS Rule Engines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_AXSRuleEngine__c/fields/FIN_Object__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
                <default>true</default>
                <label>Sales</label>
            </value>
            <value>
                <fullName>Sales Transactions</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Payment Distribution</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
                <isActive>false</isActive>
                <label>Contract</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleEngine__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleEngine__c/recordTypes/Settlement.recordType-meta.xml
<RecordType>
    <fullName>Settlement</fullName>
    <active>true</active>
    <description>Settlement</description>
    <label>Settlement</label>
</RecordType>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/FIN_SystemDataLoadLog__c.object-meta.xml
<CustomObject>
    <label>Finance Raw Data Logs</label>
    <nameField>
        <displayFormat>SDLL-{0000000000}</displayFormat>
        <label>System Data Load Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Raw Data Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleProcessCompleteStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleProcessCompleteStatus__c</fullName>
    <label>Business Rule Process Complete Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_Process__c.field-meta.xml
<CustomField>
    <fullName>FIN_Process__c</fullName>
    <label>Process</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Payment_Distribution</fullName>
                <label>Payment Distribution</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_ReturnedFromSaleTransactions__c.field-meta.xml
<CustomField>
    <fullName>FIN_ReturnedFromSaleTransactions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This indicates was the success status returned from sales transactions creation</description>
    <label>Returned from sale transactions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_SalesforceRulesEndTime__c.field-meta.xml
<CustomField>
    <fullName>FIN_SalesforceRulesEndTime__c</fullName>
    <label>Salesforce rules end time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_SalesforceRulesStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_SalesforceRulesStatus__c</fullName>
    <label>Salesforce rules status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RulesStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RulesStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
    </customValue>
    <customValue>
        <fullName>In-Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Success Heroku</fullName>
    </customValue>
    <masterLabel>RulesStatus</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/services/FIN_AXSRuleEngineService.cls
public with sharing class FIN_AXSRuleEngineService {
    public static void markRecordsOnHerokuAsProcessed(FIN_SystemDataLoadLog__c systemDataLoadLog) {
        if (systemDataLoadLog.FIN_BusinessRuleProcessCompleteStatus__c == 'Success Heroku') {
            if (systemDataLoadLog.FIN_Process__c == 'Sales' && !systemDataLoadLog.FIN_ReturnedFromSaleTransactions__c) {
                FIN_SystemDataLoadLogService.makeSimpleHttpCallout(JSON.serialize(new Map<String, String>{
                        'systemDataLoadLogId' => systemDataLoadLog.Id
                }), 'callout:Process_Sales_Transactions_Heroku');
            } else {
                markInsertedRecordsAsProcessed(systemDataLoadLog);
            }
        }
    }

    public static void markInsertedRecordsAsProcessed(FIN_SystemDataLoadLog__c systemDataLoadLog) {
        FIN_SystemDataLoadLogService.makeSimpleHttpCallout(JSON.serialize(new Map<String, String>{
                'systemDataLoadLogId' => systemDataLoadLog.Id
        }),
                'callout:Mark_Processed_Records_Heroku');
    }

    public static void processSettlementRuleEngineFromSystemDataLoadLog(FIN_SystemDataLoadLog__c systemDataLoadLog) {
        FIN_SystemDataLoadLog__c systemDataLoad = new FIN_SystemDataLoadLog__c(Id = systemDataLoadLog.Id);
        try {
            processSettlementRules(systemDataLoadLog.FIN_Region__c);
            systemDataLoad.FIN_SalesforceRulesEndTime__c = System.now();
            systemDataLoad.FIN_SalesforceRulesStatus__c = 'Success';
            update systemDataLoad;
        } catch (AuraHandledException e) {
            systemDataLoad.FIN_SalesforceRulesEndTime__c = System.now();
            systemDataLoad.FIN_SalesforceRulesStatus__c = 'Failure';
            update systemDataLoad;
            Logger.log(e, systemDataLoadLog.FIN_Process__c, systemDataLoadLog.FIN_Region__c);
        }
    }

    public static void processSettlementRules(String finRegion) {
        Id settlementRecordTypeId = Schema.SObjectType.FIN_AXSRuleEngine__c.getRecordTypeInfosByName().get('Settlement').getRecordTypeId();
        List<FIN_AXSRuleEngine__c> ruleEngines = FIN_AXSRuleEngineSelector.getSettlementRuleEngines(settlementRecordTypeId, finRegion);
        Map<String, List<AXSRuleEngineWrapper>> ruleEnginesMap = prepareRuleEngineToProcess(ruleEngines);
        for (List<AXSRuleEngineWrapper> ruleEngineWrappers : ruleEnginesMap.values()) {
            for (AXSRuleEngineWrapper ruleEngineWrapper : ruleEngineWrappers) {
                String operator = ruleEngineWrapper.finCondition;
                String finObject = ruleEngineWrapper.finObject;
                String conditions = Constants.getContractFieldFromObject(Constants.finProcessMapForSettlement.get(ruleEngineWrapper.finObject)) + ' = \'' + ruleEngineWrapper.associatedContract + '\'';
                String fieldList = '';
                if (ruleEngineWrapper.ruleConditions != null && !ruleEngineWrapper.ruleConditions.isEmpty()) {
                    conditions += (ruleEngineWrapper.ruleConditions.isEmpty() ? '' : ' AND ' + String.join(prepareConditions(ruleEngineWrapper.ruleConditions), ' ' + operator + ' '));
                }
                if (ruleEngineWrapper.ruleActions != null && !ruleEngineWrapper.ruleActions.isEmpty()) {
                    fieldList = String.join(prepareFieldsList(ruleEngineWrapper.ruleActions), ', ');
                    List<String> destinationConditions = new List<String>();
                    for (FIN_AXSRuleAction__c ruleAction : ruleEngineWrapper.ruleActions) {
                        String condition = !Constants.idFieldsFromRuleAction.contains(ruleAction.FIN_DestinationField__c) ? ruleAction.FIN_DestinationField__c + ' = \'New\' OR ' : '';
                        destinationConditions.add('(' + condition + ruleAction.FIN_DestinationField__c + ' = NULL)');
                    }
                    conditions += ' AND ' + (destinationConditions.isEmpty() ? '' : '(' + String.join(destinationConditions, ' AND ')) + ')';
                }
                if (!String.isBlank(fieldList)) {
                    String query = Constants.STANDART_SELECT_QUERY.replace(':fields', fieldList)
                            .replace(':object', Constants.finProcessMapForSettlement.get(finObject))
                            .replace(':conditions', conditions);
                    if (String.isBlank(conditions)) {
                        query = query.replace('WHERE', '');
                    }
                    System.debug(query);
                    Database.executeBatch(new FIN_UpdateRecordsBatch(query, ruleEngineWrapper.ruleActions));
                }
            }
        }
    }

    private static Map<String, List<AXSRuleEngineWrapper>> prepareRuleEngineToProcess(List<FIN_AXSRuleEngine__c> ruleEngines) {
        List<Id> ruleEnginesIds = new List<Id>();
        for (FIN_AXSRuleEngine__c ruleEngine : ruleEngines) {
            ruleEnginesIds.add(ruleEngine.Id);
        }
        Map<String, List<AXSRuleEngineWrapper>> ruleEngineWrapperMap = new Map<String, List<AXSRuleEngineWrapper>>();
        List<FIN_AXSRuleCondition__c> ruleConditions = FIN_AXSRuleConditonSelector.getRuleConditionsByEnginesIds(ruleEnginesIds);
        List<FIN_AXSRuleAction__c> ruleActions = FIN_AXSRuleActionSelector.getRuleActionsByEnginesIds(ruleEnginesIds);
        for (FIN_AXSRuleEngine__c ruleEngine : ruleEngines) {
            Map<Id, List<FIN_AXSRuleCondition__c>> axsRuleConditions = new Map<Id, List<FIN_AXSRuleCondition__c>>();
            Map<Id, List<FIN_AXSRuleAction__c>> axsRuleActions = new Map<Id, List<FIN_AXSRuleAction__c>>();
            for (FIN_AXSRuleCondition__c ruleCondition : ruleConditions) {
                if (axsRuleConditions.containsKey(ruleCondition.FIN_SortingRule__c)) {
                    axsRuleConditions.get(ruleCondition.FIN_SortingRule__c).add(ruleCondition);
                } else {
                    axsRuleConditions.put(ruleCondition.FIN_SortingRule__c, new List<FIN_AXSRuleCondition__c>{
                            ruleCondition
                    });
                }
            }
            for (FIN_AXSRuleAction__c ruleAction : ruleActions) {
                if (axsRuleActions.containsKey(ruleAction.FIN_SortingRule__c)) {
                    axsRuleActions.get(ruleAction.FIN_SortingRule__c).add(ruleAction);
                } else {
                    axsRuleActions.put(ruleAction.FIN_SortingRule__c, new List<FIN_AXSRuleAction__c>{
                            ruleAction
                    });
                }
            }
            if (ruleEngineWrapperMap.containsKey(ruleEngine.FIN_Object__c)) {
                ruleEngineWrapperMap.get(ruleEngine.FIN_Object__c).add(new AXSRuleEngineWrapper(ruleEngine,
                        axsRuleConditions.get(ruleEngine.Id), axsRuleActions.get(ruleEngine.Id)));
            } else {
                ruleEngineWrapperMap.put(ruleEngine.FIN_Object__c, new List<AXSRuleEngineWrapper>{
                        new AXSRuleEngineWrapper(ruleEngine,
                                axsRuleConditions.get(ruleEngine.Id), axsRuleActions.get(ruleEngine.Id))
                });
            }
        }
        return ruleEngineWrapperMap;
    }

    private static List<String> prepareConditions(List<FIN_AXSRuleCondition__c> ruleConditions) {
        List<String> conditions = new List<String>();
        for (FIN_AXSRuleCondition__c condition : ruleConditions) {
            if (condition.FIN_Value__c != null && condition.FIN_Object_Attribute_Formula__c != null && condition.FIN_Operator__c != null) {
                conditions.add(prepareCondition(condition));
            }
        }
        return conditions;
    }

    private static List<String> prepareFieldsList(List<FIN_AXSRuleAction__c> ruleActions) {
        List<String> fieldsList = new List<String>();
        for (FIN_AXSRuleAction__c ruleAction : ruleActions) {
            fieldsList.add(ruleAction.FIN_DestinationField__c);
        }
        return fieldsList;
    }

    private static String prepareCondition(FIN_AXSRuleCondition__c ruleCondition) {
        FIN_Object_and_Fields__mdt objectFromMetadata = FIN_Object_and_Fields__mdt.getAll().get(ruleCondition.FIN_Object__c);
        String condition = ruleCondition.FIN_Object_Attribute_Formula__c;
        switch on ruleCondition.FIN_Operator__c {
            when '=' {
                condition += ruleCondition.FIN_Operator__c + getValueInCorrectFormat(ruleCondition.FIN_Value__c, getObjectAttributeType(ruleCondition.FIN_RelatedObjectAttribute__c, objectFromMetadata != null ?
                        objectFromMetadata.DestinationObject__c : Constants.finProcessMapForSettlement.get(ruleCondition.FIN_Object__c)));
            } when '<>' {
                condition += '!=:value';
            } when 'contains' {
                condition += 'LIKE \'%:value%\'';
            }
        }
        return condition.replace(':value', ruleCondition.FIN_Value__c);
    }

    private static Object getValueInCorrectFormat(String value, String attributeType) {
        switch on attributeType {
            when 'DOUBLE' {
                return Integer.valueOf(value);
            } when 'BOOLEAN' {
                return Boolean.valueOf(value);
            } when 'DATETIME' {
                return Datetime.valueOf(value);
            } when 'DATE' {
                return Date.valueOf(value);
            }
            when else {
                return '\'' + value + '\'';
            }
        }
    }

    private static String getObjectAttributeType(String objectAttribute, String objName) {
        return Schema.getGlobalDescribe().get(objName).getDescribe().fields.getMap().get(objectAttribute).getDescribe().getType().name();
    }

    public class AXSRuleEngineWrapper {
        public Id id;
        public String finObject;
        public String finCondition;
        public String finRegion;
        public Id associatedContract;
        public List<FIN_AXSRuleCondition__c> ruleConditions;
        public List<FIN_AXSRuleAction__c> ruleActions;

        public AXSRuleEngineWrapper(FIN_AXSRuleEngine__c ruleEngine, List<FIN_AXSRuleCondition__c> conditions, List<FIN_AXSRuleAction__c> actions) {
            this.id = ruleEngine.Id;
            this.finObject = ruleEngine.FIN_Object__c;
            this.finCondition = ruleEngine.FIN_Condition__c;
            this.finRegion = ruleEngine.FIN_Region__c;
            this.associatedContract = ruleEngine.FIN_AssociatedContract__c;
            this.ruleConditions = conditions;
            this.ruleActions = actions;
        }
    }
}