force-app/main/default/objects/FIN_AXSRuleAction__c/FIN_AXSRuleAction__c.object-meta.xml
<CustomObject>
    <label>AXS Rule Action</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AXS Rule Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_AXSRuleAction__c/fields/FIN_DestinationField__c.field-meta.xml
<CustomField>
    <fullName>FIN_DestinationField__c</fullName>
    <label>Destination Field</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FIN_Object__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>context_id</fullName>
            </value>
            <value>
                <fullName>context_name</fullName>
            </value>
            <value>
                <fullName>action_date</fullName>
            </value>
            <value>
                <fullName>customer_id</fullName>
            </value>
            <value>
                <fullName>order_id</fullName>
            </value>
            <value>
                <fullName>channel</fullName>
            </value>
            <value>
                <fullName>outlet</fullName>
            </value>
            <value>
                <fullName>operator</fullName>
            </value>
            <value>
                <fullName>offer_lookup</fullName>
            </value>
            <value>
                <fullName>offer_name</fullName>
            </value>
            <value>
                <fullName>venue_id</fullName>
            </value>
            <value>
                <fullName>venue_name</fullName>
            </value>
            <value>
                <fullName>venue_address</fullName>
            </value>
            <value>
                <fullName>venue_city</fullName>
            </value>
            <value>
                <fullName>venue_state</fullName>
            </value>
            <value>
                <fullName>venue_zip</fullName>
            </value>
            <value>
                <fullName>product_id</fullName>
            </value>
            <value>
                <fullName>primary_product_id</fullName>
            </value>
            <value>
                <fullName>product_description</fullName>
            </value>
            <value>
                <fullName>product_type</fullName>
            </value>
            <value>
                <fullName>inventory_type</fullName>
            </value>
            <value>
                <fullName>entity_id</fullName>
            </value>
            <value>
                <fullName>client_id</fullName>
            </value>
            <value>
                <fullName>client_name</fullName>
            </value>
            <value>
                <fullName>event_id</fullName>
            </value>
            <value>
                <fullName>event_lookup</fullName>
            </value>
            <value>
                <fullName>event_description</fullName>
            </value>
            <value>
                <fullName>event_start_date</fullName>
            </value>
            <value>
                <fullName>event_end_date</fullName>
            </value>
            <value>
                <fullName>event_build_date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleAction__c/fields/FIN_DestinationFieldValue__c.field-meta.xml
<CustomField>
    <fullName>FIN_DestinationFieldValue__c</fullName>
    <label>Destination Field Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleAction__c/fields/FIN_Object__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object__c</fullName>
    <label>Source Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Payment_Distribution</fullName>
                <label>Payment Distribution</label>
            </value>
            <value>
                <fullName>Sales Transactions</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
                <isActive>false</isActive>
                <label>Contract</label>
            </value>
            <value>
                <fullName>FIN_Financial_Code__c</fullName>
                <isActive>false</isActive>
                <label>FIN_Financial_Code__c</label>
            </value>
            <value>
                <fullName>FIN_PaymentDistribution__c</fullName>
                <isActive>false</isActive>
                <label>FIN_PaymentDistribution__c</label>
            </value>
            <value>
                <fullName>FIN_Payment__c</fullName>
                <isActive>false</isActive>
                <label>FIN_Payment__c</label>
            </value>
            <value>
                <fullName>Order</fullName>
                <isActive>false</isActive>
                <label>Order</label>
            </value>
            <value>
                <fullName>OrderItem</fullName>
                <isActive>false</isActive>
                <label>OrderItem</label>
            </value>
            <value>
                <fullName>SBQQ__ContractedPrice__c</fullName>
                <isActive>false</isActive>
                <label>SBQQ__ContractedPrice__c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleAction__c/fields/FIN_SortingRule__c.field-meta.xml
<CustomField>
    <fullName>FIN_SortingRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AXS Rule Engine</label>
    <referenceTo>FIN_AXSRuleEngine__c</referenceTo>
    <relationshipLabel>AXS Rule Actions</relationshipLabel>
    <relationshipName>AXS_Rule_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleEngine__c/FIN_AXSRuleEngine__c.object-meta.xml
<CustomObject>
    <label>AXS Rule Engine</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AXS Rule Engines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_AXSRuleEngine__c/fields/FIN_Object__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
                <default>true</default>
                <label>Sales</label>
            </value>
            <value>
                <fullName>Sales Transactions</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Payment Distribution</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
                <isActive>false</isActive>
                <label>Contract</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/selectors/FIN_AXSRuleActionSelector.cls
public with sharing class FIN_AXSRuleActionSelector {
    public static List<FIN_AXSRuleAction__c> getRuleActionsByEnginesIds(List<Id> ruleEngineIds) {
        return [SELECT Id, FIN_DestinationField__c, FIN_DestinationFieldValue__c, FIN_Object__c, FIN_SortingRule__c, FIN_SortingRule__r.Name
                    FROM FIN_AXSRuleAction__c
                    WHERE FIN_SortingRule__c IN :ruleEngineIds];
    }
}