force-app/main/default/objects/FIN_AXSRuleAction__c/FIN_AXSRuleAction__c.object-meta.xml
<CustomObject>
    <label>AXS Rule Action</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AXS Rule Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_AXSRuleAction__c/fields/FIN_DestinationField__c.field-meta.xml
<CustomField>
    <fullName>FIN_DestinationField__c</fullName>
    <label>Destination Field</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FIN_Object__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>context_id</fullName>
            </value>
            <value>
                <fullName>context_name</fullName>
            </value>
            <value>
                <fullName>action_date</fullName>
            </value>
            <value>
                <fullName>customer_id</fullName>
            </value>
            <value>
                <fullName>order_id</fullName>
            </value>
            <value>
                <fullName>channel</fullName>
            </value>
            <value>
                <fullName>outlet</fullName>
            </value>
            <value>
                <fullName>operator</fullName>
            </value>
            <value>
                <fullName>offer_lookup</fullName>
            </value>
            <value>
                <fullName>offer_name</fullName>
            </value>
            <value>
                <fullName>venue_id</fullName>
            </value>
            <value>
                <fullName>venue_name</fullName>
            </value>
            <value>
                <fullName>venue_address</fullName>
            </value>
            <value>
                <fullName>venue_city</fullName>
            </value>
            <value>
                <fullName>venue_state</fullName>
            </value>
            <value>
                <fullName>venue_zip</fullName>
            </value>
            <value>
                <fullName>product_id</fullName>
            </value>
            <value>
                <fullName>primary_product_id</fullName>
            </value>
            <value>
                <fullName>product_description</fullName>
            </value>
            <value>
                <fullName>product_type</fullName>
            </value>
            <value>
                <fullName>inventory_type</fullName>
            </value>
            <value>
                <fullName>entity_id</fullName>
            </value>
            <value>
                <fullName>client_id</fullName>
            </value>
            <value>
                <fullName>client_name</fullName>
            </value>
            <value>
                <fullName>event_id</fullName>
            </value>
            <value>
                <fullName>event_lookup</fullName>
            </value>
            <value>
                <fullName>event_description</fullName>
            </value>
            <value>
                <fullName>event_start_date</fullName>
            </value>
            <value>
                <fullName>event_end_date</fullName>
            </value>
            <value>
                <fullName>event_build_date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleAction__c/fields/FIN_DestinationFieldValue__c.field-meta.xml
<CustomField>
    <fullName>FIN_DestinationFieldValue__c</fullName>
    <label>Destination Field Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleAction__c/fields/FIN_Object__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object__c</fullName>
    <label>Source Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Payment_Distribution</fullName>
                <label>Payment Distribution</label>
            </value>
            <value>
                <fullName>Sales Transactions</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
                <isActive>false</isActive>
                <label>Contract</label>
            </value>
            <value>
                <fullName>FIN_Financial_Code__c</fullName>
                <isActive>false</isActive>
                <label>FIN_Financial_Code__c</label>
            </value>
            <value>
                <fullName>FIN_PaymentDistribution__c</fullName>
                <isActive>false</isActive>
                <label>FIN_PaymentDistribution__c</label>
            </value>
            <value>
                <fullName>FIN_Payment__c</fullName>
                <isActive>false</isActive>
                <label>FIN_Payment__c</label>
            </value>
            <value>
                <fullName>Order</fullName>
                <isActive>false</isActive>
                <label>Order</label>
            </value>
            <value>
                <fullName>OrderItem</fullName>
                <isActive>false</isActive>
                <label>OrderItem</label>
            </value>
            <value>
                <fullName>SBQQ__ContractedPrice__c</fullName>
                <isActive>false</isActive>
                <label>SBQQ__ContractedPrice__c</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/batches/FIN_UpdateRecordsBatch.cls
public with sharing class FIN_UpdateRecordsBatch implements Database.Batchable<SObject> {
    private String query;
    private List<FIN_AXSRuleAction__c> ruleActions;

    public FIN_UpdateRecordsBatch(String query, List<FIN_AXSRuleAction__c> ruleActions) {
        this.query = query;
        this.ruleActions = ruleActions;
    }

    public Database.QueryLocator start(Database.BatchableContext param1) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext param1, List<SObject> records) {
        Database.update(processRuleActions(ruleActions, records));
    }

    public void finish(Database.BatchableContext param1) {
    }

    private static List<SObject> processRuleActions(List<FIN_AXSRuleAction__c> axsRuleActions, List<SObject> records) {
        List<SObject> updatedRecords = new List<SObject>();
        for (SObject record : records) {
            for (FIN_AXSRuleAction__c action : axsRuleActions) {
                String valueToCheck = String.valueOf(record.get(action.FIN_DestinationField__c));
                if (valueToCheck == null || valueToCheck == 'New' || valueToCheck == 'NotApplicable') {
                    record.put(action.FIN_DestinationField__c, parseValueWithType(action.FIN_DestinationField__c, action.FIN_Object__c, action.FIN_DestinationFieldValue__c));
                }
            }
            updatedRecords.add(record);
        }
        return updatedRecords;
    }

    private static String getObjectAttributeType(String objectAttribute, String objName) {
        return Schema.getGlobalDescribe().get(objName).getDescribe().fields.getMap().get(objectAttribute).getDescribe().getType().name();
    }

    public static Object parseValueWithType(String objectAttribute, String objName, String value) {
        switch on getObjectAttributeType(objectAttribute, Constants.finProcessMap.get(objName)) {
            when 'DOUBLE' {
                return Integer.valueOf(value);
            } when 'BOOLEAN' {
                return Boolean.valueOf(value);
            } when 'DATETIME' {
                return Datetime.valueOf(value);
            } when 'DATE' {
                return Date.valueOf(value);
            }
            when else {
                return value;
            }
        }
    }
}