force-app/main/default/objects/Account/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/ContractAssociation__c.object-meta.xml
<CustomObject>
    <label>Contract Association</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Contract Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractAssociation__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/recordTypes/Context.recordType-meta.xml
<RecordType>
    <fullName>Context</fullName>
    <active>false</active>
    <label>Context</label>
</RecordType>

force-app/main/default/objects/FIN_Context__c/FIN_Context__c.object-meta.xml
<CustomObject>
    <label>Context</label>
    <nameField>
        <label>Context Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contexts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testClasses/FIN_contractAssociationExtControllerTest.cls
@isTest
public with sharing class FIN_contractAssociationExtControllerTest {
    testMethod static void testSubmit() {
        Account acc = TestDataFactory.createAccount();

        FIN_Context__c context = TestDataFactory.createContext();
        insert context;

        Contract contract = TestDataFactory.createMasterContract(acc.Id, context.Id);
        insert contract;
        ContractAssociation__c cA = TestDataFactory.createContractAssociation(contract);

        Test.startTest();
        FIN_contractAssociationExtController con = new FIN_contractAssociationExtController(new ApexPages.StandardController(cA));
        con.onSubmit();
        cA = [SELECT ApprovalStatus__c FROM ContractAssociation__c WHERE Id = :cA.Id LIMIT 1];
        Test.stopTest();

        System.assertEquals('Approved', cA.ApprovalStatus__c );
    }

    testMethod static void testRecall() {
        Account acc = TestDataFactory.createAccount();

        FIN_Context__c context = TestDataFactory.createContext();
        insert context;

        Contract contract = TestDataFactory.createMasterContract(acc.Id, context.Id);
        insert contract;
        ContractAssociation__c cA = TestDataFactory.createContractAssociation(contract);

        Test.startTest();
        FIN_contractAssociationExtController con = new FIN_contractAssociationExtController(new ApexPages.StandardController(cA));
        con.onRecall();
        cA = [SELECT ApprovalStatus__c FROM ContractAssociation__c WHERE Id = :cA.Id LIMIT 1];
        Test.stopTest();

        System.assertEquals('Recalled', cA.ApprovalStatus__c );
    }
}