force-app/main/default/objects/Account/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/FIN_Client.recordType-meta.xml
<RecordType>
    <fullName>FIN_Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contract/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_ParentContract__c.field-meta.xml
<CustomField>
    <fullName>FIN_ParentContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contract.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Master</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>SubContracts</relationshipLabel>
    <relationshipName>SubContracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/ContractAssociation__c.object-meta.xml
<CustomObject>
    <label>Contract Association</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Contract Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractAssociation__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Contract_Library_Components1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FIN_Context__c/FIN_Context__c.object-meta.xml
<CustomObject>
    <label>Context</label>
    <nameField>
        <label>Context Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contexts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testClasses/FIN_ContractTest.cls
@IsTest
public with sharing class FIN_ContractTest {
    @TestSetup
    static void setUp() {
        RecordType clientRecordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'FIN_Client'];
        Account acc = TestDataFactory.createClientAccount(clientRecordType.Id);
        Contract parent = TestDataFactory.createParentContract(acc.Id);
        Contract sub = TestDataFactory.createContract(acc.Id, parent.Id);
        TestDataFactory.createContractAssociation(sub);
    }

    @IsTest
    static void checkDisabledContract() {
        List<Contract> contracts = TestDataFactory.getParentContract();
        System.assert(contracts.size() == 1);
        Test.startTest();
        Contract ctrct = contracts[0];
        ctrct.Status = 'Deactivated';
        update ctrct;
        for (Contract con : TestDataFactory.getParentContract()[0].SubContracts__r) {
            System.assertEquals('Deactivated', con.Status);
        }
        Test.stopTest();
    }

    @IsTest
    static void checkEnabledContract() {
        List<Contract> contracts = TestDataFactory.getParentContract();
        System.assert(contracts.size() == 1);
        Test.startTest();
        Contract ctrct = contracts[0];
        Set<Id> contractIds = new Set<Id>{ctrct.Id};
        Fin_ContractExtController con = new Fin_ContractExtController(new ApexPages.StandardController(ctrct));
        con.onSubmit();
        ctrct = TestDataFactory.getParentContract()[0];
        List<ContractAssociation__c> contractAssociations = [SELECT Id, ApprovalStatus__c FROM ContractAssociation__c WHERE Contract__c IN :contractIds];
        for (ContractAssociation__c contractAssociation : contractAssociations) {
            System.assertEquals('New', contractAssociation.ApprovalStatus__c);
        }
        Test.stopTest();
    }

    @IsTest
    static void checkContractAssociations() {
        List<Contract> contracts = TestDataFactory.getParentContract();
        System.assert(contracts.size() == 1);
        Test.startTest();
        Contract ctrct = contracts[0];
        ctrct.Status = 'Deactivated';
        update ctrct;
        Set<Id> contractIds = new Set<Id>();

        for (Contract contr : ctrct.SubContracts__r) {
            contractIds.add(contr.Id);
        }
        List<ContractAssociation__c> contractAssociations = [SELECT Id, ApprovalStatus__c FROM ContractAssociation__c WHERE Contract__c IN :contractIds];
        try {
            ContractAssociation__c ca = contractAssociations[0].clone(true, true, false, false);
            ca.ApprovalStatus__c = 'New';
            update ca;
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
        for (ContractAssociation__c contractAssociation : contractAssociations) {
            System.assertEquals('Deactivated', contractAssociation.ApprovalStatus__c);
        }
        Test.stopTest();
    }

    @IsTest
    static void testContractAssociationSelector() {
        Test.startTest();
        List<Contract> parentContract = TestDataFactory.getParentContract();
        List<String> contractIds = new List<String>{parentContract[0].SubContracts__r[0].Id};
        Set<Id> contractIdsSet = new Set<Id>{parentContract[0].SubContracts__r[0].Id};
        String contextId = parentContract[0].SubContracts__r[0].FIN_Context__c;
        List<ContractAssociation__c> contractAssociations = FIN_ContractAssociationSelector.getAllContractAssociationsByContractIdInAndContextId(contextId, contractIds);
        System.assertEquals(1, contractAssociations.size());
        contractAssociations = FIN_ContractAssociationSelector.getAllContractAssociationsByContextId(contextId);
        System.assertEquals(1, contractAssociations.size());
        contractAssociations = FIN_ContractAssociationSelector.getDeactivatedContractAssociationsByContractIds(contractIdsSet);
        System.assertEquals(0, contractAssociations.size());
        Test.stopTest();
    }

    @IsTest
    static void testReclassifyController() {
        Contract contract = TestDataFactory.getParentContract()[0];
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(contract);
        FIN_ReclassifyRelatedRecordsController recordsController = new FIN_ReclassifyRelatedRecordsController(sc);
        recordsController.onReclassify();
        recordsController.onReprocess();
        Test.stopTest();
    }
}