force-app/main/default/objects/Account/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/FIN_RetroactiveAdjustment__c.object-meta.xml
<CustomObject>
    <label>Retroactive Adjustment</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Retroactive Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retroactive Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Adjustment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Amount__c</fullName>
    <label>Adjustment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/testClasses/FIN_OrderHelperTest.cls
@IsTest
private class FIN_OrderHelperTest {
    @IsTest
    static void testOrderSharing() {
        List<User> users = [SELECT Id FROM User WHERE IsActive = TRUE LIMIT 3];

        Account acc = TestDataFactory.createAccount();
        Order ord = TestDataFactory.createTestOrder(acc.Id);
        ord.FIN_Region__c = 'US';
        update ord;

        Group grp = [
            SELECT Id
            FROM Group
            WHERE Name =: 'US Region'
            LIMIT 1
        ];

        List<OrderShare> oShrs = [
            SELECT Id, UserOrGroupId, OrderAccessLevel, RowCause 
            FROM OrderShare 
            WHERE OrderId = :ord.Id 
            AND UserOrGroupId= :grp.Id
        ];

//        System.assertEquals(oShrs.size(), 1);
//        System.assertEquals(oShrs[0].OrderAccessLevel, 'Read');
//        System.assertEquals(oShrs[0].RowCause, 'Manual');
//        System.assertEquals(oShrs[0].UserOrGroupId, grp.Id);
    }  

    @IsTest
    static void testOrderUpdate() {
        try {
            List<FIN_RetroactiveAdjustment__c> oldRetroList = [
                SELECT Id
                FROM FIN_RetroactiveAdjustment__c
            ];
            Id orderRecordTypeId = Schema.SObjectType.FIN_RetroactiveAdjustment__c.getRecordTypeInfosByName().get('Order').getRecordTypeId();
            Account acc = TestDataFactory.createAccount();
            Contact cont = TestDataFactory.createContactForAccount(acc.Id, 'test@g.com');
            Product2 pro = TestDataFactory.createProduct2();
            PricebookEntry standardPriceEntry = TestDataFactory.createPricebookEntry(pro.Id);
            Order ord = TestDataFactory.createTestOrder(acc.Id);

            Test.startTest();
            ord.Adjustment_Amount__c = 10;
            update ord;
            List<FIN_RetroactiveAdjustment__c> newRetroList = [
                SELECT Id, RecordTypeId
                FROM FIN_RetroactiveAdjustment__c
            ];
            Test.stopTest();

            System.assertEquals(oldRetroList.size()+1, newRetroList.size());
            System.assertEquals(newRetroList[0].RecordTypeId, orderRecordTypeId);
        } catch(Exception e) {
            System.debug(e.getMessage());
        }
    }
}