force-app/main/default/objects/Account/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/FIN_Venue__c.field-meta.xml
<CustomField>
    <fullName>FIN_Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Venue</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Client)</relationshipLabel>
    <relationshipName>Contracts_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_ParentContract__c.field-meta.xml
<CustomField>
    <fullName>FIN_ParentContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contract.RecordTypeId</field>
            <operation>equals</operation>
            <value>US Master</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>SubContracts</relationshipLabel>
    <relationshipName>SubContracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_Venue__c.field-meta.xml
<CustomField>
    <fullName>FIN_Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/ContractAssociation__c.object-meta.xml
<CustomObject>
    <label>Contract Association</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Contract Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractAssociation__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <filterItems>
            <field>$Source.Context__c</field>
            <operation>equals</operation>
            <valueField>$Source.Context__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Contract_Library_Components1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Contract_Library_Components1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/FIN_AXS_Event__c.field-meta.xml
<CustomField>
    <fullName>FIN_AXS_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AXS Event</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Context__c</field>
            <operation>equals</operation>
            <valueField>$Source.Context__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Contract_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/FIN_Event_Zone__c.field-meta.xml
<CustomField>
    <fullName>FIN_Event_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Zone</label>
    <referenceTo>Zone_Types__c</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Contract_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/FIN_Venue__c.field-meta.xml
<CustomField>
    <fullName>FIN_Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select a Venue.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Venue</value>
        </filterItems>
        <filterItems>
            <field>$Source.Context__c</field>
            <operation>equals</operation>
            <valueField>$Source.Context__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Associations (Venue)</relationshipLabel>
    <relationshipName>Contract_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/recordTypes/Context.recordType-meta.xml
<RecordType>
    <fullName>Context</fullName>
    <active>false</active>
    <label>Context</label>
</RecordType>

force-app/main/default/objects/FIN_Context__c/FIN_Context__c.object-meta.xml
<CustomObject>
    <label>Context</label>
    <nameField>
        <label>Context Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contexts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Venue__c.field-meta.xml
<CustomField>
    <fullName>FIN_Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zone_Types__c/Zone_Types__c.object-meta.xml
<CustomObject>
    <label>Zone Type</label>
    <nameField>
        <label>Zone Types (Standard)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testClasses/ReclassifyUpdateBatchTest.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
*  Test class for ReclassifyUpdateBatch logic
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Ivan Liolia
* @modifiedBy     Ivan Liolia
* @version        1.0
* @created        2022-04-05
* @modified       2022-04-05
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* vX.X            Name
* YYYY-MM-DD      Explanation of the change.  Multiple lines can be used to explain the change, but
*                 each line should be indented till left aligned with the previous description text.
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/

@isTest
public with sharing class ReclassifyUpdateBatchTest {

    /**
    * @method      setupTestData
    * @description Method that generates the test data used in test methods.
    * @author      Ivan Liolia - 2023-04-05
    */
    @TestSetup
    static void setupTestData(){
        FIN_Context__c context = TestDataFactory.createContext();
        insert context;

        Account client = TestDataFactory.createAccount();

        Account venue = TestDataFactory.createVenue();
        insert venue;

        Campaign event = TestDataFactory.createEvent();
        insert event;

        Zone_Types__c zoneType = TestDataFactory.createZoneType();
        insert zoneType;

        Contract masterContract = TestDataFactory.createMasterContract(client.Id, context.Id);
        insert masterContract;

        Contract subContract = TestDataFactory.createSubContract(client.Id, masterContract.Id, context.Id);
        insert subContract;

        ContractAssociation__c contrAs = TestDataFactory.createFullFilledContractAssociation(context.Id, subContract.Id, client.Id, venue.Id, event.Id, zoneType.Id);
        insert contrAs;

        Order sale = TestDataFactory.createSale(client.Id, masterContract.Id, event.Id, context.Id, venue.Id, zoneType.Name);
        insert sale;

        FIN_Payment__c payment = TestDataFactory.createPayment(sale.Id, masterContract.Id);

        FIN_PaymentDistribution__c paymentDis = TestDataFactory.createPaymentDistributionForReclas(payment.Id, sale.Id, masterContract.Id);
        insert paymentDis;
    }

    /**
     * @method      reclasByContextCLientVenueEventZoneTest
     * @description Tests, that sales, payment and payment distributions should be
     *              remapped from the MasterContract to Subcontract, if Context, Client, Venue,
     *              Event and Zone match
     * @author      Ivan Liolia - 2022-04-05
     */
    @isTest
    static void reclasByContextClientVenueEventZoneTest() {
        List<String> contractIds = new List<String>();

        for (Contract contract : [  SELECT Id
                                    FROM   Contract]) {
            contractIds.add(contract.Id);
        }

        Order oldSale = [   SELECT Id
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        FIN_PaymentDistribution__c oldTransAssociations = [ SELECT Id
                                                            ,      Contract__r.Name
                                                            ,      FIN_Payment__r.Contract__r.Name
                                                            FROM   FIN_PaymentDistribution__c];

        Assert.areEqual('MasterContract', oldSale.Contract.Name);
        Assert.areEqual('MasterContract', oldTransAssociations.Contract__r.Name);
        Assert.areEqual('MasterContract', oldTransAssociations.FIN_Payment__r.Contract__r.Name);

        Test.startTest();
        Database.executeBatch(new ReclassifyUpdateBatch('Order', oldSale.Contract.FIN_Context__c, contractIds), 200);
        Test.stopTest();

        Order reclassifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        FIN_PaymentDistribution__c reclassifiedTransAssociations = [SELECT Id
                                                                    ,      Contract__r.Name
                                                                    ,      FIN_Payment__r.Contract__r.Name
                                                                    FROM   FIN_PaymentDistribution__c];

        Assert.areEqual('SubContract', reclassifiedSale.Contract.Name, 'Sale was not remapped to SubContract Context, Client, Venue, Event and ZoneType');
        Assert.areEqual('SubContract', reclassifiedTransAssociations.Contract__r.Name, 'PaymentDistribution was not remapped after reclassification');
        Assert.areEqual('SubContract', reclassifiedTransAssociations.FIN_Payment__r.Contract__r.Name, 'Payment was not remapped after reclassification');
    }

    /**
     * @method      reclasByContextCLientVenueEventTest
     * @description Tests, that sales, payment and payment distributions should be
     *              remapped from the MasterContract to Subcontract, if Context, Client, Venue,
     *              and Event match
     * @author      Ivan Liolia - 2022-04-05
     */
    @isTest
    static void reclasByContextClientVenueEventTest() {
        List<String> contractIds = new List<String>();

        for (Contract contract : [  SELECT Id
                                    FROM   Contract]) {
            contractIds.add(contract.Id);
        }

        Order oldSale = [   SELECT Id
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual('MasterContract', oldSale.Contract.Name);

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_Event_Zone__c = null;
        update contrAs;

        Test.startTest();
        Database.executeBatch(new ReclassifyUpdateBatch('Order', oldSale.Contract.FIN_Context__c, contractIds), 200);
        Test.stopTest();

        Order reclassifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('SubContract', reclassifiedSale.Contract.Name, 'Sale was not remapped to SubContract by Context, Client, Venue and Event');
    }

    /**
     * @method      reclasByContextCLientEventZoneTest
     * @description Tests, that sales, payment and payment distributions should be
     *              remapped from the MasterContract to Subcontract, if Context, Client, Event,
     *              and ZoneType match
     * @author      Ivan Liolia - 2022-04-05
     */
    @isTest
    static void reclasByContextCLientEventZoneTest() {
        List<String> contractIds = new List<String>();

        for (Contract contract : [  SELECT Id
                                    FROM   Contract]) {
            contractIds.add(contract.Id);
        }

        Order oldSale = [   SELECT Id
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual('MasterContract', oldSale.Contract.Name);

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_Venue__c = null;
        update contrAs;

        Test.startTest();
        Database.executeBatch(new ReclassifyUpdateBatch('Order', oldSale.Contract.FIN_Context__c, contractIds), 200);
        Test.stopTest();

        Order reclassifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('SubContract', reclassifiedSale.Contract.Name, 'Sale was not remapped to SubContract by Context, Client, Event and ZoneType');
    }

    /**
     * @method      reclasByContextCLientVenueZoneTest
     * @description Tests, that sales, payment and payment distributions should be
     *              remapped from the MasterContract to Subcontract, if Context, Client, Venue,
     *              and ZoneType match
     * @author      Ivan Liolia - 2022-04-05
     */
    @isTest
    static void reclasByContextCLientVenueZoneTest() {
        List<String> contractIds = new List<String>();

        for (Contract contract : [  SELECT Id
                                    FROM   Contract]) {
            contractIds.add(contract.Id);
        }

        Order oldSale = [   SELECT Id
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual('MasterContract', oldSale.Contract.Name);

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_AXS_Event__c = null;
        update contrAs;

        Test.startTest();
        Database.executeBatch(new ReclassifyUpdateBatch('Order', oldSale.Contract.FIN_Context__c, contractIds), 200);
        Test.stopTest();

        Order reclassifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('SubContract', reclassifiedSale.Contract.Name, 'Sale was not remapped to SubContract by Context, Client, Venue and ZoneType');
    }

    /**
     * @method      reclasByContextCLientEventTest
     * @description Tests, that sales, payment and payment distributions should be
     *              remapped from the MasterContract to Subcontract, if Context, Client
     *              and Event match
     * @author      Ivan Liolia - 2022-04-05
     */
    @isTest
    static void reclasByContextClientEventTest() {
        List<String> contractIds = new List<String>();

        for (Contract contract : [  SELECT Id
                                    FROM   Contract]) {
            contractIds.add(contract.Id);
        }

        Order oldSale = [   SELECT Id
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual('MasterContract', oldSale.Contract.Name);

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_Event_Zone__c = null;
        contrAs.FIN_Venue__c = null;
        update contrAs;

        Test.startTest();
        Database.executeBatch(new ReclassifyUpdateBatch('Order', oldSale.Contract.FIN_Context__c, contractIds), 200);
        Test.stopTest();

        Order reclassifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('SubContract', reclassifiedSale.Contract.Name, 'Sale was not remapped to SubContract by Context, Client and Event');
    }

    /**
     * @method      reclasByContextCLientVenueTest
     * @description Tests, that sales, payment and payment distributions should be
     *              remapped from the MasterContract to Subcontract, if Context, Client
     *              and Venue match
     * @author      Ivan Liolia - 2022-04-05
     */
    @isTest
    static void reclasByContextClientVenueTest() {
        List<String> contractIds = new List<String>();

        for (Contract contract : [  SELECT Id
                                    FROM   Contract]) {
            contractIds.add(contract.Id);
        }

        Order oldSale = [   SELECT Id
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual('MasterContract', oldSale.Contract.Name);

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_Event_Zone__c = null;
        contrAs.FIN_AXS_Event__c = null;
        update contrAs;

        Test.startTest();
        Database.executeBatch(new ReclassifyUpdateBatch('Order', oldSale.Contract.FIN_Context__c, contractIds), 200);
        Test.stopTest();

        Order reclassifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('SubContract', reclassifiedSale.Contract.Name, 'Sale was not remapped to SubContract by Context, Client and Venue');
    }

    /**
     * @method      reclasByContextCLientZoneTest
     * @description Tests, that sales, payment and payment distributions should be
     *              remapped from the MasterContract to Subcontract, if Context, Client
     *              and Even Zone match
     * @author      Ivan Liolia - 2022-04-11
     */
    @isTest
    static void reclasByContextCLientZoneTest() {
        List<String> contractIds = new List<String>();

        for (Contract contract : [  SELECT Id
                                    FROM   Contract]) {
            contractIds.add(contract.Id);
        }

        Order oldSale = [   SELECT Id
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual('MasterContract', oldSale.Contract.Name);

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_Venue__c = null;
        contrAs.FIN_AXS_Event__c = null;
        update contrAs;

        Test.startTest();
        Database.executeBatch(new ReclassifyUpdateBatch('Order', oldSale.Contract.FIN_Context__c, contractIds), 200);
        Test.stopTest();

        Order reclassifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('SubContract', reclassifiedSale.Contract.Name, 'Sale was not remapped to SubContract by Context, Client and Event Zone');
    }

    /**
     * @method      reclasByContextCLientTest
     * @description Tests, that sales, payment and payment distributions should be
     *              remapped from the MasterContract to Subcontract, if Context
     *              and Client match
     * @author      Ivan Liolia - 2022-04-05
     */
    @isTest
    static void reclasByContextCLientTest() {
        List<String> contractIds = new List<String>();

        for (Contract contract : [  SELECT Id
                                    FROM   Contract]) {
            contractIds.add(contract.Id);
        }

        Order oldSale = [   SELECT Id
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual('MasterContract', oldSale.Contract.Name);

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_Event_Zone__c = null;
        contrAs.FIN_AXS_Event__c = null;
        contrAs.FIN_Venue__c = null;
        update contrAs;

        Test.startTest();
        Database.executeBatch(new ReclassifyUpdateBatch('Order', oldSale.Contract.FIN_Context__c, contractIds), 200);
        Test.stopTest();

        Order reclassifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('SubContract', reclassifiedSale.Contract.Name, 'Sale was not remapped to SubContract by Context and Client');
    }

    /**
     * @method      reclasWhenNoMatchWithEmptyClientTest
     * @description Tests, that sales, payment and payment distributions should be
     *              remapped to the MasterContract if no match with subContracts and
     *              clientId is empty
     * @author      Ivan Liolia - 2022-04-05
     */
    @isTest
    static void reclasWhenNoMatchWithEmptyClientTest() {
        List<String> contractIds = new List<String>();

        Contract subContract = [SELECT Id
                                ,      Name
                                ,      FIN_ParentContract__c
                                FROM   Contract
                                WHERE  Name = 'SubContract'];

        contractIds.add(subContract.Id);
        contractIds.add(subContract.FIN_ParentContract__c);

        Order oldSale = [   SELECT Id
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        oldSale.ContractId = subContract.Id;
        update oldSale;

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_Event_Zone__c = null;
        contrAs.FIN_AXS_Event__c = null;
        contrAs.FIN_Venue__c = null;
        contrAs.Client__c = null;
        update contrAs;

        Test.startTest();
        Database.executeBatch(new ReclassifyUpdateBatch('Order', oldSale.Contract.FIN_Context__c, contractIds), 200);
        Test.stopTest();

        Order reclassifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('MasterContract', reclassifiedSale.Contract.Name, 'Sale should be remapped to the MasterContract');
    }

    /**
     * @method      reclasWhenNoMatchWithFilledClientAndContextTest
     * @description Tests, that sales, payment and payment distributions should be
     *              remapped to the MasterContract if no match with subContracts
     *              when CLient and Context is Not Empty
     * @author      Ivan Liolia - 2022-04-05
     */
    @isTest
    static void reclasWhenNoMatchWithFilledClientAndContextTest() {
        List<String> contractIds = new List<String>();

        Contract subContract = [SELECT Id
                                ,      Name
                                ,      FIN_ParentContract__c
                                FROM   Contract
                                WHERE  Name = 'SubContract'];

        contractIds.add(subContract.Id);
        contractIds.add(subContract.FIN_ParentContract__c);

        Order oldSale = [   SELECT Id
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        oldSale.ContractId = subContract.Id;
        update oldSale;

        Account newClient = TestDataFactory.createAccount();

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_Event_Zone__c = null;
        contrAs.FIN_AXS_Event__c = null;
        contrAs.FIN_Venue__c = null;
        contrAs.Client__c = newClient.Id;
        update contrAs;

        Test.startTest();
        Database.executeBatch(new ReclassifyUpdateBatch('Order', oldSale.Contract.FIN_Context__c, contractIds), 200);
        Test.stopTest();

        Order reclassifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('MasterContract', reclassifiedSale.Contract.Name, 'Sale should be remapped to the MasterContract');
    }
}