force-app/main/default/objects/Account/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_Financial_Standard__c.field-meta.xml
<CustomField>
    <fullName>FIN_Financial_Standard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Standard</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You must select a financial standard</errorMessage>
        <filterItems>
            <field>FIN_Standardization__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Financial Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FIN_Standardization__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_Statistical_Standard__c.field-meta.xml
<CustomField>
    <fullName>FIN_Statistical_Standard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Statistical Standard</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You must select a Statistical Standardization</errorMessage>
        <filterItems>
            <field>FIN_Standardization__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Statistical Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FIN_Standardization__c</referenceTo>
    <relationshipLabel>Statistical Standard</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Context__c/FIN_Context__c.object-meta.xml
<CustomObject>
    <label>Context</label>
    <nameField>
        <label>Context Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contexts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Context__c/fields/FIN_StartDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_StartDate__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FIN_Context__c/recordTypes/US.recordType-meta.xml
<RecordType>
    <fullName>US</fullName>
    <active>true</active>
    <label>US</label>
</RecordType>

force-app/main/default/objects/FIN_Standardization__c/FIN_Standardization__c.object-meta.xml
<CustomObject>
    <label>Standardization (Fin/Stat)</label>
    <nameField>
        <label>Standardization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standardizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testClasses/Fin_ContractExtControllerTests.cls
@isTest
private class Fin_ContractExtControllerTests {

    @IsTest
    static void testSubmit() {
        RecordType record = [SELECT Id FROM RecordType WHERE Name = 'US Master Contract'];
        Account acc = new Account(Name = 'test acc');
        insert acc;
        FIN_Context__c context = new FIN_Context__c(
            FIN_StartDate__c = Date.today() - 1
        );
        insert context;

        Id finRecordTypeId = Schema.SObjectType.FIN_Standardization__c.getRecordTypeInfosByName().get('Financial Standard').getRecordTypeId();
        FIN_Standardization__c standardizationFin = new FIN_Standardization__c(
            Name = 'standardizationFin',
            RecordTypeId = finRecordTypeId
        );
        insert standardizationFin;

        Id statRecordTypeId = Schema.SObjectType.FIN_Standardization__c.getRecordTypeInfosByName().get('Statistical Standard').getRecordTypeId();
        FIN_Standardization__c standardizationStat = new FIN_Standardization__c(
            Name = 'standardizationStat',
            RecordTypeId = statRecordTypeId
        );
        insert standardizationStat;

        Contract Contract = new Contract();
        Contract.RecordTypeId = record.Id;
        Contract.CurrencyIsoCode = 'USD';
        Contract.AccountId = acc.Id;
        Contract.FIN_Context__c = context.Id;
        Contract.FIN_Financial_Standard__c = standardizationFin.Id;
        Contract.FIN_Statistical_Standard__c = standardizationStat.Id;
        insert Contract;

        Test.startTest();
        Fin_ContractExtController con = new Fin_ContractExtController(new ApexPages.StandardController(Contract));
        con.onSubmit();
        Contract = [SELECT ApprovalStatus__c FROM Contract WHERE Id = :Contract.Id LIMIT 1];
        Test.stopTest();

        System.assertEquals('Approved', Contract.ApprovalStatus__c);
    }

    @IsTest
    static void testRecall() {
        RecordType record = [SELECT Id FROM RecordType WHERE Name = 'US Master Contract'];
        Account acc = new Account(Name = 'test acc');
        insert acc;
        FIN_Context__c context = new FIN_Context__c(
            FIN_StartDate__c = Date.today() - 1
        );
        insert context;
        Contract Contract = new Contract();
        Contract.RecordTypeId = record.Id;
        Contract.CurrencyIsoCode = 'USD';
        Contract.AccountId = acc.Id;
        Contract.FIN_Context__c = context.Id;
        insert Contract;


        Test.startTest();
        Fin_ContractExtController con = new Fin_ContractExtController (new ApexPages.StandardController(Contract));
        con.onRecall();
        Contract = [SELECT ApprovalStatus__c FROM Contract WHERE Id = :Contract.Id LIMIT 1];
        Test.stopTest();

        System.assertEquals('Recalled', Contract.ApprovalStatus__c);

    }
}