force-app/main/default/objects/Account/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/FIN_Client.recordType-meta.xml
<RecordType>
    <fullName>FIN_Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/FIN_ResponsePublisher__e/FIN_ResponsePublisher__e.object-meta.xml
<CustomObject>
    <label>Response publisher</label>
    <pluralLabel>FIN_ResponsePublishers</pluralLabel>
</CustomObject>

force-app/main/default/objects/FIN_ResponsePublisher__e/fields/ResponseDTO__c.field-meta.xml
<CustomField>
    <fullName>ResponseDTO__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FIN_ResponsePublisher__e/fields/ResponseType__c.field-meta.xml
<CustomField>
    <fullName>ResponseType__c</fullName>
    <label>Response type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/FIN_SystemDataLoadLog__c.object-meta.xml
<CustomObject>
    <label>Finance Raw Data Logs</label>
    <nameField>
        <displayFormat>SDLL-{0000000000}</displayFormat>
        <label>System Data Load Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Raw Data Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleProcessCompleteStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleProcessCompleteStatus__c</fullName>
    <label>Business Rule Process Complete Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_Process__c.field-meta.xml
<CustomField>
    <fullName>FIN_Process__c</fullName>
    <label>Process</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Payment_Distribution</fullName>
                <label>Payment Distribution</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_ProcessDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_ProcessDate__c</fullName>
    <label>Process Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_StagingTableLoadBusinessApproved__c.field-meta.xml
<CustomField>
    <fullName>FIN_StagingTableLoadBusinessApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Staging Table Load Business Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_StagingTableLoadCompleteStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_StagingTableLoadCompleteStatus__c</fullName>
    <label>Raw Load Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
                <default>true</default>
                <label>In-Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/testClasses/FIN_AXSRuleEngineServiceTest.cls
@IsTest
private class FIN_AXSRuleEngineServiceTest {
    @TestSetup
    static void setUp() {
        RecordType clientRecordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'FIN_Client'];
        Account acc = TestDataFactory.createClientAccount(clientRecordType.Id);
        Contract parent = TestDataFactory.createParentContract(acc.Id);
        insert TestDataFactory.createContext();
        TestDataFactory.createRuleEngine(parent.Id);
        insert TestDataFactory.createSale(acc.Id, parent.Id, null, null, null, 'Admissions');
    }

    @IsTest
    static void testSuccessResponse() {
        testsBehaviour(true, false, false, 'Success Heroku', 'Sales');
    }

    @IsTest
    static void testErrorResponse() {
        testsBehaviour(false, true, false, 'Failure', 'Sales');
    }

    @IsTest
    static void testFromMarkingProcessed() {
        testsBehaviour(true, false, true, 'Success', 'Sales');
    }

    @IsTest
    static void testFalseResponse() {
        testsBehaviour(false, false, false, 'Success Heroku', 'Sales');
    }

    private static void testsBehaviour(Boolean isProcessed, Boolean hasErrors, Boolean isFromMarkingProcessed, String systemDataLoadLogStatus,
                                        String finProcess) {
        FIN_ResponsePublisherService.SystemDataLoadLogResponseBodyWrapper responseBodyWrapper = new FIN_ResponsePublisherService.SystemDataLoadLogResponseBodyWrapper();
        responseBodyWrapper.isFromMarkingProcessed = isFromMarkingProcessed;
        responseBodyWrapper.markedAsProcessedCount = 10;
        responseBodyWrapper.salesTransactionsCount = 20;
        responseBodyWrapper.failedRecords = 0;
        responseBodyWrapper.isProcessed = isProcessed;
        responseBodyWrapper.hasErrors = hasErrors;
        Test.setMock(HttpCalloutMock.class, new CalloutsMock());
        Test.startTest();
        FIN_SystemDataLoadLog__c systemDataLoadLog = new FIN_SystemDataLoadLog__c();
        systemDataLoadLog.FIN_Process__c = 'Sales';
        systemDataLoadLog.FIN_ProcessDate__c = Datetime.now();
        systemDataLoadLog.FIN_StagingTableLoadBusinessApproved__c = true;
        systemDataLoadLog.FIN_StagingTableLoadCompleteStatus__c = 'Success';
        systemDataLoadLog.FIN_Process__c = finProcess;
        systemDataLoadLog.FIN_Region__c = 'US';
        systemDataLoadLog.FIN_BusinessRuleProcessCompleteStatus__c = systemDataLoadLogStatus;
        String systemDataLoadLogId = Database.insert(systemDataLoadLog).id;
        responseBodyWrapper.systemDataLoadLogId = systemDataLoadLogId;
        FIN_ResponsePublisher__e responsePublisher = new FIN_ResponsePublisher__e(ResponseDTO__c = JSON.serialize(responseBodyWrapper),
                ResponseType__c = FIN_SystemDataLoadLog__c.getSObjectType().getDescribe().getName());
        EventBus.publish(responsePublisher);
        Test.stopTest();
        System.assert(1 == 1);
    }
    class CalloutsMock implements HttpCalloutMock {
            public HttpResponse respond(HttpRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"title":"TestTitle","shortDescription":"Short Description","longDescription":"Long Description","desiredSkills":"Test Desired Skills"}');
            response.setStatusCode(200);
            return response;
        }
    }
}