force-app/main/default/objects/Account/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Context__c/FIN_Context__c.object-meta.xml
<CustomObject>
    <label>Context</label>
    <nameField>
        <label>Context Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contexts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Fee_Category__c/FIN_Fee_Category__c.object-meta.xml
<CustomObject>
    <label>Fee Category</label>
    <nameField>
        <label>Fee Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/FIN_ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Submitted for Review</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/SBQQ__ContractedPrice__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__ContractedPriceHelp</customHelpPage>
    <description>Contracted (negotiated) price for a product for a given customer account.</description>
    <label>Contracted Price</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Contracted Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracted Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/Association_Type__c.field-meta.xml
<CustomField>
    <fullName>Association_Type__c</fullName>
    <label>Association Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ticket</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Uplift</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Library Associations</relationshipLabel>
    <relationshipName>Library_Associations_Context</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Fee_Category__c.field-meta.xml
<CustomField>
    <fullName>FIN_Fee_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Category</label>
    <referenceTo>FIN_Fee_Category__c</referenceTo>
    <relationshipLabel>Library Associations</relationshipLabel>
    <relationshipName>Library_Associations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testClasses/FIN_LibraryAssociationHelperTest.cls
@IsTest
private class FIN_LibraryAssociationHelperTest {
    @IsTest
    static void testCheckDuplicates() {
        Account acc = TestDataFactory.createAccount();
        Contract parentContract = TestDataFactory.createParentContract(acc.Id);
        Contract contract = TestDataFactory.createContract(acc.Id, parentContract.Id);

        Order ord = TestDataFactory.createTestOrderWithContract(acc.Id, contract.Id);
        Campaign event = new Campaign(Name = 'Test Name');
        insert event;

        Product2 product = TestDataFactory.createProduct2();
        SBQQ__ContractedPrice__c la = TestDataFactory.createLibraryAssociation(acc.Id);
        la.SBQQ__FilterField__c = '';
        la.SBQQ__Product__c = product.Id;
        la.SBQQ__EffectiveDate__c = Date.today() - 2;
        update la;

        la.FIN_ApprovalStatus__c = 'Approved';
        update la;

        SBQQ__ContractedPrice__c la2 = la.clone(false, false, false);
        FIN_LibraryAssociationHelper.LAComparingWrapper laComparingWrapper = new FIN_LibraryAssociationHelper.LAComparingWrapper(la.FIN_Context__c, la.SBQQ__Product__c, String.valueOfGmt(la.SBQQ__EffectiveDate__c), la.Association_Type__c, la.RecordTypeId, la.FIN_Fee_Category__c);
        FIN_LibraryAssociationHelper.LAComparingWrapper laComparingWrapper2 = new FIN_LibraryAssociationHelper.LAComparingWrapper(la.FIN_Context__c, la.SBQQ__Product__c, String.valueOfGmt(la2.SBQQ__EffectiveDate__c), la2.Association_Type__c, la2.RecordTypeId, la2.FIN_Fee_Category__c);
        System.assert(laComparingWrapper.equals(laComparingWrapper2));
        Boolean exceptionOccurred = false;
        try {
            insert la2;
        } catch (Exception e) {
            exceptionOccurred = true;
        }
        Assert.isTrue(exceptionOccurred, 'An Exception was not thrown');
    }
}