force-app/main/default/objects/Account/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/FIN_Venue__c.field-meta.xml
<CustomField>
    <fullName>FIN_Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Venue</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Client)</relationshipLabel>
    <relationshipName>Contracts_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FIN_Venue__c.field-meta.xml
<CustomField>
    <fullName>FIN_Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/ContractAssociation__c.object-meta.xml
<CustomObject>
    <label>Contract Association</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Contract Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContractAssociation__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <filterItems>
            <field>$Source.Context__c</field>
            <operation>equals</operation>
            <valueField>$Source.Context__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Contract_Library_Components1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Contract_Library_Components1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/FIN_AXS_Event__c.field-meta.xml
<CustomField>
    <fullName>FIN_AXS_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AXS Event</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Context__c</field>
            <operation>equals</operation>
            <valueField>$Source.Context__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Contract_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/FIN_Event_Zone__c.field-meta.xml
<CustomField>
    <fullName>FIN_Event_Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Zone</label>
    <referenceTo>Zone_Types__c</referenceTo>
    <relationshipLabel>Contract Associations</relationshipLabel>
    <relationshipName>Contract_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/fields/FIN_Venue__c.field-meta.xml
<CustomField>
    <fullName>FIN_Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only select a Venue.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Venue</value>
        </filterItems>
        <filterItems>
            <field>$Source.Context__c</field>
            <operation>equals</operation>
            <valueField>$Source.Context__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Associations (Venue)</relationshipLabel>
    <relationshipName>Contract_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContractAssociation__c/recordTypes/Context.recordType-meta.xml
<RecordType>
    <fullName>Context</fullName>
    <active>false</active>
    <label>Context</label>
</RecordType>

force-app/main/default/objects/FIN_Context__c/FIN_Context__c.object-meta.xml
<CustomObject>
    <label>Context</label>
    <nameField>
        <label>Context Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contexts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_ContextName__c.field-meta.xml
<CustomField>
    <fullName>FIN_ContextName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context Name</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Order__c.field-meta.xml
<CustomField>
    <fullName>FIN_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_PaymentTransactionId__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentTransactionId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Payment transaction ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_SystemDataLoadLog__c.field-meta.xml
<CustomField>
    <fullName>FIN_SystemDataLoadLog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>System Data Load Log</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_TransactionId__c.field-meta.xml
<CustomField>
    <fullName>FIN_TransactionId__c</fullName>
    <label>Transaction Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_ContextName__c.field-meta.xml
<CustomField>
    <fullName>FIN_ContextName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context Name</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Order_ID__c.field-meta.xml
<CustomField>
    <fullName>FIN_Order_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order ID</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_PaymentTransactionId__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentTransactionId__c</fullName>
    <label>Payment transaction ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_SystemDataLoadLog__c.field-meta.xml
<CustomField>
    <fullName>FIN_SystemDataLoadLog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>System Data Load Log</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/FIN_SystemDataLoadLog__c.object-meta.xml
<CustomObject>
    <label>Finance Raw Data Logs</label>
    <nameField>
        <displayFormat>SDLL-{0000000000}</displayFormat>
        <label>System Data Load Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Raw Data Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/FIN_OrderContext__c.field-meta.xml
<CustomField>
    <fullName>FIN_OrderContext__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_SystemDataLoadLog__c.field-meta.xml
<CustomField>
    <fullName>FIN_SystemDataLoadLog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>System Data Load Log</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_TransactionId__c.field-meta.xml
<CustomField>
    <fullName>FIN_TransactionId__c</fullName>
    <externalId>true</externalId>
    <label>Transaction Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Venue__c.field-meta.xml
<CustomField>
    <fullName>FIN_Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zone_Types__c/Zone_Types__c.object-meta.xml
<CustomObject>
    <label>Zone Type</label>
    <nameField>
        <label>Zone Types (Standard)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testClasses/FIN_ClassifyRecordsBatchTest.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
*  Test class for FIN_ClassifyRecordsBatch logic
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Ivan Liolia
* @modifiedBy     Ivan Liolia
* @version        1.0
* @created        2022-04-11
* @modified       2022-04-11
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* vX.X            Name
* YYYY-MM-DD      Explanation of the change.  Multiple lines can be used to explain the change, but
*                 each line should be indented till left aligned with the previous description text.
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/

@isTest
public with sharing class FIN_ClassifyRecordsBatchTest {
    private static String fieldsToGet = 'Id, OwnerId, FIN_TransactionId__c';
    private static String sObjectTypeName = 'Order';

    /**
    * @method      setupTestData
    * @description Method that generates the test data used in test methods.
    * @author      Ivan Liolia - 2023-04-11
    */
    @TestSetup
    static void setupTestData(){
        FIN_Context__c context = TestDataFactory.createContext();
        insert context;

        Account client = TestDataFactory.createAccount();

        Account venue = TestDataFactory.createVenue();
        insert venue;

        Campaign event = TestDataFactory.createEvent();
        insert event;

        Zone_Types__c zoneType = TestDataFactory.createZoneType();
        insert zoneType;

        Contract masterContract = TestDataFactory.createMasterContract(client.Id, context.Id);
        insert masterContract;

        Contract subContract = TestDataFactory.createSubContract(client.Id, masterContract.Id, context.Id);
        insert subContract;

        ContractAssociation__c contrAs = TestDataFactory.createFullFilledContractAssociation(context.Id, subContract.Id, client.Id, venue.Id, event.Id, zoneType.Id);
        insert contrAs;

        Order sale = TestDataFactory.createSale(client.Id, null, event.Id, context.Id, venue.Id, zoneType.Name);
        sale.OwnerId = FIN_GroupSelector.getGroupByDeveloperName(Constants.UNCLASSIFIED_QUEUE_US).Id;
        insert sale;

        FIN_Payment__c payment = TestDataFactory.createPayment(null, null);

        FIN_PaymentDistribution__c paymentDis = TestDataFactory.createPaymentDistributionForReclas(null, null, null);
        paymentDis.FIN_TransactionId__c = 'Transaction';
        paymentDis.FIN_PaymentTransactionId__c = 'PaymentTransaction';
        paymentDis.FIN_ContextName__c = context.Id;
        paymentDis.OwnerId = FIN_GroupSelector.getGroupByDeveloperName(Constants.UNCLASSIFIED_QUEUE_US).Id;
        insert paymentDis;
    }

    /**
     * @method      classByContextCLientVenueEventZoneTest
     * @description Tests, that sales, payment and payment distributions should be
     *              mapped to Subcontract, if Context, Client, Venue,
     *              Event and Zone match
     * @author      Ivan Liolia - 2022-04-11
     */
    @isTest
    static void classByContextCLientVenueEventZoneTest() {
        Order oldSale = [   SELECT Id
                            ,      ContractId
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual(null, oldSale.ContractId, 'Sale should not have a related contract');

        List<FIN_Context__c> finContexts = FIN_ContextSelector.getAllActiveContexts();

        Test.startTest();
            FIN_ClassifyRecordsBatch recordsBatch = new FIN_ClassifyRecordsBatch(Constants.sObjectToFieldsMap.get(sObjectTypeName), sObjectTypeName, fieldsToGet + Constants.fieldsToGetMap.get(sObjectTypeName), finContexts);
            Database.executeBatch(recordsBatch);
        Test.stopTest();

        Order classifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('SubContract', classifiedSale.Contract.Name, 'Sale was not mapped to SubContract Context, Client, Venue, Event and ZoneType');
    }

    /**
     * @method      classByContextCLientEventZoneTest
     * @description Tests, that sales, payment and payment distributions should be
     *              mapped to Subcontract, if Context, Client, Even,
     *              Zone match
     * @author      Ivan Liolia - 2022-04-11
     */
    @isTest
    static void classByContextCLientEventZoneTest() {
        Order oldSale = [   SELECT Id
                            ,      ContractId
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual(null, oldSale.ContractId, 'Sale should not have a related contract');

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_Venue__c = null;
        update contrAs;

        List<FIN_Context__c> finContexts = FIN_ContextSelector.getAllActiveContexts();

        Test.startTest();
            FIN_ClassifyRecordsBatch recordsBatch = new FIN_ClassifyRecordsBatch(Constants.sObjectToFieldsMap.get(sObjectTypeName), sObjectTypeName, fieldsToGet + Constants.fieldsToGetMap.get(sObjectTypeName), finContexts);
            Database.executeBatch(recordsBatch);
        Test.stopTest();

        Order classifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('SubContract', classifiedSale.Contract.Name, 'Sale was not mapped to SubContract Context, Client, Event, Zone');
    }

    /**
     * @method      classByContextCLientVenueZoneTest
     * @description Tests, that sales, payment and payment distributions should be
     *              mapped to Subcontract, if Context, Client, Venue,
     *              Zone match
     * @author      Ivan Liolia - 2022-04-11
     */
    @isTest
    static void classByContextCLientVenueZoneTest() {
        Order oldSale = [   SELECT Id
                            ,      ContractId
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual(null, oldSale.ContractId, 'Sale should not have a related contract');

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_AXS_Event__c = null;
        update contrAs;

        List<FIN_Context__c> finContexts = FIN_ContextSelector.getAllActiveContexts();

        Test.startTest();
            FIN_ClassifyRecordsBatch recordsBatch = new FIN_ClassifyRecordsBatch(Constants.sObjectToFieldsMap.get(sObjectTypeName), sObjectTypeName, fieldsToGet + Constants.fieldsToGetMap.get(sObjectTypeName), finContexts);
            Database.executeBatch(recordsBatch);
        Test.stopTest();

        Order classifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('SubContract', classifiedSale.Contract.Name, 'Sale was not mapped to SubContract Context, Client, Venue, Zone');
    }

    /**
     * @method      classByContextCLientVenueEventTest
     * @description Tests, that sales, payment and payment distributions should be
     *              mapped to Subcontract, if Context, Client, Venue,
     *              Event match
     * @author      Ivan Liolia - 2022-04-11
     */
    @isTest
    static void classByContextCLientVenueEventTest() {
        Order oldSale = [   SELECT Id
                            ,      ContractId
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual(null, oldSale.ContractId, 'Sale should not have a related contract');

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_Event_Zone__c = null;
        update contrAs;

        List<FIN_Context__c> finContexts = FIN_ContextSelector.getAllActiveContexts();

        Test.startTest();
            FIN_ClassifyRecordsBatch recordsBatch = new FIN_ClassifyRecordsBatch(Constants.sObjectToFieldsMap.get(sObjectTypeName), sObjectTypeName, fieldsToGet + Constants.fieldsToGetMap.get(sObjectTypeName), finContexts);
            Database.executeBatch(recordsBatch);
        Test.stopTest();

        Order classifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('SubContract', classifiedSale.Contract.Name, 'Sale was not mapped to SubContract Context, Client, Venue, Event');
    }

    /**
     * @method      classByContextCLientVenueTest
     * @description Tests, that sales, payment and payment distributions should be
     *              mapped to Subcontract, if Context, Client, Venue match
     * @author      Ivan Liolia - 2022-04-11
     */
    @isTest
    static void classByContextCLientVenueTest() {
        Order oldSale = [   SELECT Id
                            ,      ContractId
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual(null, oldSale.ContractId, 'Sale should not have a related contract');

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_Event_Zone__c = null;
        contrAs.FIN_AXS_Event__c = null;
        update contrAs;

        List<FIN_Context__c> finContexts = FIN_ContextSelector.getAllActiveContexts();

        Test.startTest();
            FIN_ClassifyRecordsBatch recordsBatch = new FIN_ClassifyRecordsBatch(Constants.sObjectToFieldsMap.get(sObjectTypeName), sObjectTypeName, fieldsToGet + Constants.fieldsToGetMap.get(sObjectTypeName), finContexts);
            Database.executeBatch(recordsBatch);
        Test.stopTest();

        Order classifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('SubContract', classifiedSale.Contract.Name, 'Sale was not mapped to SubContract Context, Client, Venue');
    }

    /**
     * @method      classByContextCLientEventTest
     * @description Tests, that sales, payment and payment distributions should be
     *              mapped to Subcontract, if Context, Client, Event match
     * @author      Ivan Liolia - 2022-04-11
     */
    @isTest
    static void classByContextCLientEventTest() {
        Order oldSale = [   SELECT Id
                            ,      ContractId
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual(null, oldSale.ContractId, 'Sale should not have a related contract');

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_Event_Zone__c = null;
        contrAs.FIN_Venue__c = null;
        update contrAs;

        List<FIN_Context__c> finContexts = FIN_ContextSelector.getAllActiveContexts();

        Test.startTest();
            FIN_ClassifyRecordsBatch recordsBatch = new FIN_ClassifyRecordsBatch(Constants.sObjectToFieldsMap.get(sObjectTypeName), sObjectTypeName, fieldsToGet + Constants.fieldsToGetMap.get(sObjectTypeName), finContexts);
            Database.executeBatch(recordsBatch);
        Test.stopTest();

        Order classifiedSale = [  SELECT Id
                                    ,      Contract.Name
                                    ,      Contract.FIN_Context__c
                                    FROM   Order];

        Assert.areEqual('SubContract', classifiedSale.Contract.Name, 'Sale was not mapped to SubContract Context, Client, Event');
    }

    /**
     * @method      classByContextCLientZoneTest
     * @description Tests, that sales, payment and payment distributions should be
     *              mapped to Subcontract, if Context, Client, Zone match
     * @author      Ivan Liolia - 2022-04-11
     */
    @isTest
    static void classByContextCLientZoneTest() {
        Order oldSale = [   SELECT Id
                            ,      ContractId
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual(null, oldSale.ContractId, 'Sale should not have a related contract');

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_AXS_Event__c = null;
        contrAs.FIN_Venue__c = null;
        update contrAs;

        List<FIN_Context__c> finContexts = FIN_ContextSelector.getAllActiveContexts();

        Test.startTest();
            FIN_ClassifyRecordsBatch recordsBatch = new FIN_ClassifyRecordsBatch(Constants.sObjectToFieldsMap.get(sObjectTypeName), sObjectTypeName, fieldsToGet + Constants.fieldsToGetMap.get(sObjectTypeName), finContexts);
            Database.executeBatch(recordsBatch);
        Test.stopTest();

        Order classifiedSale = [SELECT Id
                                ,      Contract.Name
                                ,      Contract.FIN_Context__c
                                FROM   Order];

        Assert.areEqual('SubContract', classifiedSale.Contract.Name, 'Sale was not mapped to SubContract Context, Client, Zone');
    }

    /**
     * @method      classByContextCLientTest
     * @description Tests, that sales, payment and payment distributions should be
     *              mapped to Subcontract, if Context, Client match
     * @author      Ivan Liolia - 2022-04-11
     */
    @isTest
    static void classByContextCLientTest() {
        Order oldSale = [   SELECT Id
                            ,      ContractId
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual(null, oldSale.ContractId, 'Sale should not have a related contract');

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_AXS_Event__c = null;
        contrAs.FIN_Venue__c = null;
        contrAs.FIN_Event_Zone__c = null;
        update contrAs;

        List<FIN_Context__c> finContexts = FIN_ContextSelector.getAllActiveContexts();

        Test.startTest();
            FIN_ClassifyRecordsBatch recordsBatch = new FIN_ClassifyRecordsBatch(Constants.sObjectToFieldsMap.get(sObjectTypeName), sObjectTypeName, fieldsToGet + Constants.fieldsToGetMap.get(sObjectTypeName), finContexts);
            Database.executeBatch(recordsBatch);
        Test.stopTest();

        Order classifiedSale = [SELECT Id
                                ,      Contract.Name
                                ,      Contract.FIN_Context__c
                                FROM   Order];

        Assert.areEqual('SubContract', classifiedSale.Contract.Name, 'Sale was not mapped to SubContract Context, Client');
    }

    /**
     * @method      classWhenNoMatchWithFilledClientAndContextTest
     * @description Tests, that sales, payment and payment distributions should not be
     *              mapped if no match when CLient and Context is Not Empty
     * @author      Ivan Liolia - 2022-04-11
     */
    @isTest
    static void classWhenNoMatchWithFilledClientAndContextTest() {
        Order oldSale = [   SELECT Id
                            ,      ContractId
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];

        Assert.areEqual(null, oldSale.ContractId, 'Sale should not have a related contract');

        Account newClient = TestDataFactory.createAccount();

        ContractAssociation__c contrAs = [  SELECT Id
                                            ,      FIN_Event_Zone__c
                                            FROM   ContractAssociation__c];
        contrAs.FIN_Event_Zone__c = null;
        contrAs.FIN_AXS_Event__c = null;
        contrAs.FIN_Venue__c = null;
        contrAs.Client__c = newClient.Id;
        update contrAs;

        List<FIN_Context__c> finContexts = FIN_ContextSelector.getAllActiveContexts();

        Test.startTest();
            FIN_ClassifyRecordsBatch recordsBatch = new FIN_ClassifyRecordsBatch(Constants.sObjectToFieldsMap.get(sObjectTypeName), sObjectTypeName, fieldsToGet + Constants.fieldsToGetMap.get(sObjectTypeName), finContexts);
            Database.executeBatch(recordsBatch);
        Test.stopTest();

        Order classifiedSale = [SELECT Id
                                ,      Contract.Name
                                ,      Contract.FIN_Context__c
                                FROM   Order];

        Assert.areEqual(null, classifiedSale.Contract.Name, 'Sale should not be mapped to any Contract');
    }

    /**
     * @method      classByContextCLientVenueEventZoneLogRecordTest
     * @description Tests, that sales, payment and payment distributions should be
     *              mapped to Subcontract, if Context, Client, Venue,
     *              Event and Zone match started from SystemDataLog record
     * @author      Ivan Liolia - 2022-04-11
     */
    @isTest
    static void classByContextCLientVenueEventZoneLogRecordTest() {
        FIN_SystemDataLoadLog__c sysDataLog = TestDataFactory.createSystemDataLog('Sales');
        insert sysDataLog;

        Order oldSale = [   SELECT Id
                            ,      ContractId
                            ,      Contract.Name
                            ,      Contract.FIN_Context__c
                            FROM   Order];
        oldSale.FIN_SystemDataLoadLog__c = sysDataLog.Id;
        update oldSale;

        List<FIN_Context__c> finContexts = FIN_ContextSelector.getAllActiveContexts();

        Test.startTest();
            FIN_ClassifyRecordsBatch recordsBatch = new FIN_ClassifyRecordsBatch(Constants.sObjectToFieldsMap.get(sObjectTypeName), sObjectTypeName, fieldsToGet + Constants.fieldsToGetMap.get(sObjectTypeName), sysDataLog, finContexts);
            Database.executeBatch(recordsBatch);
        Test.stopTest();

        Order classifiedSale = [SELECT Id
                                ,      Contract.Name
                                ,      Contract.FIN_Context__c
                                FROM   Order];

        Assert.areEqual('SubContract', classifiedSale.Contract.Name, 'Sale was not mapped to SubContract Context, Client, Venue, Event and ZoneType');
    }

    /**
     * @method      classifyPaymentTest
     * @description Tests, that payments mapped to correct Sale and Contract
     * @author      Ivan Liolia - 2022-04-11
     */
    @isTest
    static void classifyPaymentTest() {
        Order sale = [  SELECT Id
                        ,      FIN_OrderContext__c
                        FROM   Order];

        sale.ContractId = [ SELECT Id
                            FROM   Contract
                            WHERE  Name = 'SubContract'].Id;

        update sale;

        FIN_Payment__c payment = [  SELECT Id
                                    FROM   FIN_Payment__c
                                    LIMIT 1];
        payment.OwnerId = FIN_GroupSelector.getGroupByDeveloperName(Constants.UNCLASSIFIED_QUEUE_US).Id;
        payment.FIN_Context__c = sale.FIN_OrderContext__c;

        update payment;

        List<FIN_Context__c> finContexts = FIN_ContextSelector.getAllActiveContexts();

        Test.startTest();
            sObjectTypeName = 'FIN_Payment__c';
            FIN_ClassifyRecordsBatch recordsBatch = new FIN_ClassifyRecordsBatch(Constants.sObjectToFieldsMap.get(sObjectTypeName), sObjectTypeName, fieldsToGet + Constants.fieldsToGetMap.get(sObjectTypeName), finContexts);
            Database.executeBatch(recordsBatch);
        Test.stopTest();

        FIN_Payment__c classifiedPayment = [SELECT Id
                                            ,      FIN_Order__c
                                            ,      Contract__r.Name
                                            FROM   FIN_Payment__c];

        Assert.areEqual(sale.Id, classifiedPayment.FIN_Order__c, 'Payment was not mapped to Sale');
        Assert.areEqual('SubContract', classifiedPayment.Contract__r.Name, 'Payment was not mapped to Contract');
    }

    /**
     * @method      classifyPaymentDistributionTest
     * @description Tests, that paymentDistributions mapped to correct Payment, Sale and Contract
     * @author      Ivan Liolia - 2022-04-11
     */
    @isTest
    static void classifyPaymentDistributionTest() {
        Order sale = [  SELECT Id
                        ,      FIN_OrderContext__c
                        FROM   Order];

        sale.ContractId = [ SELECT Id
                            FROM   Contract
                            WHERE  Name = 'SubContract'].Id;

        update sale;

        FIN_Payment__c payment = [  SELECT Id
                                    FROM   FIN_Payment__c
                                    LIMIT 1];
        payment.FIN_Order__c = sale.Id;
        payment.FIN_Context__c = sale.FIN_OrderContext__c;
        payment.FIN_PaymentTransactionId__c = 'PaymentTransaction';
        update payment;

        List<FIN_Context__c> finContexts = FIN_ContextSelector.getAllActiveContexts();

        Test.startTest();
            sObjectTypeName = 'FIN_PaymentDistribution__c';
            FIN_ClassifyRecordsBatch recordsBatch = new FIN_ClassifyRecordsBatch(Constants.sObjectToFieldsMap.get(sObjectTypeName), sObjectTypeName, fieldsToGet + Constants.fieldsToGetMap.get(sObjectTypeName), finContexts);
            Database.executeBatch(recordsBatch);
        Test.stopTest();

        FIN_PaymentDistribution__c classifiedPaymentDistr = [   SELECT Id
                                                                ,      FIN_Order_ID__c
                                                                ,      Contract__r.Name
                                                                ,      FIN_Payment__c
                                                                ,      OwnerId
                                                                FROM   FIN_PaymentDistribution__c];

        Assert.areEqual(sale.Id, classifiedPaymentDistr.FIN_Order_ID__c, 'Payment Distribution was not mapped to Sale');
        Assert.areEqual('SubContract', classifiedPaymentDistr.Contract__r.Name, 'Payment Distribution was not mapped to Contract');
        Assert.areEqual(payment.Id, classifiedPaymentDistr.FIN_Payment__c, 'Payment Distribution was not mapped to Payment');
    }
}