force-app/main/default/objects/FIN_AXSRuleCondition__c/FIN_AXSRuleCondition__c.object-meta.xml
<CustomObject>
    <label>AXS Rule Condition</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Rule Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AXS Rule Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_Object__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object__c</fullName>
    <description>AXSRuleEngine.object</description>
    <formula>TEXT(FIN_SortingRule__r.FIN_Object__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Object</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_Object_Attribute_Formula__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object_Attribute_Formula__c</fullName>
    <formula>Case(TEXT(FIN_RelatedObject__c) ,
&quot;Payment -&gt; Sales&quot; , $CustomMetadata.FIN_Object_and_Fields__mdt.Payment_Sales.Field_API_Name__c ,
&quot;Payment Distribution -&gt; Payment&quot; , $CustomMetadata.FIN_Object_and_Fields__mdt.Payment_Distribution_Payment.Field_API_Name__c ,
&quot;Payment Distribution -&gt; Sales&quot; , $CustomMetadata.FIN_Object_and_Fields__mdt.Payment_Distribution_Sales.Field_API_Name__c 
,&quot;&quot;) &amp;  TEXT(FIN_RelatedObjectAttribute__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Object Attribute_Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_Operator__c.field-meta.xml
<CustomField>
    <fullName>FIN_Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&lt;&gt;</fullName>
            </value>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_RelatedObjectAttribute__c.field-meta.xml
<CustomField>
    <fullName>FIN_RelatedObjectAttribute__c</fullName>
    <label>Related Object Attribute</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FIN_RelatedObject__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Name</fullName>
            </value>
            <value>
                <fullName>FIN_PaymentContextID__c</fullName>
                <label>(Payment) Context ID</label>
            </value>
            <value>
                <fullName>FIN_PaymentDepositDate__c</fullName>
                <label>Deposit Date</label>
            </value>
            <value>
                <fullName>FIN_PaymentOutlet__c</fullName>
                <label>(Payment) Outlet</label>
            </value>
            <value>
                <fullName>FIN_PaymentAmount__c</fullName>
                <label>Payment Amount</label>
            </value>
            <value>
                <fullName>FIN_PaymentDate__c</fullName>
                <label>Payment Date</label>
            </value>
            <value>
                <fullName>FIN_PaymentName__c</fullName>
                <label>Payment Name</label>
            </value>
            <value>
                <fullName>FIN_PaymentPlanName__c</fullName>
                <label>Payment Plan Name</label>
            </value>
            <value>
                <fullName>FIN_PaymentRemark__c</fullName>
                <label>(Payment) Remark</label>
            </value>
            <value>
                <fullName>FIN_PaymentTransactionId__c</fullName>
                <label>Transaction Id</label>
            </value>
            <value>
                <fullName>Account Name</fullName>
            </value>
            <value>
                <fullName>Account Number</fullName>
            </value>
            <value>
                <fullName>Account Source</fullName>
            </value>
            <value>
                <fullName>FIN_ClientID__c</fullName>
                <label>Client ID</label>
            </value>
            <value>
                <fullName>Entity ID</fullName>
            </value>
            <value>
                <fullName>Legal Name</fullName>
            </value>
            <value>
                <fullName>Region</fullName>
            </value>
            <value>
                <fullName>Type</fullName>
            </value>
            <value>
                <fullName>Venue ID</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Code</fullName>
            </value>
            <value>
                <fullName>Description</fullName>
            </value>
            <value>
                <fullName>End Date</fullName>
            </value>
            <value>
                <fullName>Start Date</fullName>
            </value>
            <value>
                <fullName>Status</fullName>
            </value>
            <value>
                <fullName>FIN_PaymentContext__c</fullName>
                <label>Context</label>
            </value>
            <value>
                <fullName>Current Schema</fullName>
            </value>
            <value>
                <fullName>Short Name</fullName>
            </value>
            <value>
                <fullName>FIN_AdjustmentAmount__c</fullName>
                <label>Adjustment Amount</label>
            </value>
            <value>
                <fullName>FIN_Channel__c</fullName>
                <label>Channel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_SortingRule__c.field-meta.xml
<CustomField>
    <fullName>FIN_SortingRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AXS Rule Engine</label>
    <referenceTo>FIN_AXSRuleEngine__c</referenceTo>
    <relationshipLabel>AXS Rule Conditions</relationshipLabel>
    <relationshipName>AXS_Rule_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_Value__c.field-meta.xml
<CustomField>
    <fullName>FIN_Value__c</fullName>
    <label>Value</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/selectors/FIN_AXSRuleConditonSelector.cls
public with sharing class FIN_AXSRuleConditonSelector {
    public static List<FIN_AXSRuleCondition__c> getRuleConditionsByEnginesIds(List<Id> ruleEngineIds) {
        return [SELECT Id, FIN_RelatedObjectAttribute__c, FIN_Operator__c, FIN_Value__c, FIN_SortingRule__c, FIN_Object_Attribute_Formula__c, FIN_Object__c
                    FROM FIN_AXSRuleCondition__c
                    WHERE FIN_SortingRule__c IN :ruleEngineIds];
    }
}