force-app/main/default/objects/FIN_AXSRuleCondition__c/FIN_AXSRuleCondition__c.object-meta.xml
<CustomObject>
    <label>AXS Rule Condition</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Rule Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AXS Rule Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_Object__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object__c</fullName>
    <description>AXSRuleEngine.object</description>
    <formula>TEXT(FIN_SortingRule__r.FIN_Object__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Object</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_ObjectAttribute__c.field-meta.xml
<CustomField>
    <fullName>FIN_ObjectAttribute__c</fullName>
    <label>Object Attribute</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FIN_Object__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Processed_yn</fullName>
            </value>
            <value>
                <fullName>action_date</fullName>
            </value>
            <value>
                <fullName>channel</fullName>
            </value>
            <value>
                <fullName>client</fullName>
            </value>
            <value>
                <fullName>client_id</fullName>
            </value>
            <value>
                <fullName>client_name</fullName>
            </value>
            <value>
                <fullName>component_name</fullName>
            </value>
            <value>
                <fullName>context_id</fullName>
            </value>
            <value>
                <fullName>context_name</fullName>
            </value>
            <value>
                <fullName>currency</fullName>
            </value>
            <value>
                <fullName>current_paid_amount</fullName>
            </value>
            <value>
                <fullName>customer_account_num</fullName>
            </value>
            <value>
                <fullName>customer_id</fullName>
            </value>
            <value>
                <fullName>deposit_date</fullName>
            </value>
            <value>
                <fullName>distribution_amount</fullName>
            </value>
            <value>
                <fullName>distribution_amount_net_tax_amount</fullName>
            </value>
            <value>
                <fullName>distribution_amount_tax_amount</fullName>
            </value>
            <value>
                <fullName>distribution_amount_tax_included</fullName>
            </value>
            <value>
                <fullName>distribution_date</fullName>
            </value>
            <value>
                <fullName>entity</fullName>
            </value>
            <value>
                <fullName>entity_id</fullName>
            </value>
            <value>
                <fullName>entity_name</fullName>
            </value>
            <value>
                <fullName>event_build_date</fullName>
            </value>
            <value>
                <fullName>event_description</fullName>
            </value>
            <value>
                <fullName>event_end_date</fullName>
            </value>
            <value>
                <fullName>event_id</fullName>
            </value>
            <value>
                <fullName>event_lookup</fullName>
            </value>
            <value>
                <fullName>event_name</fullName>
            </value>
            <value>
                <fullName>event_start_date</fullName>
            </value>
            <value>
                <fullName>event_zone</fullName>
            </value>
            <value>
                <fullName>region</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_RelatedObject__c.field-meta.xml
<CustomField>
    <fullName>FIN_RelatedObject__c</fullName>
    <label>Related Object</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FIN_Object__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>FIN_PaymentDistribution__c</fullName>
                <label>Payment Distribution --&gt; Payment Distribution</label>
            </value>
            <value>
                <fullName>Payment Distribution -&gt; Payment</fullName>
            </value>
            <value>
                <fullName>Payment Distribution -&gt; Sales</fullName>
            </value>
            <value>
                <fullName>FIN_Payment__c</fullName>
                <label>Payment -&gt; Payment</label>
            </value>
            <value>
                <fullName>Payment -&gt; Sales</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
                <label>Sales -&gt; Sales</label>
            </value>
            <value>
                <fullName>SBQQ__ContractedPrice__c</fullName>
                <label>Library Association</label>
            </value>
            <value>
                <fullName>Sales Transactions</fullName>
                <label>Sales Transaction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_SortingRule__c.field-meta.xml
<CustomField>
    <fullName>FIN_SortingRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AXS Rule Engine</label>
    <referenceTo>FIN_AXSRuleEngine__c</referenceTo>
    <relationshipLabel>AXS Rule Conditions</relationshipLabel>
    <relationshipName>AXS_Rule_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/recordTypes/AXS_Rule_Condition_Enrichment_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>AXS_Rule_Condition_Enrichment_Record_Type</fullName>
    <active>true</active>
    <label>AXS Rule Condition Enrichment Record Type</label>
</RecordType>

force-app/main/default/objects/FIN_AXSRuleEngine__c/FIN_AXSRuleEngine__c.object-meta.xml
<CustomObject>
    <label>AXS Rule Engine</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AXS Rule Engines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_AXSRuleEngine__c/fields/FIN_AssociatedContract__c.field-meta.xml
<CustomField>
    <fullName>FIN_AssociatedContract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>AXS Rule Engines</relationshipLabel>
    <relationshipName>AXS_Rule_Engines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleEngine__c/fields/FIN_Object__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
                <default>true</default>
                <label>Sales</label>
            </value>
            <value>
                <fullName>Sales Transactions</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Payment Distribution</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
                <isActive>false</isActive>
                <label>Contract</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleEngine__c/fields/FIN_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FIN_Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleEngine__c/fields/FIN_Type__c.field-meta.xml
<CustomField>
    <fullName>FIN_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Statistical</fullName>
            </value>
            <value>
                <fullName>Contract-Mapping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleEngine__c/recordTypes/EnrichmentTagging.recordType-meta.xml
<RecordType>
    <fullName>EnrichmentTagging</fullName>
    <active>true</active>
    <description>Financial &amp; Statistical</description>
    <label>Enrichment Tagging</label>
</RecordType>

force-app/main/default/classes/testClasses/FIN_AXSRuleConditionTest.cls
@IsTest
public with sharing class FIN_AXSRuleConditionTest {
    @IsTest
    static void testBeforeInsert() {
        Account acc = TestDataFactory.createAccount();
        Contract parentContract = TestDataFactory.createParentContract(acc.Id);

        FIN_AXSRuleEngine__c sr = new FIN_AXSRuleEngine__c(
            RecordTypeId = Schema.SObjectType.FIN_AXSRuleEngine__c.getRecordTypeInfosByDeveloperName()
                .get('EnrichmentTagging').getRecordTypeId(),
            FIN_Object__c = 'Sales',
            FIN_AssociatedContract__c = parentContract.Id,
            FIN_Start_Date__c = Date.today(),
                FIN_Type__c = 'Financial'
        );
        insert sr;


        FIN_AXSRuleCondition__c arc = new FIN_AXSRuleCondition__c(
            FIN_SortingRule__c = sr.Id,
            RecordTypeId = Schema.SObjectType.FIN_AXSRuleCondition__c.getRecordTypeInfosByDeveloperName()
                .get('AXS_Rule_Condition_Enrichment_Record_Type').getRecordTypeId(),
            FIN_Object__c = 'Sales',
            FIN_RelatedObject__c = 'Order',
            FIN_ObjectAttribute__c = 'region'
        );

//        Test.startTest();
        insert arc;
//        Test.stopTest();

        FIN_AXSRuleCondition__c resultARC = [
            SELECT Id, FIN_Object__c
            FROM FIN_AXSRuleCondition__c
            LIMIT 1
        ];

        Assert.areEqual(sr.FIN_Object__c, resultARC.FIN_Object__c);
    }
}