force-app/main/default/objects/FIN_AXSRuleCondition__c/FIN_AXSRuleCondition__c.object-meta.xml
<CustomObject>
    <label>AXS Rule Condition</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Rule Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AXS Rule Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_Object__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object__c</fullName>
    <description>AXSRuleEngine.object</description>
    <formula>TEXT(FIN_SortingRule__r.FIN_Object__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Object</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleCondition__c/fields/FIN_SortingRule__c.field-meta.xml
<CustomField>
    <fullName>FIN_SortingRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AXS Rule Engine</label>
    <referenceTo>FIN_AXSRuleEngine__c</referenceTo>
    <relationshipLabel>AXS Rule Conditions</relationshipLabel>
    <relationshipName>AXS_Rule_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleEngine__c/FIN_AXSRuleEngine__c.object-meta.xml
<CustomObject>
    <label>AXS Rule Engine</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AXS Rule Engines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_AXSRuleEngine__c/fields/FIN_Object__c.field-meta.xml
<CustomField>
    <fullName>FIN_Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
                <default>true</default>
                <label>Sales</label>
            </value>
            <value>
                <fullName>Sales Transactions</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Payment Distribution</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
                <isActive>false</isActive>
                <label>Contract</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/triggerHandlers/FIN_AXSRuleConditionTriggerHandler.cls
public with sharing class FIN_AXSRuleConditionTriggerHandler extends TriggerHandler {
    public override void beforeInsert() {
        Set<Id> setlookup = new Set<Id>();
        for (FIN_AXSRuleCondition__c ruleCondition : (List<FIN_AXSRuleCondition__c>) this.triggerNew) {
            setlookup.add(ruleCondition.FIN_SortingRule__c);
        }

        Map<Id, FIN_AXSRuleEngine__c> maplookupObject = new Map<Id, FIN_AXSRuleEngine__c>([
            SELECT Id, FIN_Object__c
            FROM FIN_AXSRuleEngine__c
            WHERE Id IN :setlookup
        ]);

        for (FIN_AXSRuleCondition__c ruleCondition : (List<FIN_AXSRuleCondition__c>) this.triggerNew) {
            ruleCondition.FIN_Object__c = maplookupObject.get(ruleCondition.FIN_SortingRule__c).FIN_Object__c;
        }
    }
}