force-app/main/default/objects/FIN_Payee__c/FIN_Payee__c.object-meta.xml
<CustomObject>
    <label>Remittance Account</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Payee</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remittance Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_DistributionAmountNetofTaxAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmountNetofTaxAmount__c</fullName>
    <label>Distribution Amount - Net of Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RemittanceSchedule__c/FIN_RemittanceSchedule__c.object-meta.xml
<CustomObject>
    <label>Remittance Schedule</label>
    <nameField>
        <displayFormat>RS-{0000000000}</displayFormat>
        <label>Remittance Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remittance Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SettlementItem__c/FIN_SettlementItem__c.object-meta.xml
<CustomObject>
    <label>Settlement Item</label>
    <nameField>
        <displayFormat>SI-{0000000000}</displayFormat>
        <label>Settlement Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SettlementItem__c/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Settlement Items</relationshipLabel>
    <relationshipName>Settlement_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_SettlementSchedule__c/FIN_SettlementSchedule__c.object-meta.xml
<CustomObject>
    <label>Settlement Schedule</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>Settlement Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlement Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SettlementSchedule__c/fields/FIN_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SettlementInProgress</fullName>
                <default>true</default>
                <label>Settlement In Progress</label>
            </value>
            <value>
                <fullName>Remittance</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance_Payout__c/Remittance_Payout__c.object-meta.xml
<CustomObject>
    <label>Remittance Payout</label>
    <nameField>
        <displayFormat>RP-{0000000000}</displayFormat>
        <label>Remittance Payout Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remittance Payouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance_Payout__c/fields/FIN_SettlementSchedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_SettlementSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Settlement Process</label>
    <referenceTo>FIN_SettlementSchedule__c</referenceTo>
    <relationshipLabel>Remittance Payouts</relationshipLabel>
    <relationshipName>Remittance_Payouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/SBQQ__ContractedPrice__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__ContractedPriceHelp</customHelpPage>
    <description>Contracted (negotiated) price for a product for a given customer account.</description>
    <label>Contracted Price</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Contracted Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracted Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Fee_and_Component__c.field-meta.xml
<CustomField>
    <fullName>FIN_Fee_and_Component__c</fullName>
    <label>Fee and Component</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AXS Fee</fullName>
            </value>
            <value>
                <fullName>AXS Payment Fee</fullName>
            </value>
            <value>
                <fullName>Venue Facility Fee</fullName>
            </value>
            <value>
                <fullName>Venue Fee</fullName>
            </value>
            <value>
                <fullName>Venue Lift</fullName>
            </value>
            <value>
                <fullName>Venue Uplift</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Payee__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remittance Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FIN_Payee__c.FIN_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FIN_Payee__c</referenceTo>
    <relationshipLabel>Library Associations</relationshipLabel>
    <relationshipName>Library_Associations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Status__c</fullName>
    <formula>IF (
    ISBLANK(SBQQ__EffectiveDate__c) &amp;&amp; ISBLANK(SBQQ__ExpirationDate__c),
    IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;,
    IF (
        NOT(ISBLANK(SBQQ__EffectiveDate__c)) &amp;&amp; NOT(ISBLANK(SBQQ__ExpirationDate__c)) &amp;&amp;
        TODAY()&lt;= SBQQ__ExpirationDate__c &amp;&amp; TODAY()&gt;= SBQQ__EffectiveDate__c,
        IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;,
        IF (
            NOT(ISBLANK(SBQQ__EffectiveDate__c)) &amp;&amp; ISBLANK(SBQQ__ExpirationDate__c) &amp;&amp; TODAY()&gt;= SBQQ__EffectiveDate__c,
            IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;,
            IF (
                NOT(ISBLANK(SBQQ__ExpirationDate__c)) &amp;&amp; ISBLANK(SBQQ__EffectiveDate__c) &amp;&amp; TODAY()&lt;= SBQQ__ExpirationDate__c,
                IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;, IMAGE(&apos;/img/samples/flag_red.gif&apos;, &apos;red&apos;) + &apos; Inactive&apos;)
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testClasses/RemittanceDataControllerTest.cls
@IsTest
private class RemittanceDataControllerTest {
    @TestSetup
    static void setUp() {
        Account acc = TestDataFactory.createAccount();
        Contract parentContract = TestDataFactory.createParentContract(acc.Id);
        Contract contract = TestDataFactory.createContract(acc.Id, parentContract.Id);
        Product2 pro = TestDataFactory.createProduct2();
        PricebookEntry standardPriceEntry = TestDataFactory.createPricebookEntry(pro.Id);
        Order ord = TestDataFactory.createTestOrderWithContract(acc.Id, contract.Id);
        FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id, contract.Id);
        FIN_PaymentDistribution__c paymentdist = TestDataFactory.createPaymentDistribution(payment.Id, null, contract.Id);
        paymentdist.FIN_DistributionAmountNetofTaxAmount__c = 10;
        update paymentdist;

        FIN_SettlementSchedule__c settlementSchedule = TestDataFactory.createSettlementSchedule(contract.Id);
        settlementSchedule.FIN_Status__c = 'Remittance';
        update settlementSchedule;

        SBQQ__ContractedPrice__c library = TestDataFactory.createLibraryAssociation(acc.Id);
        library.FIN_Fee_and_Component__c = 'Venue Fee';
        update library;

        FIN_SettlementItem__c settlementItem = TestDataFactory.createSettlementItem(contract.Id, settlementSchedule.Id, paymentdist.Id);
        Remittance_Payout__c rp = TestDataFactory.createRemittancePayout(settlementSchedule.Id, contract.Id);
    }

    @IsTest
    public static void testFilteredRPs() {
        List<FIN_SettlementSchedule__c> settlementSchedules = [
            SELECT Id
            FROM FIN_SettlementSchedule__c
        ];

        List<Remittance_Payout__c> remittancePayouts = RemittanceDataController.getFilteredRPs(null, null, '', '', settlementSchedules[0].Id);

        Assert.areEqual(1, remittancePayouts.size());
    }

    @IsTest
    public static void testGetPayees() {
        List<FIN_Payee__c> payees = RemittanceDataController.getPayees(null);

        Assert.areEqual(1, payees.size());
    }

    @IsTest
    public static void testGetContracts() {
        List<Contract> contracts = RemittanceDataController.getContracts(null);

        Assert.areEqual(1, contracts.size());
    }

    @IsTest
    public static void testSSNums() {
        List<FIN_SettlementSchedule__c> settlementSchedules = RemittanceDataController.getSSNums(null);

        Assert.areEqual(1, settlementSchedules.size());
    }

    @IsTest
    public static void testCreateRI() {
        FIN_RemittanceSchedule__c remittanceSchedule = TestDataFactory.createRemittanceSchedule();
        List<Remittance_Payout__c> remittancePayouts = [
            SELECT Id
            FROM Remittance_Payout__c
        ];

        Integer riQty = RemittanceDataController.createRI(new List<Id>{
            remittancePayouts[0].Id
        }, remittanceSchedule.Id);

        Assert.areEqual(1, riQty);
    }
}