force-app/main/default/objects/FIN_Invoice__c/FIN_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Invoice__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
            <value>
                <fullName>Posted</fullName>
                <isActive>false</isActive>
                <label>Posted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testClasses/Fin_InvoiceExtControllerTests.cls
@isTest
private class Fin_InvoiceExtControllerTests {

    // testMethod static void testSubmit() {
    //     FIN_Invoice__c invoice= new FIN_Invoice__c();
    //     insert invoice;
        
    //     Test.startTest();
    //     Fin_InvoiceExtController con = new Fin_InvoiceExtController(new ApexPages.StandardController(invoice));
    //     con.onSubmit();
    //     invoice= [SELECT ApprovalStatus__c FROM FIN_Invoice__c WHERE Id = :invoice.Id LIMIT 1];
    //     Test.stopTest();
        
    //     System.assertEquals('Approved', invoice.ApprovalStatus__c );
    // }
    
    // testMethod static void testRecall() {
    //     FIN_Invoice__c invoice= new FIN_Invoice__c();
    //     insert invoice;
        
    //     Test.startTest();
    //     Fin_InvoiceExtController con = new Fin_InvoiceExtController (new ApexPages.StandardController(invoice));
    //     con.onRecall();
    //     invoice= [SELECT ApprovalStatus__c  FROM FIN_Invoice__c WHERE Id = :invoice.Id LIMIT 1];
    //     Test.stopTest();
        
    //     System.assertEquals('Recalled', invoice.ApprovalStatus__c );
    // }
}