force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Client__c.field-meta.xml
<CustomField>
    <fullName>FIN_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distribution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>FIN_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/FIN_RetroactiveAdjustment__c.object-meta.xml
<CustomObject>
    <label>Retroactive Adjustment</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Retroactive Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retroactive Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Account__c.field-meta.xml
<CustomField>
    <fullName>FIN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_ActionDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_ActionDate__c</fullName>
    <label>Action Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_Amount__c</fullName>
    <label>Ticket Component Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Contract__c.field-meta.xml
<CustomField>
    <fullName>FIN_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_CurrentPaidAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_CurrentPaidAmount__c</fullName>
    <label>Current paid amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_FeeGrossAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_FeeGrossAmount__c</fullName>
    <label>Fee gross amount</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_FeeNetAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_FeeNetAmount__c</fullName>
    <label>Fee net amount</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_FeeTaxAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_FeeTaxAmount__c</fullName>
    <label>Fee tax amount</label>
    <precision>17</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Gross_Amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_Gross_Amount__c</fullName>
    <label>Ticket Component Gross Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_MerchGrossAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_MerchGrossAmount__c</fullName>
    <label>Merch Gross Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_MerchNetAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_MerchNetAmount__c</fullName>
    <label>Merch Net Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_MerchTaxAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_MerchTaxAmount__c</fullName>
    <label>Merch Tax Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Order__c.field-meta.xml
<CustomField>
    <fullName>FIN_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>FIN_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Transactions</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Quantity__c.field-meta.xml
<CustomField>
    <fullName>FIN_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_Tax_Amount__c</fullName>
    <label>Ticket Component Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>FIN_UnitPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_CurrentPaidAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_CurrentPaidAmount__c</fullName>
    <label>Current paid amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_ActionDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_ActionDate__c</fullName>
    <label>Action Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_Amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_Amount__c</fullName>
    <label>Ticket Component Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_Client__c.field-meta.xml
<CustomField>
    <fullName>FIN_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products (Client)</relationshipLabel>
    <relationshipName>Order_Products4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_CurrentPaidAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_CurrentPaidAmount__c</fullName>
    <label>Current Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_FeeGrossAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_FeeGrossAmount__c</fullName>
    <label>Fee Gross Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_FeeNetAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_FeeNetAmount__c</fullName>
    <label>Fee Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_FeeTaxAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_FeeTaxAmount__c</fullName>
    <label>Fee Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_Gross_Amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_Gross_Amount__c</fullName>
    <label>Ticket Component Gross Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Sales Transactions</relationshipLabel>
    <relationshipName>Sales_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_MerchGrossAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_MerchGrossAmount__c</fullName>
    <label>Merch Gross Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_MerchNetAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_MerchNetAmount__c</fullName>
    <label>Merch Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_MerchTaxAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_MerchTaxAmount__c</fullName>
    <label>Merch Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_Missing_Library_Association__c.field-meta.xml
<CustomField>
    <fullName>FIN_Missing_Library_Association__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Missing Library Association</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_Quantity__c.field-meta.xml
<CustomField>
    <fullName>FIN_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_Tax_Amount__c</fullName>
    <label>Ticket Component Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/helpers/FIN_OrderItemHelper.cls
public with sharing class FIN_OrderItemHelper {
    public static void updateMissingLAField(List<OrderItem> orderItems) {
        for(OrderItem orderItem : orderItems) {
            orderItem.FIN_Missing_Library_Association__c = orderItem.FIN_LibraryAssociation__c != null ? false : true;
        }
    }

    public static void createRetroactiveAdjustment(List<OrderItem> orderItems, Map<Id, OrderItem> oldMap) {
        List<FIN_RetroactiveAdjustment__c> retroactiveAdjustments = new List<FIN_RetroactiveAdjustment__c>();
        Id orderItemRecordTypeId = Schema.SObjectType.FIN_RetroactiveAdjustment__c.getRecordTypeInfosByName().get('Order Product').getRecordTypeId();

        Map<String, String> orderItemRAMap = new Map<String, String>{
            'FIN_Client__c' => 'FIN_Account__c',
            'FIN_Region__c' => 'FIN_Region__c', 
            'FIN_ActionDate__c' => 'FIN_ActionDate__c',
            'SBQQ__Contract__c' => 'FIN_Contract__c',
            'FIN_PaymentDistribution__c' => 'FIN_PaymentDistribution__c',
            'Quantity' => 'FIN_Quantity__c',
            'FIN_Gross_Amount__c' => 'FIN_Gross_Amount__c',
            'FIN_Amount__c' => 'FIN_Amount__c',
            'FIN_Tax_Amount__c' => 'FIN_Tax_Amount__c',
            'FIN_FeeGrossAmount__c' => 'FIN_FeeGrossAmount__c',
            'FIN_FeeNetAmount__c' => 'FIN_FeeNetAmount__c',
            'FIN_FeeTaxAmount__c' => 'FIN_FeeTaxAmount__c',
            'FIN_MerchGrossAmount__c' => 'FIN_MerchGrossAmount__c',
            'FIN_MerchNetAmount__c' => 'FIN_MerchNetAmount__c',
            'FIN_MerchTaxAmount__c' => 'FIN_MerchTaxAmount__c',
            'FIN_CurrentPaidAmount__c' => 'FIN_CurrentPaidAmount__c',
            'UnitPrice' => 'FIN_UnitPrice__c'
        };

        for(OrderItem orderItem : orderItems) {
            OrderItem oldO = oldMap.get(orderItem.Id);
            Integer i=0;

            FIN_RetroactiveAdjustment__c newRetroactiveAdjustment = new FIN_RetroactiveAdjustment__c();
            newRetroactiveAdjustment.FIN_OrderProduct__c = orderItem.Id;
            newRetroactiveAdjustment.RecordTypeId = orderItemRecordTypeId;
            newRetroactiveAdjustment.FIN_Contract__c = orderItem.SBQQ__Contract__c;
            newRetroactiveAdjustment.FIN_Account__c = orderItem.FIN_Client__c;
            newRetroactiveAdjustment.FIN_Order__c = orderItem.OrderId;
            newRetroactiveAdjustment.FIN_PaymentDistribution__c = orderItem.FIN_PaymentDistribution__c;
            
            for(String str : orderItemRAMap.keyset()) {
                if(orderItem.get(str) != oldO.get(str)) {
                    newRetroactiveAdjustment.put(orderItemRAMap.get(str), orderItem.get(str));
                    i++;
                }
            }

            if(i != 0) {
                retroactiveAdjustments.add(newRetroactiveAdjustment);
            }
        }

        insert retroactiveAdjustments;
    }

}