force-app/main/default/objects/FIN_Context__c/FIN_Context__c.object-meta.xml
<CustomObject>
    <label>Context</label>
    <nameField>
        <label>Context Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contexts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Context__c/fields/FIN_Active__c.field-meta.xml
<CustomField>
    <fullName>FIN_Active__c</fullName>
    <formula>TODAY() &gt; FIN_StartDate__c
&amp;&amp;
TODAY() &lt; FIN_EndDate__c ||
ISNULL(FIN_EndDate__c)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_Fee_Category__c/FIN_Fee_Category__c.object-meta.xml
<CustomObject>
    <label>Fee Category</label>
    <nameField>
        <label>Fee Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ContractedPrice__c/SBQQ__ContractedPrice__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__ContractedPriceHelp</customHelpPage>
    <description>Contracted (negotiated) price for a product for a given customer account.</description>
    <label>Contracted Price</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Contracted Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracted Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/Association_Type__c.field-meta.xml
<CustomField>
    <fullName>Association_Type__c</fullName>
    <label>Association Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ticket</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Uplift</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Active__c.field-meta.xml
<CustomField>
    <fullName>FIN_Active__c</fullName>
    <formula>TODAY() &gt; SBQQ__EffectiveDate__c &amp;&amp;
TODAY() &lt; SBQQ__ExpirationDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Component_Number__c.field-meta.xml
<CustomField>
    <fullName>FIN_Component_Number__c</fullName>
    <inlineHelpText>Indicates what Number the Product Component is within a Context</inlineHelpText>
    <label>Component Key</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Library Associations</relationshipLabel>
    <relationshipName>Library_Associations_Context</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_ContextName__c.field-meta.xml
<CustomField>
    <fullName>FIN_ContextName__c</fullName>
    <formula>FIN_Context__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Context name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Fee_Category__c.field-meta.xml
<CustomField>
    <fullName>FIN_Fee_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Category</label>
    <referenceTo>FIN_Fee_Category__c</referenceTo>
    <relationshipLabel>Library Associations</relationshipLabel>
    <relationshipName>Library_Associations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_ProductName__c.field-meta.xml
<CustomField>
    <fullName>FIN_ProductName__c</fullName>
    <formula>SBQQ__Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/selectors/FIN_LibraryAssociationSelector.cls
public with sharing class FIN_LibraryAssociationSelector {
    public static List<SBQQ__ContractedPrice__c> getLibraryAssociationsForReclassificationByContextId(String contextId) {
        return [SELECT Id, FIN_ContextName__c, FIN_Context__c, FIN_Fee_Category__c, FIN_ProductName__c, Association_Type__c, FIN_Component_Number__c
        FROM SBQQ__ContractedPrice__c
        WHERE FIN_ContextName__c != NULL AND FIN_ProductName__c != NULL
            AND FIN_Context__c = :contextId AND FIN_Active__c = TRUE];
    }
}