force-app/main/default/objects/FIN_Context__c/FIN_Context__c.object-meta.xml
<CustomObject>
    <label>Context</label>
    <nameField>
        <label>Context Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contexts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Context__c/fields/FIN_Active__c.field-meta.xml
<CustomField>
    <fullName>FIN_Active__c</fullName>
    <formula>TODAY() &gt; FIN_StartDate__c
&amp;&amp;
TODAY() &lt; FIN_EndDate__c ||
ISNULL(FIN_EndDate__c)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_Fee_Category__c/FIN_Fee_Category__c.object-meta.xml
<CustomObject>
    <label>Fee Category</label>
    <nameField>
        <label>Fee Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ContractedPrice__c/SBQQ__ContractedPrice__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__ContractedPriceHelp</customHelpPage>
    <description>Contracted (negotiated) price for a product for a given customer account.</description>
    <label>Contracted Price</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Contracted Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracted Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/Association_Type__c.field-meta.xml
<CustomField>
    <fullName>Association_Type__c</fullName>
    <label>Association Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ticket</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Uplift</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Active__c.field-meta.xml
<CustomField>
    <fullName>FIN_Active__c</fullName>
    <formula>TODAY() &gt; SBQQ__EffectiveDate__c &amp;&amp;
TODAY() &lt; SBQQ__ExpirationDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Context__c.field-meta.xml
<CustomField>
    <fullName>FIN_Context__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Context</label>
    <referenceTo>FIN_Context__c</referenceTo>
    <relationshipLabel>Library Associations</relationshipLabel>
    <relationshipName>Library_Associations_Context</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_ContextName__c.field-meta.xml
<CustomField>
    <fullName>FIN_ContextName__c</fullName>
    <formula>FIN_Context__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Context name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_ContextNameforSearch__c.field-meta.xml
<CustomField>
    <fullName>FIN_ContextNameforSearch__c</fullName>
    <label>Context Name for Search</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Fee_Category__c.field-meta.xml
<CustomField>
    <fullName>FIN_Fee_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Category</label>
    <referenceTo>FIN_Fee_Category__c</referenceTo>
    <relationshipLabel>Library Associations</relationshipLabel>
    <relationshipName>Library_Associations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/recordTypes/FIN_Contracted_Fee.recordType-meta.xml
<RecordType>
    <fullName>FIN_Contracted_Fee</fullName>
    <active>true</active>
    <label>Contracted Fee</label>
</RecordType>

force-app/main/default/classes/helpers/FIN_LibraryAssociationHelper.cls
public with sharing class  FIN_LibraryAssociationHelper {
    public static final String ContractFeeRTID = Schema.getGlobalDescribe().get('SBQQ__ContractedPrice__c').getDescribe().getRecordTypeInfosByDeveloperName().get('FIN_Contracted_Fee').getRecordTypeId();
    public static void checkDuplicates(List<SBQQ__ContractedPrice__c> libraryAssociationList) {
        
        Set<Id> laIds = new Set<Id>();
        for(SBQQ__ContractedPrice__c libraryAssociation : libraryAssociationList) {
            laIds.add(libraryAssociation.Id);
        }

        List<SBQQ__ContractedPrice__c> allLA = [
            SELECT Id, FIN_Context__c, FIN_Active__c, SBQQ__Product__c, SBQQ__EffectiveDate__c, 
            Association_Type__c, RecordTypeId, FIN_Fee_Category__c
            FROM SBQQ__ContractedPrice__c
            WHERE FIN_Active__c = TRUE
            AND FIN_Context__c != NULL
            AND SBQQ__Product__c != NULL
            AND Association_Type__c != NULL
            AND Id NOT IN :laIds
        ];

        Map<LAComparingWrapper, SBQQ__ContractedPrice__c> laMap = new Map<LAComparingWrapper, SBQQ__ContractedPrice__c>();

        for (SBQQ__ContractedPrice__c la : allLA) {
            laMap.put(new LAComparingWrapper(la.FIN_Context__c, la.SBQQ__Product__c, String.valueOfGmt(la.SBQQ__EffectiveDate__c), la.Association_Type__c, la.RecordTypeId, la.FIN_Fee_Category__c), la);
        }

        System.debug('laMap'+laMap.keySet());
        for (SBQQ__ContractedPrice__c la : libraryAssociationList) {
            System.debug(la);
            if (laMap.containsKey(new LAComparingWrapper(la.FIN_Context__c, la.SBQQ__Product__c, String.valueOfGmt(la.SBQQ__EffectiveDate__c), la.Association_Type__c, la.RecordTypeId, la.FIN_Fee_Category__c))) {
                la.addError('It`s a duplicate');
            } else {
                la.FIN_ContextNameforSearch__c = la.FIN_ContextName__c;
            }
        }
    }

    public class LAComparingWrapper {
        private String contextId;
        private String productId;
        private String effectiveDate;
        private String associationType;
        private Id recordTypeId;
        private String feeCategory;

        public LAComparingWrapper(String contextId, String productId, String effectiveDate, String associationType, Id recordTypeId, String feeCategory) {
            this.contextId = contextId;
            this.productId = productId;
            this.effectiveDate = effectiveDate;
            this.associationType = associationType;
            this.recordTypeId = recordTypeId;
            this.feeCategory = feeCategory;
        }

        public Boolean equals(Object obj) {
            if (obj instanceof LAComparingWrapper) {
                LAComparingWrapper lacw = (LAComparingWrapper) obj;
                if(recordTypeId == ContractFeeRTID){
                    return this.contextId == lacw.contextId && this.feeCategory == lacw.feeCategory && this.effectiveDate == lacw.effectiveDate && this.associationType == lacw.associationType;
                }
                else{
                    return this.contextId == lacw.contextId && this.productId == lacw.productId && this.effectiveDate == lacw.effectiveDate && this.associationType == lacw.associationType;
                }
            }
            return false;
        }
    }
}