force-app/main/default/objects/ContractAssociation__c/ContractAssociation__c.object-meta.xml
<CustomObject>
    <label>Contract Association</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Contract Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/ContractAssociation__c.field-meta.xml
<CustomField>
    <fullName>ContractAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Association</label>
    <referenceTo>ContractAssociation__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/controllers/FIN_contractAssociationExtController.cls
public with sharing class FIN_contractAssociationExtController {
    private Id contractAssociationId;
    public FIN_contractAssociationExtController (ApexPages.StandardController stdController) {
        contractAssociationId = stdController.getId();
    }
    public PageReference onSubmit() {
        if (contractAssociationId != null) {
           
                SBAA.ApprovalAPI.submit(contractAssociationId, SBAA__Approval__c.contractAssociation__c);
           
        }
        return new PageReference('/' + contractAssociationId);
    }
    public PageReference onRecall() {
        if (contractAssociationId != null) {
            
                SBAA.ApprovalAPI.recall(contractAssociationId, SBAA__Approval__c.contractAssociation__c);
           
        }
        return new PageReference('/' + contractAssociationId);
    }
}