force-app/main/default/objects/FIN_AXSRuleEngine__c/FIN_AXSRuleEngine__c.object-meta.xml
<CustomObject>
    <label>AXS Rule Engine</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AXS Rule Engines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/FIN_AXS_Rule_Engine__c.field-meta.xml
<CustomField>
    <fullName>FIN_AXS_Rule_Engine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AXS Rule Engine</label>
    <referenceTo>FIN_AXSRuleEngine__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/invocable/FIN_SubmitForApprovalApexAction.cls
public class FIN_SubmitForApprovalApexAction{
  @InvocableMethod(label='Submit For Approval - Apex Action' description='Submit For Approval Apex Action for Order,Contract and Rule Engine')
  public static List<String> getAccountNames(List<ID> ids) {
    
    id firstrecordId= ids[0];

    Schema.SObjectType sobjectType = firstrecordId.getSObjectType();
    String sobjectName = sobjectType.getDescribe().getName();
    System.debug(sobjectName);
    
    for( id myid : ids){
    
        if (sobjectName =='Order'){    
                SBAA.ApprovalAPI.submit(myId, SBAA__Approval__c.Order__c);
         }else if (sobjectName == 'Contract'){
                SBAA.ApprovalAPI.submit(myId, SBAA__Approval__c.Contract__c);
         }else if ( sobjectName == 'FIN_AXSRuleEngine__c'){
                SBAA.ApprovalAPI.submit(myId, SBAA__Approval__c.FIN_AXS_Rule_Engine__c);
         }
     }        
    return null;
  }
}