force-app/main/default/objects/FIN_AXSRuleEngine__c/FIN_AXSRuleEngine__c.object-meta.xml
<CustomObject>
    <label>AXS Rule Engine</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AXS Rule Engines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_AXSRuleEngine__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleEngine__c/fields/FIN_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FIN_Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FIN_AXSRuleEngine__c/fields/FIN_Type__c.field-meta.xml
<CustomField>
    <fullName>FIN_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Statistical</fullName>
            </value>
            <value>
                <fullName>Contract-Mapping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testClasses/FIN_AXSRuleEngineExtControllerTests.cls
@isTest
private class FIN_AXSRuleEngineExtControllerTests {
//FIN_AXSRuleEngineExtControllerTests
    testMethod static void testSubmit() {
        FIN_AXSRuleEngine__c AXSRuleEngine= new FIN_AXSRuleEngine__c(
            FIN_Start_Date__c = Date.today(),
                FIN_Type__c = 'Financial'
        );
        insert AXSRuleEngine;
        
        Test.startTest();
        FIN_AXSRuleEngineExtController con = new FIN_AXSRuleEngineExtController(new ApexPages.StandardController(AXSRuleEngine));
        con.onSubmit();
        AXSRuleEngine= [SELECT ApprovalStatus__c FROM FIN_AXSRuleEngine__c WHERE Id = :AXSRuleEngine.Id LIMIT 1];
        Test.stopTest();
        
        System.assertEquals('Approved', AXSRuleEngine.ApprovalStatus__c );
    }
    
    testMethod static void testRecall() {
        FIN_AXSRuleEngine__c AXSRuleEngine= new FIN_AXSRuleEngine__c(
            FIN_Start_Date__c = Date.today(),
                FIN_Type__c = 'Financial'
        );
        insert AXSRuleEngine;
        
        Test.startTest();
        FIN_AXSRuleEngineExtController con = new FIN_AXSRuleEngineExtController (new ApexPages.StandardController(AXSRuleEngine));
        con.onRecall();
        AXSRuleEngine= [SELECT ApprovalStatus__c  FROM FIN_AXSRuleEngine__c WHERE Id = :AXSRuleEngine.Id LIMIT 1];
        Test.stopTest();
        
        System.assertEquals('Recalled', AXSRuleEngine.ApprovalStatus__c );
    }
}