force-app/main/default/objects/FIN_Journalizing_Item__c/FIN_Journalizing_Item__c.object-meta.xml
<CustomObject>
    <label>Journalizing Item</label>
    <nameField>
        <displayFormat>JI-{0000000000}</displayFormat>
        <label>Journalizing Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journalizing Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/Payment_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Payment_Distribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Journalizing_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Journalizing_Status__c</fullName>
    <label>Journalizing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Journalizing_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Order__c.field-meta.xml
<CustomField>
    <fullName>FIN_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/FIN_Journalizing_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ToBePosted</fullName>
        <label>To be Posted</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>Exported</fullName>
    </customValue>
    <customValue>
        <fullName>Posted</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <customValue>
        <fullName>PartiallyPosted</fullName>
        <isActive>false</isActive>
        <label>Partially Posted</label>
    </customValue>
    <masterLabel>Journalizing Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/helpers/FIN_JournalizingItemHelper.cls
public with sharing class FIN_JournalizingItemHelper {
    static final String PDS_CONST = 'PDs';
    static final String PAYMENTS_CONST = 'Payments';
    static final String INPROGRESS_CONST = 'InProgress';
    static final String TOBEPOSTED_CONST = 'ToBePosted';

    public static void updateStatusesAfterInsert(List<FIN_Journalizing_Item__c> items, Map<Id, FIN_Journalizing_Item__c> oldMap) {
        try {
            Map<String, Set<Id>> mapObjIds = new Map<String, Set<Id>>{
                PDS_CONST => new Set<Id>(),
                PAYMENTS_CONST => new Set<Id>()
            };

            for (FIN_Journalizing_Item__c item : [
                SELECT Id, Payment_Distribution__c, FIN_Payment__c, Payment_Distribution__r.FIN_Payment__c
                FROM FIN_Journalizing_Item__c
                WHERE Id IN :items
            ]) {
                mapObjIds.get(PDS_CONST).add(item.Payment_Distribution__c);
                mapObjIds.get(PAYMENTS_CONST).add(item.FIN_Payment__c);
                mapObjIds.get(PAYMENTS_CONST).add(item.Payment_Distribution__r.FIN_Payment__c);
            }

            List<FIN_PaymentDistribution__c> pdList = new List<FIN_PaymentDistribution__c>();

            for (FIN_PaymentDistribution__c pd : [
                SELECT Id, FIN_Journalizing_Status__c
                FROM FIN_PaymentDistribution__c
                WHERE Id IN :mapObjIds.get(PDS_CONST)
            ]) {
                pd.FIN_Journalizing_Status__c = INPROGRESS_CONST;
                pdList.add(pd);
            }

            if (!pdList.isEmpty()) {
                update pdList;
            }

            List<FIN_Payment__c> paymentsList = new List<FIN_Payment__c>();

            for (FIN_Payment__c payment : [
                SELECT Id, FIN_Journalizing_Status__c
                FROM FIN_Payment__c
                WHERE Id IN :mapObjIds.get(PAYMENTS_CONST)
            ]) {
                payment.FIN_Journalizing_Status__c = INPROGRESS_CONST;
                paymentsList.add(payment);
            }

            if (!paymentsList.isEmpty()) {
                update paymentsList;
            }
        } catch (DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
    }

    public static void updateStatusesBeforeDelete(Map<Id, FIN_Journalizing_Item__c> itemsInv) {
        try {
            Map<String, Set<Id>> mapObjIds = new Map<String, Set<Id>>{
                PDS_CONST => new Set<Id>(),
                PAYMENTS_CONST => new Set<Id>()
            };

            for (FIN_Journalizing_Item__c item : [
                SELECT Id, Payment_Distribution__c, FIN_Payment__c, Payment_Distribution__r.FIN_Payment__c
                FROM FIN_Journalizing_Item__c
                WHERE Id IN :itemsInv.keySet()
            ]) {
                mapObjIds.get(PDS_CONST).add(item.Payment_Distribution__c);
                mapObjIds.get(PAYMENTS_CONST).add(item.FIN_Payment__c);
                mapObjIds.get(PAYMENTS_CONST).add(item.Payment_Distribution__r.FIN_Payment__c);
            }

            List<FIN_PaymentDistribution__c> pdList = new List<FIN_PaymentDistribution__c>();
            if (!mapObjIds.get(PDS_CONST).isEmpty()) {
                for (FIN_PaymentDistribution__c pd : [
                    SELECT Id, FIN_Journalizing_Status__c, FIN_Payment__r.FIN_Order__c
                    FROM FIN_PaymentDistribution__c
                    WHERE Id IN :mapObjIds.get(PDS_CONST)
                ]) {
                    pd.FIN_Journalizing_Status__c = TOBEPOSTED_CONST;
                    pdList.add(pd);
                }
            }

            if (!pdList.isEmpty()) {
                update pdList;
            }

            List<FIN_Payment__c> paymentList = new List<FIN_Payment__c>();
            if (!mapObjIds.get(PAYMENTS_CONST).isEmpty()) {
                for (FIN_Payment__c payment : [
                    SELECT Id, FIN_Journalizing_Status__c
                    FROM FIN_Payment__c
                    WHERE Id IN :mapObjIds.get(PAYMENTS_CONST)
                ]) {
                    payment.FIN_Journalizing_Status__c = TOBEPOSTED_CONST;
                    paymentList.add(payment);
                }
            }

            if (!paymentList.isEmpty()) {
                update paymentList;
            }
        } catch (DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
    }
}