force-app/main/default/objects/FIN_Journalizing_Item__c/FIN_Journalizing_Item__c.object-meta.xml
<CustomObject>
    <label>Journalizing Item</label>
    <nameField>
        <displayFormat>JI-{0000000000}</displayFormat>
        <label>Journalizing Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journalizing Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_Parent_Journalizing_Schedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_Parent_Journalizing_Schedule__c</fullName>
    <label>Parent Journalizing Schedule</label>
    <referenceTo>Journalizing_Schedule__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/Payment_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Payment_Distribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Event__c.field-meta.xml
<CustomField>
    <fullName>FIN_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journalizing_Schedule__c/Journalizing_Schedule__c.object-meta.xml
<CustomObject>
    <label>Journalizing Schedule</label>
    <nameField>
        <displayFormat>JS-{0000000000}</displayFormat>
        <label>Journalizing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journalizing Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journalizing_Schedule__c/fields/FIN_Type__c.field-meta.xml
<CustomField>
    <fullName>FIN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDs</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testClasses/FIN_JournalizingItemHelperTest.cls
@IsTest
private class FIN_JournalizingItemHelperTest {
    @TestSetup
    static void prepareData() {
        RecordType record = [
                SELECT Id
                FROM RecordType
                WHERE Name = 'US Payment Distribution'
            ];

            Campaign event = new Campaign(
                Name = 'Test Name'
            );
            insert event;

            FIN_PaymentDistribution__c pd = new FIN_PaymentDistribution__c(
                RecordTypeId = record.Id,
                CurrencyIsoCode = 'USD',
                FIN_Event__c = event.Id,
                FIN_Journalizing_Status__c = 'ToBePosted'
            );
            insert pd;

            Journalizing_Schedule__c js = new Journalizing_Schedule__c(
                FIN_Type__c = 'PDs'
            );
            insert js;
    }

    @IsTest
    static void updateStatusesAfterInsert() {
        FIN_PaymentDistribution__c pd = [
            SELECT Id
            FROM FIN_PaymentDistribution__c
            LIMIT 1
        ];
        Journalizing_Schedule__c js = [
            SELECT Id
            FROM Journalizing_Schedule__c
            LIMIT 1
        ];

        FIN_Journalizing_Item__c ji = new FIN_Journalizing_Item__c(
            FIN_Parent_Journalizing_Schedule__c = js.Id,
            Payment_Distribution__c = pd.Id
        );
        insert ji;

        List<FIN_PaymentDistribution__c> PDList = [
            SELECT Id, RecordTypeId, FIN_Journalizing_Status__c
            FROM FIN_PaymentDistribution__c
        ];

        System.assertEquals(PDList[0].FIN_Journalizing_Status__c, 'InProgress');
    }

    @IsTest
    static void updateStatusesBeforeDelete() {
        FIN_PaymentDistribution__c pd = [
            SELECT Id
            FROM FIN_PaymentDistribution__c
            LIMIT 1
        ];
        Journalizing_Schedule__c js = [
            SELECT Id
            FROM Journalizing_Schedule__c
            LIMIT 1
        ];

        FIN_Journalizing_Item__c ji = new FIN_Journalizing_Item__c(
            FIN_Parent_Journalizing_Schedule__c = js.Id,
            Payment_Distribution__c = pd.Id
        );

        insert ji;
        delete ji;

        List<FIN_PaymentDistribution__c> PDList = [
            SELECT Id, RecordTypeId, FIN_Journalizing_Status__c
            FROM FIN_PaymentDistribution__c
        ];

        System.assertEquals(PDList[0].FIN_Journalizing_Status__c, 'ToBePosted');
    }
}