force-app/main/default/objects/FIN_Journalizing_Item__c/FIN_Journalizing_Item__c.object-meta.xml
<CustomObject>
    <label>Journalizing Item</label>
    <nameField>
        <displayFormat>JI-{0000000000}</displayFormat>
        <label>Journalizing Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journalizing Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_JournalEntrySign__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntrySign__c</fullName>
    <label>Journal Entry Sign</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/Payment_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Payment_Distribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_AdjustmentAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_AdjustmentAmount__c</fullName>
    <label>Distribution Adjustment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Auto_Approved__c.field-meta.xml
<CustomField>
    <fullName>FIN_Auto_Approved__c</fullName>
    <description>Fill up Contract, Distribution Amount, Payment and Library Association to mark the record Approved</description>
    <formula>IF(
OR( ISBLANK( FIN_Payment__c) ,ISBlank(FIN_LibraryAssociation__c), ISBLANK(FIN_DistributionAmount__c), ISBLANK(Contract__c) ) ,
FALSE,
TRUE)</formula>
    <inlineHelpText>Fill up Contract, Distribution Amount, Payment and Library Association to mark the record Approved</inlineHelpText>
    <label>Auto Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_DistributionAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmount__c</fullName>
    <label>Distribution Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_DistributionAmountNetofTaxAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmountNetofTaxAmount__c</fullName>
    <label>Distribution Amount - Net of Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_DistributionAmountTaxAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmountTaxAmount__c</fullName>
    <label>Distribution Amount - Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_DistributionAmountTaxIncluded__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmountTaxIncluded__c</fullName>
    <label>Distribution Amount - Tax Included</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_DistributionDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionDate__c</fullName>
    <label>Distribution Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <formula>FIN_DistributionAmount__c  * FIN_JournalEntrySign__c</formula>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_JournalEntrySign__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntrySign__c</fullName>
    <formula>IF (
ISBLANK(TEXT(FIN_LibraryAssociation__r.FIN_Financial_Code__r.FIN_Financial_Chart_of_Accounts__r.FIN_Account_Type__c)),
1,

IF(
((TEXT(FIN_LibraryAssociation__r.FIN_Financial_Code__r.FIN_Financial_Chart_of_Accounts__r.FIN_Account_Type__c) == &apos;Asset&apos;) || 
(TEXT(FIN_LibraryAssociation__r.FIN_Financial_Code__r.FIN_Financial_Chart_of_Accounts__r.FIN_Account_Type__c) == &apos;Expenses&apos;))
, 1, -1
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Journal Entry Sign</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>FIN_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_PDUnclassified__c.field-meta.xml
<CustomField>
    <fullName>FIN_PDUnclassified__c</fullName>
    <formula>((CONTAINS(FIN_ContractRecordType__c, &apos;Master&apos;) || 
 ISBLANK(Contract__c) || CONTAINS(FIN_ContractName__c, &apos;UNCLASSIFIED&apos;)) &amp;&amp; !FIN_Auto_Approved__c)
|| (ISBLANK(FIN_Event__c) &amp;&amp; !FIN_Auto_Approved__c)
|| !FIN_Auto_Approved__c
|| (FIN_Sales_Unclassified__c &amp;&amp; !FIN_Auto_Approved__c)
|| (ISBLANK(FIN_LibraryAssociation__c) &amp;&amp; !FIN_Auto_Approved__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PD Unclassified?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/Invoices_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoices_Status__c</fullName>
    <label>Invoices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Invoices_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/FIN_RetroactiveAdjustment__c.object-meta.xml
<CustomObject>
    <label>Retroactive Adjustment</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Retroactive Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retroactive Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_AdjustmentAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_AdjustmentAmount__c</fullName>
    <label>Adjustment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_DistributionAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmount__c</fullName>
    <label>Distribution Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_DistributionAmountNetofTaxAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmountNetofTaxAmount__c</fullName>
    <label>Distribution Amount - Net of Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_DistributionAmountTaxAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmountTaxAmount__c</fullName>
    <label>Distribution Amount - Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_DistributionAmountTaxIncluded__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmountTaxIncluded__c</fullName>
    <label>Distribution Amount - Tax Included</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_DistributionDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionDate__c</fullName>
    <label>Distribution Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>FIN_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Transactions</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FIN_Invoices_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>ToBeInvoiced</fullName>
        <label>To Be Invoiced</label>
    </customValue>
    <customValue>
        <fullName>InvoiceScheduled</fullName>
        <label>Invoice in Progress</label>
    </customValue>
    <customValue>
        <fullName>Invoiced</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/helpers/FIN_PaymentDistributionHelper.cls
public with sharing class FIN_PaymentDistributionHelper {
    public static void updateJournalEntrySignAndAmount(List<FIN_PaymentDistribution__c> pds, Map<Id, FIN_PaymentDistribution__c> oldMap) {
        Map<Id, FIN_PaymentDistribution__c> pdsWithNewJournalEntryAmount = new Map<Id, FIN_PaymentDistribution__c>();
        Id pdRecordTypeId = Schema.SObjectType.FIN_Journalizing_Item__c.getRecordTypeInfosByName().get('II PDs Record Type').getRecordTypeId();

        for (FIN_PaymentDistribution__c pd : pds) {
            if (pd.FIN_DistributionAmount__c != oldMap.get(pd.Id).FIN_DistributionAmount__c && pd.FIN_Journalizing_Status__c != 'Posted') {
                pdsWithNewJournalEntryAmount.put(pd.Id, pd);
            }
        }

        if (pdsWithNewJournalEntryAmount.size() > 0) {
            List<FIN_Journalizing_Item__c> journalizingItems = [
                SELECT Id, Payment_Distribution__c, FIN_JournalEntryAmount__c, FIN_JournalEntrySign__c
                FROM FIN_Journalizing_Item__c
                WHERE RecordTypeId = :pdRecordTypeId
                AND Payment_Distribution__c IN :pdsWithNewJournalEntryAmount.keySet()
            ];

            if (journalizingItems.size() > 0) {
                for (FIN_Journalizing_Item__c journalizingItem : journalizingItems) {
                    journalizingItem.FIN_JournalEntryAmount__c = pdsWithNewJournalEntryAmount.get(journalizingItem.Payment_Distribution__c).FIN_JournalEntryAmount__c;
                    journalizingItem.FIN_JournalEntrySign__c = pdsWithNewJournalEntryAmount.get(journalizingItem.Payment_Distribution__c).FIN_JournalEntrySign__c;
                }

                update journalizingItems;
            }
        }
    }

    public static void createRetroactiveAdjustment(List<FIN_PaymentDistribution__c> pdDistributions, Map<Id, FIN_PaymentDistribution__c> oldMap) {
        List<FIN_RetroactiveAdjustment__c> retroactiveAdjustments = new List<FIN_RetroactiveAdjustment__c>();
        Id pdDistributionRecordTypeId = Schema.SObjectType.FIN_RetroactiveAdjustment__c.getRecordTypeInfosByName().get('Payment Distribution').getRecordTypeId();

        Map<String, String> pdDistributionRAMap = new Map<String, String>{
            'FIN_Region__c' => 'FIN_Region__c',
            'FIN_OrderProduct__c' => 'FIN_OrderProduct__c',
            'FIN_DistributionDate__c' => 'FIN_DistributionDate__c',
            'FIN_DistributionAmount__c' => 'FIN_DistributionAmount__c',
            'FIN_DistributionAmountTaxIncluded__c' => 'FIN_DistributionAmountTaxIncluded__c',
            'FIN_DistributionAmountTaxAmount__c' => 'FIN_DistributionAmountTaxAmount__c',
            'FIN_DistributionAmountNetofTaxAmount__c' => 'FIN_DistributionAmountNetofTaxAmount__c',
            'FIN_AdjustmentAmount__c' => 'FIN_AdjustmentAmount__c'
        };

        for (FIN_PaymentDistribution__c pdDistribution : pdDistributions) {
            if (pdDistribution.FIN_AdjustmentAmount__c != oldMap.get(pdDistribution.Id).FIN_AdjustmentAmount__c) {
                FIN_PaymentDistribution__c oldPD = oldMap.get(pdDistribution.Id);

                FIN_RetroactiveAdjustment__c newRetroactiveAdjustment = new FIN_RetroactiveAdjustment__c();
                newRetroactiveAdjustment.FIN_PaymentDistribution__c = pdDistribution.Id;
                newRetroactiveAdjustment.FIN_OrderProduct__c = pdDistribution.FIN_OrderProduct__c;
                newRetroactiveAdjustment.RecordTypeId = pdDistributionRecordTypeId;

                for (String str : pdDistributionRAMap.keyset()) {
                    if (pdDistribution.get(str) != oldPD.get(str)) {
                        newRetroactiveAdjustment.put(pdDistributionRAMap.get(str), pdDistribution.get(str));
                    }
                }

                retroactiveAdjustments.add(newRetroactiveAdjustment);
            }
        }
        if (!retroactiveAdjustments.isEmpty()) {
                insert retroactiveAdjustments;
        }
    }

    public static void updateOwnerOnClassifiedRecord(List<FIN_PaymentDistribution__c> paymentDistributions) {
        for (FIN_PaymentDistribution__c pd : paymentDistributions) {
            if (!String.isBlank(pd.Owner.Name)) {
                System.debug('pd.Owner' + pd.Owner.Name.contains('Unclassified'));
                if (pd.Owner.Name.contains('Unclassified') && !pd.FIN_PDUnclassified__c) {
                    pd.OwnerId = UserInfo.getUserId();
                }
            }
        }
    }

    public static void updateSettlementJournalizingStatuses(List<FIN_PaymentDistribution__c> paymentDistributions) {
        for (FIN_PaymentDistribution__c pd : paymentDistributions) {
            if (pd.FIN_FinancialResponsibilty__c == 'AXS') {
                pd.FIN_Settlement_Status__c = 'ToBeSettled';
                pd.FIN_Journalizing_Status__c = 'ToBePosted';
                pd.Invoices_Status__c = 'ToBeInvoiced';
            } else if (pd.FIN_FinancialResponsibilty__c == 'N/A') {
                pd.FIN_Settlement_Status__c = 'NotApplicable';
                pd.FIN_Journalizing_Status__c = 'NotApplicable';
                pd.Invoices_Status__c = 'NotApplicable';
            }
            if (pd.FIN_Auto_Approved__c == true) {
                pd.FIN_ApprovalStatus__c = 'Approved';
            } else {
                pd.FIN_ApprovalStatus__c = 'New';
            }
        }
    }

    public static void updateApprovalStatus(List<FIN_PaymentDistribution__c> paymentDistributions, Map<Id, FIN_PaymentDistribution__c> oldMap) {
        for (FIN_PaymentDistribution__c pd : paymentDistributions) {
            if (!pd.FIN_Auto_Approved__c && pd.FIN_ApprovalStatus__c == 'Approved') {
                if (pd.FIN_ApprovalStatus__c != oldMap.get(pd.Id).FIN_ApprovalStatus__c) {
                    pd.addError('Please populate the fields required for Approval: Contract, Payment, Library Association, Distribution Amount');
                } else {
                    pd.FIN_ApprovalStatus__c = 'New';
                }
            } else if (pd.FIN_Auto_Approved__c && pd.FIN_ApprovalStatus__c == oldMap.get(pd.Id).FIN_ApprovalStatus__c && pd.FIN_ApprovalStatus__c == 'New') {
                pd.FIN_ApprovalStatus__c = 'Approved';
            }
        }
    }
}