force-app/main/default/objects/FIN_Journalizing_Item__c/FIN_Journalizing_Item__c.object-meta.xml
<CustomObject>
    <label>Journalizing Item</label>
    <nameField>
        <displayFormat>JI-{0000000000}</displayFormat>
        <label>Journalizing Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journalizing Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_Parent_Journalizing_Schedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_Parent_Journalizing_Schedule__c</fullName>
    <label>Parent Journalizing Schedule</label>
    <referenceTo>Journalizing_Schedule__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/Payment_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Payment_Distribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Journalizing_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Journalizing_Status__c</fullName>
    <label>Journalizing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Journalizing_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journalizing_Schedule__c/Journalizing_Schedule__c.object-meta.xml
<CustomObject>
    <label>Journalizing Schedule</label>
    <nameField>
        <displayFormat>JS-{0000000000}</displayFormat>
        <label>Journalizing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journalizing Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journalizing_Schedule__c/fields/FIN_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Journalizing_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FIN_Journalizing_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ToBePosted</fullName>
        <label>To be Posted</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>Exported</fullName>
    </customValue>
    <customValue>
        <fullName>Posted</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <customValue>
        <fullName>PartiallyPosted</fullName>
        <isActive>false</isActive>
        <label>Partially Posted</label>
    </customValue>
    <masterLabel>Journalizing Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/helpers/FIN_JournalizingScheduleHelper.cls
public with sharing class  FIN_JournalizingScheduleHelper {
    static final String TOBEPOSTED_CONST = 'ToBePosted';
    static final String POSTED_CONST = 'Posted';
    static final String VOIDED_CONST = 'Voided';

    public static void updateStatusesAfterUpdate(List<Journalizing_Schedule__c> journalizings, Map<Id, Journalizing_Schedule__c> oldMap) {
        Set<Id> journalizingPostedIds = new Set<Id>();
        Set<Id> journalizingVoidIds = new Set<Id>();

        try {
            for (Journalizing_Schedule__c journalizing : journalizings) {
                if (journalizing.FIN_Status__c != oldMap?.get(journalizing.Id)?.FIN_Status__c && journalizing.FIN_Status__c == POSTED_CONST) {
                    journalizingPostedIds.add(journalizing.Id);
                } else if (journalizing.FIN_Status__c != oldMap?.get(journalizing.Id)?.FIN_Status__c && journalizing.FIN_Status__c == VOIDED_CONST) {
                    journalizingVoidIds.add(journalizing.Id);
                }
            }

            List<FIN_Journalizing_Item__c> itemsPosted = [
                SELECT Id, Payment_Distribution__c, FIN_Payment__c, Payment_Distribution__r.FIN_Payment__c
                FROM FIN_Journalizing_Item__c
                WHERE FIN_Parent_Journalizing_Schedule__c IN :journalizingPostedIds
            ];

            List<FIN_Journalizing_Item__c> itemsVoid = [
                SELECT Id, Payment_Distribution__c, FIN_Payment__c, Payment_Distribution__r.FIN_Payment__c
                FROM FIN_Journalizing_Item__c
                WHERE FIN_Parent_Journalizing_Schedule__c IN :journalizingVoidIds
            ];

            Map<String, Set<Id>> mapPDsId = new Map<String, Set<Id>>{
                POSTED_CONST => new Set<Id>(),
                VOIDED_CONST => new Set<Id>()
            };

            Map<String, Set<Id>> mapPaymentsId = new Map<String, Set<Id>>{
                POSTED_CONST => new Set<Id>(),
                VOIDED_CONST => new Set<Id>()
            };

            for (FIN_Journalizing_Item__c item : itemsPosted) {
                mapPDsId.get(POSTED_CONST).add(item.Payment_Distribution__c);
                mapPaymentsId.get(POSTED_CONST).add(item.FIN_Payment__c);
                mapPaymentsId.get(POSTED_CONST).add(item.Payment_Distribution__r.FIN_Payment__c);
            }

            for (FIN_Journalizing_Item__c item : itemsVoid) {
                mapPDsId.get(VOIDED_CONST).add(item.Payment_Distribution__c);
                mapPaymentsId.get(VOIDED_CONST).add(item.FIN_Payment__c);
                mapPaymentsId.get(VOIDED_CONST).add(item.Payment_Distribution__r.FIN_Payment__c);
            }

            System.debug('mapPDsId.values()' + mapPDsId.values());

            List<FIN_PaymentDistribution__c> pdList = [
                SELECT Id, FIN_Journalizing_Status__c
                FROM FIN_PaymentDistribution__c
                WHERE Id IN :getSet(mapPDsId)
            ];

            for (FIN_PaymentDistribution__c pd : pdList) {
                if(mapPDsId.get(POSTED_CONST).contains(pd.Id)) {
                    pd.FIN_Journalizing_Status__c = POSTED_CONST;
                } else if (mapPDsId.get(VOIDED_CONST).contains(pd.Id)) {
                    pd.FIN_Journalizing_Status__c = TOBEPOSTED_CONST;
                }
            }
            
            List<FIN_Payment__c> paymentsList = [
                SELECT Id, FIN_Journalizing_Status__c
                FROM FIN_Payment__c
                WHERE Id IN :getSet(mapPaymentsId)
            ];

            for(FIN_Payment__c payment: paymentsList) {
                if(mapPaymentsId.get(POSTED_CONST).contains(payment.Id)) {
                    payment.FIN_Journalizing_Status__c = POSTED_CONST;
                } else if (mapPaymentsId.get(VOIDED_CONST).contains(payment.Id)) {
                    payment.FIN_Journalizing_Status__c = TOBEPOSTED_CONST;
                }
            }

            update pdList;
            update paymentsList;

        } catch (DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
    }

    public static Set<Id> getSet(Map<String,Set<Id>> mapIds) {
        Set<Id> result = new Set<Id>();
        for(Set<Id> setId : mapIds.values()){
            result.addAll(setId);
        }

        result.remove(null);
        return result;
    }
}