force-app/main/default/objects/FIN_Journalizing_Item__c/FIN_Journalizing_Item__c.object-meta.xml
<CustomObject>
    <label>Journalizing Item</label>
    <nameField>
        <displayFormat>JI-{0000000000}</displayFormat>
        <label>Journalizing Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journalizing Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_JournalEntrySign__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntrySign__c</fullName>
    <label>Journal Entry Sign</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_Library_Association__c.field-meta.xml
<CustomField>
    <fullName>FIN_Library_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_Manual_Amount__c.field-meta.xml
<CustomField>
    <fullName>FIN_Manual_Amount__c</fullName>
    <label>Manual $ Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_Parent_Journalizing_Schedule__c.field-meta.xml
<CustomField>
    <fullName>FIN_Parent_Journalizing_Schedule__c</fullName>
    <label>Parent Journalizing Schedule</label>
    <referenceTo>Journalizing_Schedule__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/Payment_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Payment_Distribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <formula>FIN_PaymentAmount__c * FIN_JournalEntrySign__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_JournalEntrySign__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntrySign__c</fullName>
    <formula>IF (
ISBLANK(TEXT(FIN_LibraryAssociation__r.FIN_Financial_Code__r.FIN_Financial_Chart_of_Accounts__r.FIN_Account_Type__c)),
1,
				
IF(
((TEXT(FIN_LibraryAssociation__r.FIN_Financial_Code__r.FIN_Financial_Chart_of_Accounts__r.FIN_Account_Type__c) == &apos;Asset&apos;) ||
(TEXT(FIN_LibraryAssociation__r.FIN_Financial_Code__r.FIN_Financial_Chart_of_Accounts__r.FIN_Account_Type__c) == &apos;Expenses&apos;))
, 1, -1
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Journal Entry Sign</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Journalizing_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Journalizing_Status__c</fullName>
    <label>Journalizing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Journalizing_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_PaymentAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentAmount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>FIN_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_DistributionAmountNetofTaxAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmountNetofTaxAmount__c</fullName>
    <label>Distribution Amount - Net of Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <formula>FIN_DistributionAmount__c  * FIN_JournalEntrySign__c</formula>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_JournalEntrySign__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntrySign__c</fullName>
    <formula>IF (
ISBLANK(TEXT(FIN_LibraryAssociation__r.FIN_Financial_Code__r.FIN_Financial_Chart_of_Accounts__r.FIN_Account_Type__c)),
1,

IF(
((TEXT(FIN_LibraryAssociation__r.FIN_Financial_Code__r.FIN_Financial_Chart_of_Accounts__r.FIN_Account_Type__c) == &apos;Asset&apos;) || 
(TEXT(FIN_LibraryAssociation__r.FIN_Financial_Code__r.FIN_Financial_Chart_of_Accounts__r.FIN_Account_Type__c) == &apos;Expenses&apos;))
, 1, -1
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Journal Entry Sign</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distribution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>FIN_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journalizing_Schedule__c/Journalizing_Schedule__c.object-meta.xml
<CustomObject>
    <label>Journalizing Schedule</label>
    <nameField>
        <displayFormat>JS-{0000000000}</displayFormat>
        <label>Journalizing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journalizing Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journalizing_Schedule__c/fields/FIN_Type__c.field-meta.xml
<CustomField>
    <fullName>FIN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDs</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/FIN_Current_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Current_Region__c</fullName>
    <label>Current Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FIN_Journalizing_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ToBePosted</fullName>
        <label>To be Posted</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>Exported</fullName>
    </customValue>
    <customValue>
        <fullName>Posted</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <customValue>
        <fullName>PartiallyPosted</fullName>
        <isActive>false</isActive>
        <label>Partially Posted</label>
    </customValue>
    <masterLabel>Journalizing Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/controllers/JournalizingDataController.cls
public with sharing class JournalizingDataController {
    static final String PDS_CONST = 'PDs';
    static final String PAYMENTS_CONST = 'Payments';

    @AuraEnabled(cacheable=true)
    public static List<String> getRegionPickListValues() {
        List<String> pickListValuesList = new List<String>();
        Schema.DescribeFieldResult fieldResult = User.FIN_Current_Region__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry pickListVal : ple) {
            pickListValuesList.add(pickListVal.getLabel());
        }

        return pickListValuesList;
    }

    @AuraEnabled(cacheable=false)
    public static Integer createJI(List<Id> listIDs, String type, String journalizingSh) {
        List<FIN_Journalizing_Item__c> newItems = new List<FIN_Journalizing_Item__c>();

        if (type == 'PDs') {
            List<FIN_PaymentDistribution__c> listPD = new List<FIN_PaymentDistribution__c>();

            for (FIN_PaymentDistribution__c pd : [
                SELECT Id, FIN_Payment__c, FIN_LibraryAssociation__c, FIN_JournalEntryAmount__c, FIN_JournalEntrySign__c
                FROM FIN_PaymentDistribution__c
                WHERE Id IN :listIDs
            ]) {
                pd.FIN_Journalizing_Status__c = 'InProgress';
                newItems.add(new FIN_Journalizing_Item__c(
                    Payment_Distribution__c = pd.Id,
                    FIN_Payment__c = pd.FIN_Payment__c,
                    RecordTypeId = getRecordTypeIdByObjName(type),
                    FIN_Parent_Journalizing_Schedule__c = journalizingSh,
                    FIN_Library_Association__c = pd.FIN_LibraryAssociation__c,
                    FIN_Manual_Amount__c = pd.FIN_JournalEntryAmount__c,
                    FIN_JournalEntryAmount__c = pd.FIN_JournalEntryAmount__c,
                    FIN_JournalEntrySign__c = pd.FIN_JournalEntrySign__c
                ));

                listPD.add(pd);
            }

            if(!listPD.isEmpty()) {
                update listPD;
            }
        } else if (type == 'Payments') {
            List<FIN_Payment__c> listPayments = new List<FIN_Payment__c>();

            for (FIN_Payment__c payment : [
                SELECT Id, FIN_JournalEntryAmount__c, FIN_JournalEntrySign__c, FIN_LibraryAssociation__c
                FROM FIN_Payment__c
                WHERE Id IN :listIDs
            ]) {
                payment.FIN_Journalizing_Status__c = 'InProgress';
                newItems.add(new FIN_Journalizing_Item__c(
                    FIN_Payment__c = payment.Id,
                    FIN_Parent_Journalizing_Schedule__c = journalizingSh,
                    RecordTypeId = getRecordTypeIdByObjName(type),
                    FIN_JournalEntryAmount__c = payment.FIN_JournalEntryAmount__c,
                    FIN_JournalEntrySign__c = payment.FIN_JournalEntrySign__c,
                    FIN_Library_Association__c = payment.FIN_LibraryAssociation__c
                    // FIN_Manual_Amount__c = payment.FIN_JournalEntryAmount__c
                ));
                listPayments.add(payment);
            }

            if(!listPayments.isEmpty()) {
                update listPayments;
            }
        }

        insert newItems;

        return newItems.size();
    }

    @AuraEnabled(cacheable=true)
    public static List<Contract> getRelatedRecords(String journalizingSh) {
        List<FIN_Journalizing_Item__c> listII = [
            SELECT Id, Payment_Distribution__r.Contract__c, FIN_Payment__r.Contract__c, FIN_Parent_Journalizing_Schedule__r.FIN_Type__c
            FROM FIN_Journalizing_Item__c
            WHERE FIN_Parent_Journalizing_Schedule__c = :journalizingSh
        ];
        Set<String> setContractId = new Set<String>();
        Set<String> setPDsId = new Set<String>();
        Set<String> setPaymentsId = new Set<String>();

        String type;

        if (listII.size() > 0) {
            type = listII[0]?.FIN_Parent_Journalizing_Schedule__r?.FIN_Type__c;
        }

        if (type == PDS_CONST) {
            for (FIN_Journalizing_Item__c item : listII) {
                setContractId.add(item.Payment_Distribution__r.Contract__c);
                setPDsId.add(item.Payment_Distribution__c);

            }
        } else if (type == PAYMENTS_CONST) {
            for (FIN_Journalizing_Item__c item : listII) {
                setContractId.add(item.FIN_Payment__r.Contract__c);
                setPaymentsId.add(item.FIN_Payment__c);
            }
        }

        if (!setContractId.isEmpty()) {
            if (type == PDS_CONST) {
                return [
                    SELECT Id, Name, ContractNumber, (
                        SELECT Id, FIN_DistributionAmountNetofTaxAmount__c, FIN_JournalEntryAmount__c
                        FROM Payment_Distributions__r
                        WHERE Id IN:setPDsId
                    )
                    FROM Contract
                    WHERE Id IN :setContractId
                ];
            } else if (type == PAYMENTS_CONST) {
                return [
                    SELECT Id, Name, ContractNumber, (
                        SELECT Id, FIN_PaymentAmount__c, FIN_JournalEntryAmount__c
                        FROM Payments__r
                        WHERE Id IN:setPaymentsId
                    )
                    FROM Contract
                    WHERE Id IN :setContractId
                ];
            } else {
                return new List<Contract>();
            }
        } else {
            return new List<Contract>();
        }
    }

    @AuraEnabled(cacheable=false)
    public static Integer removeRelatedJIs(List<Id> listSubContracts, String journalizingSh) {
        List<FIN_Journalizing_Item__c> listII = [
            SELECT Id
            FROM FIN_Journalizing_Item__c
            WHERE (Payment_Distribution__r.Contract__c IN :listSubContracts
            OR FIN_Payment__r.Contract__c IN :listSubContracts)
            AND FIN_Parent_Journalizing_Schedule__c = :journalizingSh
        ];

        delete listII;
        return listII.size();
    }

    public static Id getRecordTypeIdByObjName(String type) {
        Map<String, Schema.RecordTypeInfo> rts = Schema.SObjectType.FIN_Journalizing_Item__c.getRecordTypeInfosByDeveloperName();

        for (String rt : rts.keySet()) {
            if (rt.contains(type)) {
                return rts.get(rt).RecordTypeId;
            }
        }

        return null;
    }
}