force-app/main/default/objects/FIN_Journalizing_Item__c/FIN_Journalizing_Item__c.object-meta.xml
<CustomObject>
    <label>Journalizing Item</label>
    <nameField>
        <displayFormat>JI-{0000000000}</displayFormat>
        <label>Journalizing Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journalizing Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_JournalEntrySign__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntrySign__c</fullName>
    <label>Journal Entry Sign</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Submitted for Review</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Auto_Approved__c.field-meta.xml
<CustomField>
    <fullName>FIN_Auto_Approved__c</fullName>
    <description>Fill up Contract, Payment Amount, Sales and Library Association to mark the record Approved</description>
    <formula>IF(
OR( ISBLANK( FIN_Order__c) ,ISBLANK(FIN_LibraryAssociation__c), ISBLANK(FIN_PaymentAmount__c), ISBLANK(Contract__c) ) ,
FALSE,
TRUE)</formula>
    <inlineHelpText>Fill up Contract, Payment Amount, Sales and Library Association to mark the record Approved</inlineHelpText>
    <label>Auto Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_DepositDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_DepositDate__c</fullName>
    <label>Deposit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_FinancialResponsibilty__c.field-meta.xml
<CustomField>
    <fullName>FIN_FinancialResponsibilty__c</fullName>
    <formula>CASE(FIN_Channel__c,
  &quot;Back Office&quot;, TEXT(FIN_PaymentTypeChannel__r.FIN_Back_Office__c),
  &quot;Web&quot;, TEXT(FIN_PaymentTypeChannel__r.FIN_Web__c),
&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Financial Responsibilty</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Invoices_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Invoices_Status__c</fullName>
    <label>Invoices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Invoices_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <formula>FIN_PaymentAmount__c * FIN_JournalEntrySign__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_JournalEntrySign__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntrySign__c</fullName>
    <formula>IF (
ISBLANK(TEXT(FIN_LibraryAssociation__r.FIN_Financial_Code__r.FIN_Financial_Chart_of_Accounts__r.FIN_Account_Type__c)),
1,
				
IF(
((TEXT(FIN_LibraryAssociation__r.FIN_Financial_Code__r.FIN_Financial_Chart_of_Accounts__r.FIN_Account_Type__c) == &apos;Asset&apos;) ||
(TEXT(FIN_LibraryAssociation__r.FIN_Financial_Code__r.FIN_Financial_Chart_of_Accounts__r.FIN_Account_Type__c) == &apos;Expenses&apos;))
, 1, -1
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Journal Entry Sign</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Journalizing_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Journalizing_Status__c</fullName>
    <label>Journalizing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Journalizing_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Order__c.field-meta.xml
<CustomField>
    <fullName>FIN_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_PaymentAdjustment__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentAdjustment__c</fullName>
    <label>Payment Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_PaymentAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentAmount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_PaymentDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDate__c</fullName>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_PaymentUnclassified__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentUnclassified__c</fullName>
    <formula>((CONTAINS(FIN_ContractRecordType__c, &apos;Master&apos;) ||
		ISBLANK(Contract__c) || CONTAINS(Contract__r.Name,&apos;UNCLASSIFIED&apos;)) &amp;&amp; !FIN_Auto_Approved__c)
		|| !FIN_Auto_Approved__c
		|| (FIN_Sales_Unclassified__c &amp;&amp; !FIN_Auto_Approved__c)
		|| (ISBLANK(FIN_LibraryAssociation__c) &amp;&amp; !FIN_Auto_Approved__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Unclassified?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Settlement_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/FIN_RetroactiveAdjustment__c.object-meta.xml
<CustomObject>
    <label>Retroactive Adjustment</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Retroactive Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retroactive Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_DepositDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_DepositDate__c</fullName>
    <label>Deposit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Order__c.field-meta.xml
<CustomField>
    <fullName>FIN_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_PaymentAdjustment__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentAdjustment__c</fullName>
    <label>Payment Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_PaymentAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentAmount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_PaymentDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDate__c</fullName>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Submitted for Review</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Auto_Approved__c.field-meta.xml
<CustomField>
    <fullName>FIN_Auto_Approved__c</fullName>
    <description>This field determines if the record has minimum data elements to be auto approved</description>
    <formula>IF(
OR( Account.Name =&quot;US Unclassified Client&quot; ,ISBLANK(FIN_OrderContext__c), ISBLANK(ContractId), FIN_Total_Sales_Qty__c = 0),
FALSE,
TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Contract, Context and Account must be populated and at least 1 Sale Transaction must be created to make the Sale auto-approved.</inlineHelpText>
    <label>Auto Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Journalizing_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Journalizing_Status__c</fullName>
    <label>Journalizing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Journalizing_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FIN_Invoices_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>ToBeInvoiced</fullName>
        <label>To Be Invoiced</label>
    </customValue>
    <customValue>
        <fullName>InvoiceScheduled</fullName>
        <label>Invoice in Progress</label>
    </customValue>
    <customValue>
        <fullName>Invoiced</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FIN_Journalizing_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ToBePosted</fullName>
        <label>To be Posted</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>Exported</fullName>
    </customValue>
    <customValue>
        <fullName>Posted</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <customValue>
        <fullName>PartiallyPosted</fullName>
        <isActive>false</isActive>
        <label>Partially Posted</label>
    </customValue>
    <masterLabel>Journalizing Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/FIN_Settlement_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>ToBeSettled</fullName>
        <label>To Be Settled</label>
    </customValue>
    <customValue>
        <fullName>Settled</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>ScheduledSettlement</fullName>
        <label>Scheduled for Settlement</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <masterLabel>Settlement Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/helpers/FIN_PaymentHelper.cls
public with sharing class FIN_PaymentHelper {
    public static void createRetroactiveAdjustment(List<FIN_Payment__c> payments, Map<Id, FIN_Payment__c> oldMap) {
        List<FIN_RetroactiveAdjustment__c> retroactiveAdjustments = new List<FIN_RetroactiveAdjustment__c>();
        Id paymentRecordTypeId = Schema.SObjectType.FIN_RetroactiveAdjustment__c.getRecordTypeInfosByName().get('Payment').getRecordTypeId();

        Map<String, String> paymentRAMap = new Map<String, String>{
            'FIN_Order__c' => 'FIN_Order__c',
            'FIN_Region__c' => 'FIN_Region__c',
            'FIN_PaymentDate__c' => 'FIN_PaymentDate__c',
            'FIN_DepositDate__c' => 'FIN_DepositDate__c',
            'FIN_PaymentAdjustment__c' => 'FIN_PaymentAdjustment__c',
            'FIN_JournalEntryAmount__c' => 'FIN_JournalEntryAmount__c'
        };

        for (FIN_Payment__c payment : payments) {
            FIN_Payment__c oldP = oldMap.get(payment.Id);
            Integer i = 0;

            FIN_RetroactiveAdjustment__c newRetroactiveAdjustment = new FIN_RetroactiveAdjustment__c();
            newRetroactiveAdjustment.FIN_Payment__c = payment.Id;
            newRetroactiveAdjustment.FIN_Order__c = payment.FIN_Order__c;
            newRetroactiveAdjustment.RecordTypeId = paymentRecordTypeId;

            for (String str : paymentRAMap.keyset()) {
                if (payment.get(str) != oldP.get(str)) {
                    newRetroactiveAdjustment.put(paymentRAMap.get(str), payment.get(str));
                    i++;
                }
            }

            if (i != 0) {
                retroactiveAdjustments.add(newRetroactiveAdjustment);
            }
        }

        insert retroactiveAdjustments;
    }

    public static void mapPaymentToRelatedSaleContract(List<FIN_Payment__c> payments) {
        for (FIN_Payment__c payment : payments) {
            if (payment.FIN_Order__r != null) {
                payment.Contract__c = payment.FIN_Order__r.ContractId;
            }
        }
    }

    public static void updateOwnerOnClassifiedRecord(List<FIN_Payment__c> payments) {
        for (FIN_Payment__c payment : payments) {
            if (!String.isBlank(payment.Owner.Name)) {
                if (payment.Owner.Name.contains('Unclassified') && !payment.FIN_PaymentUnclassified__c) {
                    payment.OwnerId = UserInfo.getUserId();
                }
            }
        }
    }

    public static void updateJournalEntrySignAndAmount(List<FIN_Payment__c> payments, Map<Id, FIN_Payment__c> oldMap) {
        Map<Id, FIN_Payment__c> paymentsWithNewJournalEntryAmount = new Map<Id, FIN_Payment__c>();
        Id paymentRecordTypeId = Schema.SObjectType.FIN_Journalizing_Item__c.getRecordTypeInfosByName().get('II Payments Record Type').getRecordTypeId();

        for (FIN_Payment__c payment : payments) {
            if (payment.FIN_PaymentAmount__c != oldMap.get(payment.Id).FIN_PaymentAmount__c && payment.FIN_Journalizing_Status__c != 'Posted') {
                paymentsWithNewJournalEntryAmount.put(payment.Id, payment);
            }
        }

        if (paymentsWithNewJournalEntryAmount.size() > 0) {
            List<FIN_Journalizing_Item__c> journalizingItems = [
                SELECT Id, FIN_Payment__c, FIN_JournalEntryAmount__c, FIN_JournalEntrySign__c
                FROM FIN_Journalizing_Item__c
                WHERE RecordTypeId = :paymentRecordTypeId
                AND FIN_Payment__c IN :paymentsWithNewJournalEntryAmount.keySet()
            ];

            if (journalizingItems.size() > 0) {
                for (FIN_Journalizing_Item__c journalizingItem : journalizingItems) {
                    journalizingItem.FIN_JournalEntryAmount__c = paymentsWithNewJournalEntryAmount.get(journalizingItem.FIN_Payment__c).FIN_JournalEntryAmount__c;
                    journalizingItem.FIN_JournalEntrySign__c = paymentsWithNewJournalEntryAmount.get(journalizingItem.FIN_Payment__c).FIN_JournalEntrySign__c;
                }

                update journalizingItems;
            }
        }
    }

    public static void updateSettlementJournalizingStatuses(List<FIN_Payment__c> payments) {
        for (FIN_Payment__c payment : payments) {
            if (payment.FIN_FinancialResponsibilty__c == 'AXS') {
                payment.FIN_Settlement_Status__c = 'ToBeSettled';
                payment.FIN_Journalizing_Status__c = 'ToBePosted';
                payment.FIN_Invoices_Status__c = 'ToBeInvoiced';
            } else if (payment.FIN_FinancialResponsibilty__c == 'N/A') {
                payment.FIN_Settlement_Status__c = 'NotApplicable';
                payment.FIN_Journalizing_Status__c = 'NotApplicable';
                payment.FIN_Invoices_Status__c = 'NotApplicable';
            }
            if (payment.FIN_Auto_Approved__c == true) {
                payment.FIN_ApprovalStatus__c = 'Approved';
            } else {
                payment.FIN_ApprovalStatus__c = 'New';
            }
        }
    }

    public static void updateApprovalStatus(List<FIN_Payment__c> payments, Map<Id, FIN_Payment__c> oldMap) {
        for (FIN_Payment__c payment : payments) {
            if (!payment.FIN_Auto_Approved__c && payment.FIN_ApprovalStatus__c == 'Approved') {
                if (payment.FIN_ApprovalStatus__c != oldMap.get(payment.Id).FIN_ApprovalStatus__c) {
                    payment.addError('Please populate the fields required for Approval: Sale, Contract, Library Association, Payment Amount');
                } else {
                    payment.FIN_ApprovalStatus__c = 'New';
                }
            } else if (payment.FIN_Auto_Approved__c && payment.FIN_ApprovalStatus__c == oldMap.get(payment.Id).FIN_ApprovalStatus__c && payment.FIN_ApprovalStatus__c == 'New') {
                payment.FIN_ApprovalStatus__c = 'Approved';
            }
        }
    }
}