force-app/main/default/objects/FIN_Journalizing_Item__c/FIN_Journalizing_Item__c.object-meta.xml
<CustomObject>
    <label>Journalizing Item</label>
    <nameField>
        <displayFormat>JI-{0000000000}</displayFormat>
        <label>Journalizing Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journalizing Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Journalizing_Item__c/fields/Payment_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Payment_Distribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Journalizing Items</relationshipLabel>
    <relationshipName>Journalizing_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <formula>FIN_PaymentAmount__c * FIN_JournalEntrySign__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_Payment__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_AdjustmentAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_AdjustmentAmount__c</fullName>
    <label>Distribution Adjustment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_DistributionAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmount__c</fullName>
    <label>Distribution Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <formula>FIN_DistributionAmount__c  * FIN_JournalEntrySign__c</formula>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distribution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/FIN_RetroactiveAdjustment__c.object-meta.xml
<CustomObject>
    <label>Retroactive Adjustment</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Retroactive Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retroactive Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_AdjustmentAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_AdjustmentAmount__c</fullName>
    <label>Adjustment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_DistributionAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_DistributionAmount__c</fullName>
    <label>Distribution Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_JournalEntryAmount__c.field-meta.xml
<CustomField>
    <fullName>FIN_JournalEntryAmount__c</fullName>
    <label>Journal Entry Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Retroactive Adjustments</relationshipLabel>
    <relationshipName>Retroactive_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_RetroactiveAdjustment__c/fields/FIN_Type__c.field-meta.xml
<CustomField>
    <fullName>FIN_Type__c</fullName>
    <formula>IF (NOT(ISBLANK(FIN_AdjustmentAmount__c)), &apos;Financial&apos; , &apos;Statistical&apos;)</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journalizing_Schedule__c/Journalizing_Schedule__c.object-meta.xml
<CustomObject>
    <label>Journalizing Schedule</label>
    <nameField>
        <displayFormat>JS-{0000000000}</displayFormat>
        <label>Journalizing Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journalizing Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journalizing_Schedule__c/fields/FIN_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Journalizing_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Journalizing_Schedule__c/fields/FIN_Type__c.field-meta.xml
<CustomField>
    <fullName>FIN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PDs</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_LibraryAssociation__c.field-meta.xml
<CustomField>
    <fullName>FIN_LibraryAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Library Association</label>
    <referenceTo>SBQQ__ContractedPrice__c</referenceTo>
    <relationshipLabel>Sales Transactions</relationshipLabel>
    <relationshipName>Sales_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/FIN_Type__c.field-meta.xml
<CustomField>
    <fullName>FIN_Type__c</fullName>
    <description>Ticket Category</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>CC Add On</fullName>
            </value>
            <value>
                <fullName>Misc</fullName>
            </value>
            <value>
                <fullName>Promoter Add On</fullName>
            </value>
            <value>
                <fullName>Venue Add On</fullName>
            </value>
            <value>
                <fullName>License Fee</fullName>
                <isActive>false</isActive>
                <label>License Fee</label>
            </value>
            <value>
                <fullName>Non revenue-bearing</fullName>
                <isActive>false</isActive>
                <label>Non revenue-bearing</label>
            </value>
            <value>
                <fullName>Revenue Center</fullName>
                <isActive>false</isActive>
                <label>Revenue Center</label>
            </value>
            <value>
                <fullName>Revenue-bearing</fullName>
                <isActive>false</isActive>
                <label>Revenue-bearing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__ContractedPrice__c/SBQQ__ContractedPrice__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__ContractedPriceHelp</customHelpPage>
    <description>Contracted (negotiated) price for a product for a given customer account.</description>
    <label>Contracted Price</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Contracted Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracted Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__ContractedPrice__c/fields/FIN_Status__c.field-meta.xml
<CustomField>
    <fullName>FIN_Status__c</fullName>
    <formula>IF (
    ISBLANK(SBQQ__EffectiveDate__c) &amp;&amp; ISBLANK(SBQQ__ExpirationDate__c),
    IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;,
    IF (
        NOT(ISBLANK(SBQQ__EffectiveDate__c)) &amp;&amp; NOT(ISBLANK(SBQQ__ExpirationDate__c)) &amp;&amp;
        TODAY()&lt;= SBQQ__ExpirationDate__c &amp;&amp; TODAY()&gt;= SBQQ__EffectiveDate__c,
        IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;,
        IF (
            NOT(ISBLANK(SBQQ__EffectiveDate__c)) &amp;&amp; ISBLANK(SBQQ__ExpirationDate__c) &amp;&amp; TODAY()&gt;= SBQQ__EffectiveDate__c,
            IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;,
            IF (
                NOT(ISBLANK(SBQQ__ExpirationDate__c)) &amp;&amp; ISBLANK(SBQQ__EffectiveDate__c) &amp;&amp; TODAY()&lt;= SBQQ__ExpirationDate__c,
                IMAGE(&quot;/img/samples/flag_green.gif&quot;, &quot;green&quot;) + &apos; Active&apos;, IMAGE(&apos;/img/samples/flag_red.gif&apos;, &apos;red&apos;) + &apos; Inactive&apos;)
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/FIN_Journalizing_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ToBePosted</fullName>
        <label>To be Posted</label>
    </customValue>
    <customValue>
        <fullName>InProgress</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>Exported</fullName>
    </customValue>
    <customValue>
        <fullName>Posted</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <customValue>
        <fullName>PartiallyPosted</fullName>
        <isActive>false</isActive>
        <label>Partially Posted</label>
    </customValue>
    <masterLabel>Journalizing Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/testClasses/FIN_PaymentDistributionHelperTest.cls
@IsTest
private class FIN_PaymentDistributionHelperTest {
    @IsTest
    static void testCreateRetroactiveAdjustment() {
        try {
            List<FIN_RetroactiveAdjustment__c> oldRetroList = [
                SELECT Id
                FROM FIN_RetroactiveAdjustment__c
            ];
            Id paymentRecordTypeId = Schema.SObjectType.FIN_RetroactiveAdjustment__c.getRecordTypeInfosByName().get('Payment Distribution').getRecordTypeId();
            Account acc = TestDataFactory.createAccount();
            Contact cont = TestDataFactory.createContactForAccount(acc.Id, 'test@g.com');
            Product2 pro = TestDataFactory.createProduct2();
            PricebookEntry standardPriceEntry = TestDataFactory.createPricebookEntry(pro.Id);
            Order ord = TestDataFactory.createTestOrder(acc.Id);
            OrderItem orderItem = TestDataFactory.createTestOrderLine(ord.Id, pro.Id, standardPriceEntry.Id);
            FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id, cont.Id);
            FIN_PaymentDistribution__c paymentdist = TestDataFactory.createPaymentDistribution(payment.Id,null, cont.Id);

            Test.startTest();
            paymentdist.FIN_AdjustmentAmount__c = 123;
            update paymentdist;

            List<FIN_RetroactiveAdjustment__c> newRetroList = [
                SELECT Id, RecordTypeId
                FROM FIN_RetroactiveAdjustment__c
            ];
            Test.stopTest();

           System.assertEquals(oldRetroList.size()+1, newRetroList.size());
           System.assertEquals(newRetroList[0].RecordTypeId, paymentRecordTypeId);
        } catch(Exception e) {
            System.debug(e.getMessage());
        }
    }

    @IsTest
    static void testUpdateJournalEntrySignAndAmount() {
        try {
            Account acc = TestDataFactory.createAccount();
            Contract parentContract = TestDataFactory.createParentContract(acc.Id);
            Contract contract = TestDataFactory.createContract(acc.Id, parentContract.Id);

            Order ord = TestDataFactory.createTestOrderWithContract(acc.Id, contract.Id);
            FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id, contract.Id);
            FIN_PaymentDistribution__c paymentdist = TestDataFactory.createPaymentDistribution(payment.Id,null, contract.Id);

            SBQQ__ContractedPrice__c la = TestDataFactory.createLibraryAssociation(acc.Id);
            paymentdist.FIN_LibraryAssociation__c = la.Id;
            update paymentdist;

            Journalizing_Schedule__c js = TestDataFactory.createJournalizingSchedule(contract.Id);
            js.FIN_Type__c = 'PDs';
            js.FIN_Status__c = 'InProgress';
            update js;

            Integer numOfNewJI = JournalizingDataController.createJI(new List<Id>{
                paymentdist.Id
            }, 'PDs', js.Id);

            List<FIN_Journalizing_Item__c> journalizingItems = [
                SELECT Id, Payment_Distribution__c, FIN_JournalEntryAmount__c
                FROM FIN_Journalizing_Item__c
                WHERE Payment_Distribution__c = :paymentdist.Id
            ];

            Integer newAmount = 120;
            System.assertNotEquals(newAmount, journalizingItems[0].FIN_JournalEntryAmount__c);


            paymentdist.FIN_DistributionAmount__c = newAmount;
            update paymentdist;

            List<FIN_Journalizing_Item__c> journalizingItems2 = [
                SELECT Id, FIN_Payment__c, FIN_JournalEntryAmount__c
                FROM FIN_Journalizing_Item__c
                WHERE FIN_Payment__c = :paymentdist.Id
            ];

            System.assertEquals(newAmount, journalizingItems2[0].FIN_JournalEntryAmount__c);
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }
}