force-app/main/default/objects/FIN_InvoiceSchedule__c/FIN_InvoiceSchedule__c.object-meta.xml
<CustomObject>
    <label>Invoice Schedule</label>
    <nameField>
        <displayFormat>IS-{0000000000}</displayFormat>
        <label>Invoice Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_Payment__c/FIN_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/FIN_PaymentDistribution__c.object-meta.xml
<CustomObject>
    <label>Payment Distribution</label>
    <nameField>
        <displayFormat>PD-{0000000000}</displayFormat>
        <label>Payment Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Distributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Payment Distributions</relationshipLabel>
    <relationshipName>Payment_Distributions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIN_PaymentDistribution__c/fields/Invoices_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoices_Status__c</fullName>
    <label>Invoices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Invoices_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Payment__c.field-meta.xml
<CustomField>
    <fullName>FIN_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>FIN_Payment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Invoices_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoices_Status__c</fullName>
    <label>Invoices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Invoices_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FIN_PaymentDistribution__c.field-meta.xml
<CustomField>
    <fullName>FIN_PaymentDistribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution</label>
    <referenceTo>FIN_PaymentDistribution__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/FIN_Invoices_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>ToBeInvoiced</fullName>
        <label>To Be Invoiced</label>
    </customValue>
    <customValue>
        <fullName>InvoiceScheduled</fullName>
        <label>Invoice in Progress</label>
    </customValue>
    <customValue>
        <fullName>Invoiced</fullName>
    </customValue>
    <customValue>
        <fullName>Voided</fullName>
        <label>Void</label>
    </customValue>
    <customValue>
        <fullName>NotApplicable</fullName>
        <label>Not Applicable</label>
    </customValue>
    <masterLabel>Invoice Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/testClasses/InvoiceDataControllerTest.cls
@IsTest
public with sharing class InvoiceDataControllerTest {
    @IsTest
    static void testGetFilteredRecords() {
        Account acc = TestDataFactory.createAccount();

        Contract parentContract = TestDataFactory.createParentContract(acc.Id);
        Contract contract = TestDataFactory.createContract(acc.Id, parentContract.Id);

        Order ord = TestDataFactory.createTestOrderWithContract(acc.Id, contract.Id);
        FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id,contract.Id);
        Product2 pro = TestDataFactory.createProduct2();
        PricebookEntry standardPriceEntry = TestDataFactory.createPricebookEntry(pro.Id);
        OrderItem orderItem = TestDataFactory.createTestOrderLine(ord.Id, pro.Id, standardPriceEntry.Id);

        List<Contract> listPayments = InvoiceDataController.getFilteredSubContractsWithPayments('invoice',parentContract.Id, ord.Id, '', '','','');
//        Assert.areEqual(listPayments.size(), 1);

        List<Contract> listSalesTr = InvoiceDataController.getFilteredSubContractsWithSalesTransactions(parentContract.Id, ord.Id, '', '');
//        Assert.areEqual(listSalesTr.size(), 1);
    }

    @IsTest
    static void testFunctionalityInvoiceItems() {
        Account acc = TestDataFactory.createAccount();

        Contract parentContract = TestDataFactory.createParentContract(acc.Id);
        Contract contract = TestDataFactory.createContract(acc.Id, parentContract.Id);

        Order ord = TestDataFactory.createTestOrderWithContract(acc.Id, contract.Id);
        Product2 pro = TestDataFactory.createProduct2();
        PricebookEntry standardPriceEntry = TestDataFactory.createPricebookEntry(pro.Id);
        OrderItem orderItem = TestDataFactory.createTestOrderLine(ord.Id, pro.Id, standardPriceEntry.Id);

        FIN_Payment__c payment = TestDataFactory.createPayment(ord.Id,contract.Id);
        FIN_PaymentDistribution__c paymentdist = TestDataFactory.createPaymentDistribution(payment.Id, null,contract.Id);
        paymentdist.Invoices_Status__c = 'ToBeInvoiced';
        update paymentdist;

        FIN_InvoiceSchedule__c ii = TestDataFactory.createInvoiceSchedule(contract.Id);
        Map<Id, List<Id>> idIdMap = new Map<Id, List<Id>>();
        idIdMap.put(contract.Id, new List<Id>{paymentdist.Id});
        System.debug('idIdMap'+idIdMap);
        String json = JSON.serialize(idIdMap);
        System.debug('idIdMap'+idIdMap.toString());

        Integer result = InvoiceDataController.createInvoiceItems(json, 'PDs', new FIN_InvoiceSchedule__c(),ii.Id);
//        Assert.areEqual(result, 1);
        System.debug('after create');

        FIN_InvoiceSchedule__c ii2 = TestDataFactory.createInvoiceSchedule(contract.Id);
        Map<Id, List<Id>> idIdMap2 = new Map<Id, List<Id>>();
        idIdMap2.put(contract.Id, new List<Id>{payment.Id});
         json = idIdMap2.toString();
        Integer result2 = InvoiceDataController.createInvoiceItems(json, 'Payments', ii2,ii2.Id);
//        Assert.areEqual(result2, 1);

        FIN_InvoiceSchedule__c ii3 = TestDataFactory.createInvoiceSchedule(contract.Id);
        Map<Id, List<Id>> idIdMap3 = new Map<Id, List<Id>>();
        idIdMap3.put(contract.Id, new List<Id>{orderItem.Id});
        json = idIdMap3.toString();
        Integer result3 = InvoiceDataController.createInvoiceItems(json,'SalesTransactions', ii3,ii3.Id);
//        Assert.areEqual(result3, 1);


        List<Object> listPDs = InvoiceDataController.getRelatedRecords(ii.Id);
//        Assert.areEqual(listPDs.size(), 1);

        List<Object> listPayments = InvoiceDataController.getRelatedRecords(ii2.Id);
//        Assert.areEqual(listPayments.size(), 1);

        List<Object> listSalesTr = InvoiceDataController.getRelatedRecords(ii3.Id);
//        Assert.areEqual(listSalesTr.size(), 1);


        // Integer deletedPDsSize = InvoiceDataController.removeRelatedIIs(new List<Id>{paymentdist.Id}, ii.Id);
        // Assert.areEqual(deletedPDsSize, 1);

        // Integer deletedPaymentsSize = InvoiceDataController.removeRelatedIIs(new List<Id>{payment.Id}, ii2.Id);
        // Assert.areEqual(deletedPaymentsSize, 1);

        // Integer deletedSalesTrSize = InvoiceDataController.removeRelatedIIs(new List<Id>{orderItem.Id}, ii3.Id);
        // Assert.areEqual(deletedSalesTrSize, 1);
    }
}