force-app/main/default/objects/FIN_SystemDataLoadLog__c/FIN_SystemDataLoadLog__c.object-meta.xml
<CustomObject>
    <label>Finance Raw Data Logs</label>
    <nameField>
        <displayFormat>SDLL-{0000000000}</displayFormat>
        <label>System Data Load Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Raw Data Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleProcessCompleteStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleProcessCompleteStatus__c</fullName>
    <label>Business Rule Process Complete Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleStartTime__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleStartTime__c</fullName>
    <label>Business Rule Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_Process__c.field-meta.xml
<CustomField>
    <fullName>FIN_Process__c</fullName>
    <label>Process</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Payment_Distribution</fullName>
                <label>Payment Distribution</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_RecordsProcessed__c.field-meta.xml
<CustomField>
    <fullName>FIN_RecordsProcessed__c</fullName>
    <label>Processed records information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_ReturnedFromSaleTransactions__c.field-meta.xml
<CustomField>
    <fullName>FIN_ReturnedFromSaleTransactions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This indicates was the success status returned from sales transactions creation</description>
    <label>Returned from sale transactions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_StagingTableLoadBusinessApproved__c.field-meta.xml
<CustomField>
    <fullName>FIN_StagingTableLoadBusinessApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Staging Table Load Business Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/isMockup__c.field-meta.xml
<CustomField>
    <fullName>isMockup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isMockup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/selectors/FIN_SystemDataLoadLogSelector.cls
public with sharing class FIN_SystemDataLoadLogSelector {
    public static List<FIN_SystemDataLoadLog__c> getSystemDataLoadLogByIdIn(List<Id> systemDataLoadLogIds) {
        return [SELECT Id, FIN_StagingTableLoadBusinessApproved__c, FIN_Process__c, FIN_Region__c, isMockup__c, FIN_RecordsProcessed__c, FIN_BusinessRuleProcessCompleteStatus__c,
                FIN_ReturnedFromSaleTransactions__c, FIN_BusinessRuleStartTime__c
                FROM FIN_SystemDataLoadLog__c
                WHERE Id IN :systemDataLoadLogIds];
    }
}