force-app/main/default/objects/FIN_SystemDataLoadLog__c/FIN_SystemDataLoadLog__c.object-meta.xml
<CustomObject>
    <label>Finance Raw Data Logs</label>
    <nameField>
        <displayFormat>SDLL-{0000000000}</displayFormat>
        <label>System Data Load Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Raw Data Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleProcessCompleteStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleProcessCompleteStatus__c</fullName>
    <label>Business Rule Process Complete Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_Process__c.field-meta.xml
<CustomField>
    <fullName>FIN_Process__c</fullName>
    <label>Process</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Payment_Distribution</fullName>
                <label>Payment Distribution</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_ProcessDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_ProcessDate__c</fullName>
    <label>Process Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_StagingTableLoadBusinessApproved__c.field-meta.xml
<CustomField>
    <fullName>FIN_StagingTableLoadBusinessApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Staging Table Load Business Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_StagingTableLoadCompleteStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_StagingTableLoadCompleteStatus__c</fullName>
    <label>Raw Load Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
                <default>true</default>
                <label>In-Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related sales</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Finance Raw Data Logs</relationshipLabel>
    <relationshipName>Finance_Raw_Data_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/Master_Data_Load__c.object-meta.xml
<CustomObject>
    <label>Master Data Load</label>
    <nameField>
        <displayFormat>MDL-{0000}</displayFormat>
        <label>Master Data Load Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Data Load</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data_Load__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Load</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Master Data Load</relationshipLabel>
    <relationshipName>Master_Data_Load_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/fields/Payment_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Payment_Distribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution Load</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Master Data Load (Payment Distribution)</relationshipLabel>
    <relationshipName>Master_Data_Load1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/fields/ProcessDate__c.field-meta.xml
<CustomField>
    <fullName>ProcessDate__c</fullName>
    <label>ProcessDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Load</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Master Data Load (Sales)</relationshipLabel>
    <relationshipName>Master_Data_Load</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/testClasses/FIN_MasterDataLoadTriggerHandlerTest.cls
@isTest
public with sharing class FIN_MasterDataLoadTriggerHandlerTest {

@IsTest
static void sysDataLogCreationTest(){
    FIN_SystemDataLoadLog__c systemDataLoadLog = new FIN_SystemDataLoadLog__c();
    systemDataLoadLog.FIN_Process__c = 'Sales';
    systemDataLoadLog.FIN_ProcessDate__c = Datetime.now();
    systemDataLoadLog.FIN_StagingTableLoadBusinessApproved__c = true;
    systemDataLoadLog.FIN_StagingTableLoadCompleteStatus__c = 'Success';
    systemDataLoadLog.FIN_Region__c = 'US';
    systemDataLoadLog.FIN_BusinessRuleProcessCompleteStatus__c = 'In-Progress';
    insert systemDataLoadLog;

    FIN_SystemDataLoadLog__c systemDataLoadLogPayment = new FIN_SystemDataLoadLog__c();
    systemDataLoadLogPayment.FIN_Process__c = 'Payment';
    systemDataLoadLogPayment.FIN_ProcessDate__c = Datetime.now();
    systemDataLoadLogPayment.FIN_StagingTableLoadBusinessApproved__c = true;
    systemDataLoadLogPayment.FIN_StagingTableLoadCompleteStatus__c = 'Success';
    systemDataLoadLogPayment.FIN_Region__c = 'US';
    systemDataLoadLogPayment.FIN_BusinessRuleProcessCompleteStatus__c = 'In-Progress';
    insert systemDataLoadLogPayment;

    FIN_SystemDataLoadLog__c systemDataLoadLogPaymentDistr = new FIN_SystemDataLoadLog__c();
    systemDataLoadLogPaymentDistr.FIN_Process__c = 'Payment_Distribution';
    systemDataLoadLogPaymentDistr.FIN_ProcessDate__c = Datetime.now();
    systemDataLoadLogPaymentDistr.FIN_StagingTableLoadBusinessApproved__c = true;
    systemDataLoadLogPaymentDistr.FIN_StagingTableLoadCompleteStatus__c = 'Success';
    systemDataLoadLogPaymentDistr.FIN_Region__c = 'US';
    systemDataLoadLogPaymentDistr.FIN_BusinessRuleProcessCompleteStatus__c = 'In-Progress';
    insert systemDataLoadLogPaymentDistr;

    Test.setMock(HttpCalloutMock.class, new CalloutsMock());

    Test.startTest();
        Master_Data_Load__c mDL = new Master_Data_Load__c();
        mdl.ProcessDate__c = Date.today().addDays(-1);
        mdl.Sales__c = systemDataLoadLog.Id;
        mDL.Payment__c = systemDataLoadLogPayment.Id;
        mDL.Payment_Distribution__c = systemDataLoadLogPaymentDistr.Id;
        insert mDl;
    Test.stopTest();

    Assert.areEqual(1, [SELECT Id
                        FROM   Master_Data_Load__c
                        WHERE  Id = :mDL.Id].size());
}

    class CalloutsMock implements HttpCalloutMock {
            public HttpResponse respond(HttpRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"title":"TestTitle","shortDescription":"Short Description","longDescription":"Long Description","desiredSkills":"Test Desired Skills"}');
            response.setStatusCode(200);
            return response;
        }
    }
}