force-app/main/default/objects/FIN_SystemDataLoadLog__c/FIN_SystemDataLoadLog__c.object-meta.xml
<CustomObject>
    <label>Finance Raw Data Logs</label>
    <nameField>
        <displayFormat>SDLL-{0000000000}</displayFormat>
        <label>System Data Load Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Raw Data Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleEndTime__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleEndTime__c</fullName>
    <label>Run End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleProcessCompleteStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleProcessCompleteStatus__c</fullName>
    <label>Business Rule Process Complete Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_Process__c.field-meta.xml
<CustomField>
    <fullName>FIN_Process__c</fullName>
    <label>Process</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Payment_Distribution</fullName>
                <label>Payment Distribution</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_ProcessDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_ProcessDate__c</fullName>
    <label>Process Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_RecordsProcessed__c.field-meta.xml
<CustomField>
    <fullName>FIN_RecordsProcessed__c</fullName>
    <label>Processed records information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_SalesforceRulesEndTime__c.field-meta.xml
<CustomField>
    <fullName>FIN_SalesforceRulesEndTime__c</fullName>
    <label>Salesforce rules end time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_SalesforceRulesStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_SalesforceRulesStatus__c</fullName>
    <label>Salesforce rules status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RulesStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related sales</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Finance Raw Data Logs</relationshipLabel>
    <relationshipName>Finance_Raw_Data_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/Master_Data_Load__c.object-meta.xml
<CustomObject>
    <label>Master Data Load</label>
    <nameField>
        <displayFormat>MDL-{0000}</displayFormat>
        <label>Master Data Load Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Data Load</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data_Load__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Load</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Master Data Load</relationshipLabel>
    <relationshipName>Master_Data_Load_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/fields/Payment_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Payment_Distribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution Load</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Master Data Load (Payment Distribution)</relationshipLabel>
    <relationshipName>Master_Data_Load1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Load</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Master Data Load (Sales)</relationshipLabel>
    <relationshipName>Master_Data_Load</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_SystemDataLoadLog__c.field-meta.xml
<CustomField>
    <fullName>FIN_SystemDataLoadLog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>System Data Load Log</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RulesStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
    </customValue>
    <customValue>
        <fullName>In-Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Success Heroku</fullName>
    </customValue>
    <masterLabel>RulesStatus</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/services/FIN_ResponsePublisherService.cls
public with sharing class FIN_ResponsePublisherService {
    public static void processSystemDataLoadLogResponse(String responseBody) {
        SystemDataLoadLogResponseBodyWrapper responseBodyWrapper = (SystemDataLoadLogResponseBodyWrapper) JSON.deserialize(responseBody, SystemDataLoadLogResponseBodyWrapper.class);
        System.debug(responseBodyWrapper);
        List<FIN_SystemDataLoadLog__c> systemDataLoadLogs = FIN_SystemDataLoadLogSelector.getSystemDataLoadLogByIdIn(new List<String>{
                responseBodyWrapper.systemDataLoadLogId
        });
        if (systemDataLoadLogs.isEmpty()) {
            return;
        }
        FIN_SystemDataLoadLog__c systemDataLoadLog = systemDataLoadLogs.get(0);
        FIN_SystemDataLoadLog__c loadLog = systemDataLoadLog.clone(true, true, false, false);
        if (responseBodyWrapper.isProcessed && !responseBodyWrapper.hasErrors && !responseBodyWrapper.isFromMarkingProcessed) {
            abortCronJobs(systemDataLoadLog);
            FIN_AXSRuleEngineService.markRecordsOnHerokuAsProcessed(systemDataLoadLog);
            return;
        }
        if (responseBodyWrapper.isProcessed && !responseBodyWrapper.hasErrors && responseBodyWrapper.isFromMarkingProcessed) {
            loadLog.FIN_BusinessRuleProcessCompleteStatus__c = 'Success';
            loadLog.FIN_BusinessRuleEndTime__c = System.now();
            if (responseBodyWrapper.markedAsProcessedCount != null) {
                loadLog.FIN_RecordsProcessed__c += ',\n' + 'Marked as processed records: ' + responseBodyWrapper.markedAsProcessedCount;
            }
            if (responseBodyWrapper.failedRecords != null) {
                loadLog.FIN_RecordsProcessed__c += ',\n' + 'Records was failed: ' + responseBodyWrapper.failedRecords;
            }
            update loadLog;
            classifyRecords(systemDataLoadLog);
            return;
        }
        if (responseBodyWrapper.hasErrors) {
            Logger.log(new AuraHandledException(responseBodyWrapper.message + ' sysLoadLog: ' + systemDataLoadLog.Id), systemDataLoadLog.FIN_Process__c, systemDataLoadLog.FIN_Region__c);
            loadLog.FIN_SalesforceRulesStatus__c = 'Failure';
            loadLog.FIN_SalesforceRulesEndTime__c = System.now();
            update loadLog;
            return;
        }
        if (!responseBodyWrapper.isProcessed && !responseBodyWrapper.hasErrors && !responseBodyWrapper.isFromMarkingProcessed) {
            abortCronJobs(systemDataLoadLog);
            FIN_SystemDataLoadLogService.scheduleApexJob(systemDataLoadLog);
        }
        System.debug('In publisher: ' + responseBodyWrapper);
    }

    public static void classifyRecords(FIN_SystemDataLoadLog__c systemDataLoadLog) {
        Master_Data_Load__c mdl = MasterDataLoadSelector.getMasterDataLoadRecordByProcessDate(systemDataLoadLog.FIN_ProcessDate__c.date())[0];
        if (mdl.Sales__r.FIN_BusinessRuleProcessCompleteStatus__c == Constants.SUCCESS_STATUS
                && mdl.Payment__r.FIN_BusinessRuleProcessCompleteStatus__c == Constants.SUCCESS_STATUS
                && mdl.Payment_Distribution__r.FIN_BusinessRuleProcessCompleteStatus__c == Constants.SUCCESS_STATUS) {
            FIN_UnclassifiedRecordsController.runBatchJob(mdl);
        }
    }

    private static void abortCronJobs(FIN_SystemDataLoadLog__c systemDataLoadLog) {
        for (CronTrigger cronTrigger : [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name LIKE :systemDataLoadLog.FIN_Process__c + ' ' + Constants.SYSTEM_DATA_LOAD_LOG_JOB_NAME + '%']) {
            System.abortJob(cronTrigger.Id);
        }
    }


    public class SystemDataLoadLogResponseBodyWrapper {
        public String systemDataLoadLogId;
        public String message;
        public Integer failedRecords;
        public Integer markedAsProcessedCount;
        public Integer salesTransactionsCount;
        public Integer status;
        public Boolean isProcessed;
        public Boolean isFromMarkingProcessed;
        public Boolean hasErrors;
    }
}