force-app/main/default/objects/FIN_SystemDataLoadLog__c/FIN_SystemDataLoadLog__c.object-meta.xml
<CustomObject>
    <label>Finance Raw Data Logs</label>
    <nameField>
        <displayFormat>SDLL-{0000000000}</displayFormat>
        <label>System Data Load Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Raw Data Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleEndTime__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleEndTime__c</fullName>
    <label>Run End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleProcessCompleteStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleProcessCompleteStatus__c</fullName>
    <label>Business Rule Process Complete Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleStartTime__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleStartTime__c</fullName>
    <label>Business Rule Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_OrderToGet__c.field-meta.xml
<CustomField>
    <fullName>FIN_OrderToGet__c</fullName>
    <label>Order to process</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_Process__c.field-meta.xml
<CustomField>
    <fullName>FIN_Process__c</fullName>
    <label>Process</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Payment_Distribution</fullName>
                <label>Payment Distribution</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_ProcessCompletionStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_ProcessCompletionStatus__c</fullName>
    <formula>IF ( AND ( ISPICKVAL(FIN_StagingTableLoadCompleteStatus__c,&quot;SUCCESS&quot;),ISPICKVAL(FIN_BusinessRuleProcessCompleteStatus__c,&quot;SUCCESS&quot;)) , &quot;Success&quot; , &quot;In-Progress&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Process Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_ProcessDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_ProcessDate__c</fullName>
    <label>Process Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_SalesforceRulesStartTime__c.field-meta.xml
<CustomField>
    <fullName>FIN_SalesforceRulesStartTime__c</fullName>
    <label>Salesforce rules start time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_SalesforceRulesStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_SalesforceRulesStatus__c</fullName>
    <label>Salesforce rules status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RulesStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_StagingTableLoadBusinessApproved__c.field-meta.xml
<CustomField>
    <fullName>FIN_StagingTableLoadBusinessApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Staging Table Load Business Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_ToastNotification__e/FIN_ToastNotification__e.object-meta.xml
<CustomObject>
    <label>FIN_ToastNotification</label>
    <pluralLabel>FIN_ToastNotifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/Master_Data_Load__c/Master_Data_Load__c.object-meta.xml
<CustomObject>
    <label>Master Data Load</label>
    <nameField>
        <displayFormat>MDL-{0000}</displayFormat>
        <label>Master Data Load Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Data Load</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data_Load__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/fields/ProcessDate__c.field-meta.xml
<CustomField>
    <fullName>ProcessDate__c</fullName>
    <label>ProcessDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RulesStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
    </customValue>
    <customValue>
        <fullName>In-Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Success Heroku</fullName>
    </customValue>
    <masterLabel>RulesStatus</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/triggerHandlers/FIN_SystemDataLoadLogTriggerHandler.cls
public class FIN_SystemDataLoadLogTriggerHandler extends TriggerHandler {
    protected override void afterInsert() {
        for (FIN_SystemDataLoadLog__c dataLoadLog : (List<FIN_SystemDataLoadLog__c>) this.triggerNew) {
            checkMasterDataLoadRecord(dataLoadLog);
        }
        addOrderToDataLoadRecord((List<FIN_SystemDataLoadLog__c>) this.triggerNew);
    }
    protected override void beforeUpdate() {
        for (FIN_SystemDataLoadLog__c dataLoadLog : (List<FIN_SystemDataLoadLog__c>) this.triggerNew) {
            if (dataLoadLog.FIN_StagingTableLoadBusinessApproved__c && dataLoadLog.FIN_BusinessRuleStartTime__c == null && dataLoadLog.FIN_BusinessRuleProcessCompleteStatus__c == null) {
               dataLoadLog.FIN_BusinessRuleStartTime__c = System.now();
               dataLoadLog.FIN_BusinessRuleProcessCompleteStatus__c= 'In-Progress';
            }
            if (dataLoadLog.FIN_BusinessRuleProcessCompleteStatus__c == 'Success' && dataLoadLog.FIN_SalesforceRulesStartTime__c == null) {
                dataLoadLog.FIN_SalesforceRulesStartTime__c = System.now();
                dataLoadLog.FIN_SalesforceRulesStatus__c = 'In-Progress';
            }
        }
    }

    protected override void afterUpdate() {
        for (FIN_SystemDataLoadLog__c dataLoadLog : (List<FIN_SystemDataLoadLog__c>) this.triggerNew) {
            if (((dataLoadLog.FIN_BusinessRuleProcessCompleteStatus__c != 'In-Progress' && dataLoadLog.FIN_BusinessRuleProcessCompleteStatus__c != null)
                    || (dataLoadLog.FIN_SalesforceRulesStatus__c != 'In-Progress' && dataLoadLog.FIN_SalesforceRulesStatus__c != null))
                && dataLoadLog.FIN_StagingTableLoadBusinessApproved__c) {
                if (dataLoadLog.FIN_BusinessRuleProcessCompleteStatus__c == 'Success'
                        && dataLoadLog.FIN_SalesforceRulesStatus__c == 'Failure') {
                } else {
                    if (dataLoadLog.FIN_BusinessRuleProcessCompleteStatus__c == 'Success Heroku') {
                        FIN_SystemDataLoadLogService.scheduleApexJob(dataLoadLog);
                    }
                    if (dataLoadLog.FIN_SalesforceRulesStatus__c == 'In-Progress') {
                        FIN_AXSRuleEngineService.processSettlementRuleEngineFromSystemDataLoadLog(dataLoadLog);
                    }
                }
            } else {
                if (dataLoadLog.FIN_BusinessRuleEndTime__c == null) {
                    checkMasterDataLoadRecord(dataLoadLog);
                }
            }
            if (dataLoadLog.FIN_ProcessCompletionStatus__c != null && dataLoadLog.FIN_ProcessCompletionStatus__c != 'In-Progress') {
//                FIN_SystemDataLoadLogService.sendNotification(dataLoadLog.FIN_BusinessRuleProcessCompleteStatus__c,
//                        dataLoadLog.FIN_Region__c, dataLoadLog);
                EventBus.publish(new FIN_ToastNotification__e(Status__c = dataLoadLog.FIN_ProcessCompletionStatus__c,
                        Message__c = 'Your process was '
                                + (dataLoadLog.FIN_ProcessCompletionStatus__c == Constants.SUCCESS_STATUS ? 'finished successfully' : 'failed please review the errors')));
            }
        }
    }

    private static void checkMasterDataLoadRecord(FIN_SystemDataLoadLog__c dataLoadLog) {
        List<Master_Data_Load__c> mdlList = MasterDataLoadSelector.getMasterDataLoadRecordByProcessDate(dataLoadLog.FIN_ProcessDate__c.date());
        Master_Data_Load__c mdl = mdlList.isEmpty() ? new Master_Data_Load__c() : mdlList[0];
        mdl.put(Constants.getFinProcessMap().get(dataLoadLog.FIN_Process__c), dataLoadLog.Id);
        mdl.ProcessDate__c = dataLoadLog.FIN_ProcessDate__c.date();
        mdl.FIN_Region__c = dataLoadLog.FIN_Region__c;
        upsert mdl;
    }

    private static void addOrderToDataLoadRecord(List<FIN_SystemDataLoadLog__c> dataLoadLogs) {
        List<FIN_SystemDataLoadLog__c> systemDataLoadLogs = new List<FIN_SystemDataLoadLog__c>();
        for (FIN_SystemDataLoadLog__c dataLoadLog : dataLoadLogs) {
            FIN_SystemDataLoadLog__c systemDataLoadLog = new FIN_SystemDataLoadLog__c();
            systemDataLoadLog.Id = dataLoadLog.Id;
            systemDataLoadLog.FIN_OrderToGet__c = Constants.getOrderForSystemDataLoadLogRecords().get(dataLoadLog.FIN_Process__c);
            systemDataLoadLogs.add(systemDataLoadLog);
        }
        update systemDataLoadLogs;
    }
}