force-app/main/default/objects/FIN_SystemDataLoadLog__c/FIN_SystemDataLoadLog__c.object-meta.xml
<CustomObject>
    <label>Finance Raw Data Logs</label>
    <nameField>
        <displayFormat>SDLL-{0000000000}</displayFormat>
        <label>System Data Load Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Raw Data Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleEndTime__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleEndTime__c</fullName>
    <label>Run End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleProcessCompleteStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleProcessCompleteStatus__c</fullName>
    <label>Business Rule Process Complete Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleStartTime__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleStartTime__c</fullName>
    <label>Business Rule Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_Process__c.field-meta.xml
<CustomField>
    <fullName>FIN_Process__c</fullName>
    <label>Process</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Payment_Distribution</fullName>
                <label>Payment Distribution</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_ProcessDate__c.field-meta.xml
<CustomField>
    <fullName>FIN_ProcessDate__c</fullName>
    <label>Process Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_SalesforceRulesStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_SalesforceRulesStatus__c</fullName>
    <label>Salesforce rules status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RulesStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_StagingTableLoadCompleteStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_StagingTableLoadCompleteStatus__c</fullName>
    <label>Raw Load Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
                <default>true</default>
                <label>In-Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related sales</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Finance Raw Data Logs</relationshipLabel>
    <relationshipName>Finance_Raw_Data_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/Master_Data_Load__c.object-meta.xml
<CustomObject>
    <label>Master Data Load</label>
    <nameField>
        <displayFormat>MDL-{0000}</displayFormat>
        <label>Master Data Load Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Data Load</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data_Load__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/fields/ProcessDate__c.field-meta.xml
<CustomField>
    <fullName>ProcessDate__c</fullName>
    <label>ProcessDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Load</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Master Data Load (Sales)</relationshipLabel>
    <relationshipName>Master_Data_Load</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RulesStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
    </customValue>
    <customValue>
        <fullName>In-Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Success Heroku</fullName>
    </customValue>
    <masterLabel>RulesStatus</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/testClasses/FIN_SystemDataLoadLogTest.cls
@IsTest
public with sharing class FIN_SystemDataLoadLogTest {
    @IsTest
    static void testAfterInProgressInsert() {
        try {
            FIN_SystemDataLoadLog__c systemDataLoadLog = new FIN_SystemDataLoadLog__c(
                FIN_Process__c = 'Sales',
                FIN_ProcessDate__c = Date.today(),
                FIN_StagingTableLoadCompleteStatus__c = 'Success',
                FIN_BusinessRuleStartTime__c = DateTime.newInstance(2022, 2, 11, 8, 6, 16),
                FIN_BusinessRuleEndTime__c = DateTime.newInstance(2022, 2, 12, 8, 6, 16),
                FIN_Region__c = 'US',
                FIN_BusinessRuleProcessCompleteStatus__c = 'Success',
                FIN_SalesforceRulesStatus__c = 'In-Progress'
            );

            Master_Data_Load__c mdl = new Master_Data_Load__c (
                ProcessDate__c = Date.today(),
                FIN_Region__c = 'US',
                Sales__c = systemDataLoadLog.Id
            );

            Test.startTest();
            insert systemDataLoadLog;
            insert mdl;
            Test.stopTest();
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }

    @IsTest
    static void testAfterSuccessInsert() {
        try {
            FIN_SystemDataLoadLog__c systemDataLoadLog = new FIN_SystemDataLoadLog__c(
                FIN_Process__c = 'Sales',
                FIN_ProcessDate__c = Date.today(),
                FIN_StagingTableLoadCompleteStatus__c = 'Success',
                FIN_BusinessRuleStartTime__c = DateTime.newInstance(2022, 2, 11, 8, 6, 16),
                FIN_BusinessRuleEndTime__c = DateTime.newInstance(2022, 2, 12, 8, 6, 16),
                FIN_Region__c = 'US',
                FIN_BusinessRuleProcessCompleteStatus__c = 'Success'
            );

            Master_Data_Load__c mdl = new Master_Data_Load__c (
                ProcessDate__c = Date.today(),
                FIN_Region__c = 'US',
                Sales__c = systemDataLoadLog.Id
            );

            Test.startTest();
            insert systemDataLoadLog;
            insert mdl;
            Test.stopTest();
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }

    @IsTest
    static void testAfterFailureInsert() {
        try {
            FIN_SystemDataLoadLog__c systemDataLoadLog = new FIN_SystemDataLoadLog__c(
                FIN_Process__c = 'Sales',
                FIN_ProcessDate__c = Date.today(),
                FIN_StagingTableLoadCompleteStatus__c = 'Success',
                FIN_BusinessRuleStartTime__c = DateTime.newInstance(2022, 2, 11, 8, 6, 16),
                FIN_BusinessRuleEndTime__c = DateTime.newInstance(2022, 2, 12, 8, 6, 16),
                FIN_Region__c = 'US',
                FIN_BusinessRuleProcessCompleteStatus__c = 'Failure'
            );

            Test.startTest();
            insert systemDataLoadLog;
            Test.stopTest();
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }
}