force-app/main/default/objects/FIN_SystemDataLoadLog__c/FIN_SystemDataLoadLog__c.object-meta.xml
<CustomObject>
    <label>Finance Raw Data Logs</label>
    <nameField>
        <displayFormat>SDLL-{0000000000}</displayFormat>
        <label>System Data Load Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Raw Data Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleProcessCompleteStatus__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleProcessCompleteStatus__c</fullName>
    <label>Business Rule Process Complete Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_BusinessRuleStartTime__c.field-meta.xml
<CustomField>
    <fullName>FIN_BusinessRuleStartTime__c</fullName>
    <label>Business Rule Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_Process__c.field-meta.xml
<CustomField>
    <fullName>FIN_Process__c</fullName>
    <label>Process</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Payment_Distribution</fullName>
                <label>Payment Distribution</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/FIN_StagingTableLoadBusinessApproved__c.field-meta.xml
<CustomField>
    <fullName>FIN_StagingTableLoadBusinessApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Staging Table Load Business Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/IsBackfillLoad__c.field-meta.xml
<CustomField>
    <fullName>IsBackfillLoad__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is backfill load</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/isMockup__c.field-meta.xml
<CustomField>
    <fullName>isMockup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isMockup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FIN_SystemDataLoadLog__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related sales</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Finance Raw Data Logs</relationshipLabel>
    <relationshipName>Finance_Raw_Data_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/Master_Data_Load__c.object-meta.xml
<CustomObject>
    <label>Master Data Load</label>
    <nameField>
        <displayFormat>MDL-{0000}</displayFormat>
        <label>Master Data Load Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Data Load</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data_Load__c/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Load</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Master Data Load</relationshipLabel>
    <relationshipName>Master_Data_Load_Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/fields/Payment_Distribution__c.field-meta.xml
<CustomField>
    <fullName>Payment_Distribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Distribution Load</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Master Data Load (Payment Distribution)</relationshipLabel>
    <relationshipName>Master_Data_Load1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/fields/ProcessDate__c.field-meta.xml
<CustomField>
    <fullName>ProcessDate__c</fullName>
    <label>ProcessDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Data_Load__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Load</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Master Data Load (Sales)</relationshipLabel>
    <relationshipName>Master_Data_Load</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_Region__c.field-meta.xml
<CustomField>
    <fullName>FIN_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIN_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FIN_SystemDataLoadLog__c.field-meta.xml
<CustomField>
    <fullName>FIN_SystemDataLoadLog__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>System Data Load Log</label>
    <referenceTo>FIN_SystemDataLoadLog__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/FIN_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>US</label>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>SWE</fullName>
        <isActive>false</isActive>
        <label>SWE</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <isActive>false</isActive>
        <label>UK</label>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
        <isActive>false</isActive>
        <label>Global</label>
    </customValue>
    <customValue>
        <fullName>AMEA</fullName>
        <isActive>false</isActive>
        <label>AMEA</label>
    </customValue>
    <customValue>
        <fullName>FRA</fullName>
        <isActive>false</isActive>
        <label>FRA</label>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
        <isActive>false</isActive>
        <label>CAN</label>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/selectors/MasterDataLoadSelector.cls
public with sharing class MasterDataLoadSelector {
    public static List<Master_Data_Load__c> getMasterDataLoadRecordByProcessDate(Date systemLoadLogProcessDate) {
        return [SELECT Id, Sales__c, Payment_Distribution__c, Payment__c, ProcessDate__c, FIN_Region__c,
                Sales__r.FIN_BusinessRuleProcessCompleteStatus__c, Payment__r.FIN_BusinessRuleProcessCompleteStatus__c, Payment_Distribution__r.FIN_BusinessRuleProcessCompleteStatus__c
                FROM Master_Data_Load__c
                WHERE ProcessDate__c = :systemLoadLogProcessDate];
    }

    public static List<Master_Data_Load__c> getMasterDataLoadRecordWithLookupDataById(Id masterDataLoadId) {
        return [SELECT Id, Payment__r.FIN_StagingTableLoadBusinessApproved__c, Sales__r.FIN_StagingTableLoadBusinessApproved__c,
                Payment_Distribution__r.FIN_StagingTableLoadBusinessApproved__c, Payment__r.FIN_Process__c, Sales__r.FIN_Process__c,
                Payment_Distribution__r.FIN_Process__c, FIN_Region__c, Sales__r.isMockup__c, Payment__r.isMockup__c, Payment_Distribution__r.isMockup__c,
                Sales__r.FIN_BusinessRuleStartTime__c, Payment_Distribution__r.FIN_BusinessRuleStartTime__c, Payment__r.FIN_BusinessRuleStartTime__c,
                Sales__r.Id, Payment__r.Id, Payment_Distribution__r.Id, Sales__r.IsBackfillLoad__c, Payment_Distribution__r.IsBackfillLoad__c, Payment__r.IsBackfillLoad__c,
                Sales__r.FIN_BusinessRuleProcessCompleteStatus__c, Payment__r.FIN_BusinessRuleProcessCompleteStatus__c, Payment_Distribution__r.FIN_BusinessRuleProcessCompleteStatus__c
                FROM Master_Data_Load__c
                WHERE Id = :masterDataLoadId];
    }
}