force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/controllers/Fin_OrderExtController.cls
public with sharing class Fin_OrderExtController {
    private Id OrderId;
    public Fin_OrderExtController(ApexPages.StandardController stdController) {
        OrderId = stdController.getId();
    }
    public PageReference onSubmit() {
        if (OrderId != null) {
            if (!Test.isRunningTest()) {
                SBAA.ApprovalAPI.submit(OrderId, SBAA__Approval__c.Order__c);
            }
        }
        return new PageReference('/' + OrderId);
    }
    public PageReference onRecall() {
        if (OrderId != null) {
            //if(!Test.isRunningTest()){
            SBAA.ApprovalAPI.recall(OrderId, SBAA__Approval__c.Order__c);
            //}
        }
        return new PageReference('/' + OrderId);
    }
}