force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/controllers/Fin_ContractExtController.cls
public with sharing class Fin_ContractExtController {
    private Id ContractId;
    public Fin_ContractExtController (ApexPages.StandardController stdController) {
        ContractId = stdController.getId();
    }
    public PageReference onSubmit() {
        if (ContractId != null) {
            //if(!Test.isRunningTest()){
                SBAA.ApprovalAPI.submit(ContractId, SBAA__Approval__c.Contract__c);
            //}
        }
        return new PageReference('/' + ContractId);
    }
    public PageReference onRecall() {
        if (ContractId != null) {
            //if(!Test.isRunningTest()){
                SBAA.ApprovalAPI.recall(ContractId, SBAA__Approval__c.Contract__c);
            //}    
        }
        return new PageReference('/' + ContractId);
    }
}