force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/FIN_AXS_Rule_Engine__c.field-meta.xml
<CustomField>
    <fullName>FIN_AXS_Rule_Engine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AXS Rule Engine</label>
    <referenceTo>FIN_AXSRuleEngine__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/controllers/Fin_AXSRuleEngineExtController.cls
public with sharing class Fin_AXSRuleEngineExtController {
    private Id FIN_AXSRuleEngineId;
    public Fin_AXSRuleEngineExtController (ApexPages.StandardController stdController) {
        FIN_AXSRuleEngineId = stdController.getId();
    }
    public PageReference onSubmit() {
        if (FIN_AXSRuleEngineId != null) {
            //if(!Test.isRunningTest()){
                SBAA.ApprovalAPI.submit(FIN_AXSRuleEngineId, SBAA__Approval__c.FIN_AXS_Rule_Engine__c);
            //}    
        }
        return new PageReference('/' + FIN_AXSRuleEngineId);
    }
    public PageReference onRecall() {
        if (FIN_AXSRuleEngineId != null) {
            //if(!Test.isRunningTest()){
                SBAA.ApprovalAPI.recall(FIN_AXSRuleEngineId, SBAA__Approval__c.FIN_AXS_Rule_Engine__c);
            //}   
        }
        return new PageReference('/' + FIN_AXSRuleEngineId);
    }
}